import { BUILDING_IDS, type BuildingDefinition, type BuildingId, type ProductionMethod } from './types';

/**
 * Catálogo de edifícios (setores produtivos) e métodos de produção.
 *
 * Valores POR NÍVEL. Empregos em pessoas (escala dos Pops); insumos e produção em unidades
 * (R$ bi/ano a preços-base). Calibração (testada em `tests/industry-data.test.ts`):
 * - Salário de referência por emprego = `POP_TYPES[t].income × 12 / 1e9` (R$ bi/ano por pessoa).
 * - Método padrão: margem (receita − insumos − salários)/receita entre 5% e 35% a preços 1.
 *   Agro e indústria ~10–18%; extração, energia e finanças ~25–30% (capital intensivo: o custo de
 *   capital entra como insumo de `machinery`, `finance` e `services`); refino ~9%.
 * - Métodos avançados (`minTech`): menos empregos, mais produção, mais insumos de capital/tecnologia.
 *   Lucro por nível ≈ o do padrão a salários de referência (nível 2 ≈ 0,95–1,05×; nível 3 ≈ 1,1×),
 *   mas com folha bem menor: passam a valer a pena quando os salários sobem ou a tecnologia avança.
 * - `business` = donos/diretores (~1,5–3% do nível; bancos e polos de tecnologia um pouco mais).
 * - Setor público e informal não seguem a regra de margem (público é pago pelo orçamento;
 *   informal não tem insumos e rende ~1/3 do formal por pessoa).
 * - Construção: o custo de 1 ponto ≈ (insumos + salários) / (pontos × 12) ≈ R$ 3,5–4,6 mi; a cesta
 *   de insumos segue a referência do design (cimento ~45%, aço ~30%, máquinas ~15%, transporte ~10%).
 * - `profileWeights`: peso na geração inicial = Σ peso × fator do estado (fatores de `stateFactors`,
 *   0..1; renda = PIB per capita/60). Comparáveis entre edifícios do mesmo tipo principal de Pop
 *   (agricultores → agro; operários → extração/energia/indústria) e proporcionais ao emprego nacional.
 */

export const BUILDINGS: Record<BuildingId, BuildingDefinition> = {
  // -------------------------------------------------------------------------
  // Agropecuária
  // -------------------------------------------------------------------------
  farm_grain: {
    id: 'farm_grain',
    name: 'Lavoura de grãos',
    icon: 'wheat',
    sector: 'agro',
    description: 'Arroz, feijão, milho e trigo para o mercado interno e a ração animal.',
    constructionCost: 150,
    buildableBy: ['private', 'state'],
    resource: 'arable',
    profileWeights: { agro: 1, urbanization: 0.1 },
    methods: [
      {
        id: 'grain_family',
        name: 'Lavoura familiar',
        description: 'Pequenas e médias propriedades, pouca máquina e muito trabalho manual.',
        jobs: { farmers: 3600, workers: 500, business: 60 },
        inputs: { chemicals: 0.025, fuel: 0.015, transport: 0.02, finance: 0.005 },
        outputs: { grain: 0.235 },
      },
      {
        id: 'grain_mechanized',
        name: 'Lavoura mecanizada',
        description: 'Tratores, colheitadeiras e adubação intensiva: mais grão com menos gente.',
        jobs: { farmers: 2000, workers: 400, middle_class: 60, business: 60 },
        inputs: {
          chemicals: 0.05,
          machinery: 0.03,
          fuel: 0.035,
          transport: 0.03,
          electricity: 0.005,
          finance: 0.01,
        },
        outputs: { grain: 0.285 },
        minTech: 1,
        pollution: 0.15,
      },
      {
        id: 'grain_precision',
        name: 'Agricultura de precisão',
        description: 'Sensores, GPS e software decidem plantio e adubação talhão a talhão.',
        jobs: { farmers: 1100, workers: 200, middle_class: 150, tech_workers: 30, business: 60 },
        inputs: {
          chemicals: 0.055,
          machinery: 0.045,
          electronics: 0.01,
          software: 0.01,
          fuel: 0.035,
          transport: 0.035,
          electricity: 0.008,
          finance: 0.012,
        },
        outputs: { grain: 0.32 },
        minTech: 3,
        pollution: 0.1,
      },
    ],
  },
  farm_soy: {
    id: 'farm_soy',
    name: 'Lavoura de soja',
    icon: 'sprout',
    sector: 'agro',
    description: 'Grandes áreas de soja no Cerrado e no Sul, voltadas sobretudo à exportação.',
    constructionCost: 180,
    buildableBy: ['private', 'state'],
    resource: 'arable',
    profileWeights: { agro: 0.5, income: 0.4 },
    methods: [
      {
        id: 'soy_conventional',
        name: 'Plantio convencional',
        description: 'Preparo do solo, adubação e colheita com mecanização parcial.',
        jobs: { farmers: 2800, workers: 500, middle_class: 50, business: 80 },
        inputs: { chemicals: 0.05, machinery: 0.02, fuel: 0.025, transport: 0.035, finance: 0.01 },
        outputs: { soy: 0.31 },
        pollution: 0.2,
      },
      {
        id: 'soy_no_till',
        name: 'Plantio direto mecanizado',
        description: 'Frota própria de máquinas e duas safras por ano no mesmo talhão.',
        jobs: { farmers: 1700, workers: 350, middle_class: 80, business: 80 },
        inputs: {
          chemicals: 0.075,
          machinery: 0.04,
          fuel: 0.035,
          transport: 0.045,
          electricity: 0.005,
          finance: 0.015,
        },
        outputs: { soy: 0.355 },
        minTech: 1,
        pollution: 0.2,
      },
      {
        id: 'soy_precision',
        name: 'Agricultura de precisão',
        description: 'Máquinas autônomas, drones e dados de satélite em toda a lavoura.',
        jobs: { farmers: 1000, workers: 200, middle_class: 150, tech_workers: 40, business: 80 },
        inputs: {
          chemicals: 0.08,
          machinery: 0.05,
          electronics: 0.012,
          software: 0.012,
          fuel: 0.04,
          transport: 0.05,
          electricity: 0.008,
          finance: 0.018,
        },
        outputs: { soy: 0.4 },
        minTech: 2,
        pollution: 0.15,
      },
    ],
  },
  ranch: {
    id: 'ranch',
    name: 'Pecuária',
    icon: 'beef',
    sector: 'agro',
    description: 'Criação de bovinos, suínos e aves; consome grãos e soja como ração.',
    constructionCost: 140,
    buildableBy: ['private', 'state'],
    resource: 'pasture',
    profileWeights: { agro: 1.2 },
    methods: [
      {
        id: 'ranch_extensive',
        name: 'Pecuária extensiva',
        description: 'Gado solto em grandes pastagens, com baixa lotação por hectare.',
        jobs: { farmers: 3000, workers: 700, business: 70 },
        inputs: { grain: 0.03, soy: 0.02, chemicals: 0.01, transport: 0.02, finance: 0.005 },
        outputs: { meat: 0.25 },
        pollution: 0.35,
      },
      {
        id: 'ranch_feedlot',
        name: 'Confinamento e integração',
        description: 'Engorda em confinamento e granjas integradas à agroindústria.',
        jobs: { farmers: 1800, workers: 600, middle_class: 60, business: 70 },
        inputs: {
          grain: 0.08,
          soy: 0.06,
          chemicals: 0.02,
          machinery: 0.015,
          electricity: 0.01,
          transport: 0.03,
          finance: 0.01,
        },
        outputs: { meat: 0.36 },
        minTech: 1,
        pollution: 0.3,
      },
      {
        id: 'ranch_precision',
        name: 'Pecuária de precisão',
        description: 'Melhoramento genético, rastreabilidade e manejo monitorado por sensores.',
        jobs: { farmers: 1100, workers: 400, middle_class: 120, tech_workers: 20, business: 70 },
        inputs: {
          grain: 0.09,
          soy: 0.07,
          chemicals: 0.03,
          pharmaceuticals: 0.01,
          machinery: 0.02,
          electronics: 0.008,
          software: 0.005,
          electricity: 0.012,
          transport: 0.035,
          finance: 0.012,
        },
        outputs: { meat: 0.41 },
        minTech: 2,
        pollution: 0.2,
      },
    ],
  },
  plantation: {
    id: 'plantation',
    name: 'Lavouras permanentes',
    icon: 'coffee',
    sector: 'agro',
    description: 'Café, cana-de-açúcar, laranja, algodão e frutas para exportação e indústria.',
    constructionCost: 200,
    buildableBy: ['private', 'state'],
    resource: 'arable',
    profileWeights: { agro: 0.6, industry: 0.2 },
    methods: [
      {
        id: 'plantation_manual',
        name: 'Colheita manual',
        description: 'Plantio e colheita com muita mão de obra, inclusive temporária.',
        jobs: { farmers: 2800, workers: 1600, business: 70 },
        inputs: { chemicals: 0.035, fuel: 0.012, transport: 0.025, finance: 0.005 },
        outputs: { cash_crops: 0.255 },
      },
      {
        id: 'plantation_mechanized',
        name: 'Colheita mecanizada',
        description: 'Colhedoras de cana, café e algodão substituem o corte manual.',
        jobs: { farmers: 1700, workers: 700, middle_class: 60, business: 70 },
        inputs: {
          chemicals: 0.05,
          machinery: 0.035,
          fuel: 0.03,
          transport: 0.035,
          electricity: 0.005,
          finance: 0.01,
        },
        outputs: { cash_crops: 0.295 },
        minTech: 1,
        pollution: 0.15,
      },
      {
        id: 'plantation_irrigated',
        name: 'Fruticultura irrigada',
        description: 'Irrigação controlada por sensores e colheita escalonada o ano todo.',
        jobs: { farmers: 1100, workers: 450, middle_class: 120, tech_workers: 20, business: 70 },
        inputs: {
          chemicals: 0.06,
          machinery: 0.045,
          electronics: 0.01,
          software: 0.006,
          electricity: 0.02,
          fuel: 0.03,
          transport: 0.04,
          finance: 0.012,
        },
        outputs: { cash_crops: 0.34 },
        minTech: 2,
      },
    ],
  },
  forestry: {
    id: 'forestry',
    name: 'Silvicultura',
    icon: 'tree-pine',
    sector: 'agro',
    description: 'Florestas plantadas de eucalipto e pinus para celulose, móveis e construção.',
    constructionCost: 160,
    buildableBy: ['private', 'state'],
    resource: 'forest',
    profileWeights: { agro: 0.2, industry: 0.2 },
    methods: [
      {
        id: 'forestry_planted',
        name: 'Floresta plantada',
        description: 'Plantio, manejo e corte com equipes de campo.',
        jobs: { farmers: 2400, workers: 1400, business: 60 },
        inputs: { chemicals: 0.015, machinery: 0.01, fuel: 0.02, transport: 0.03, finance: 0.005 },
        outputs: { wood: 0.24 },
      },
      {
        id: 'forestry_mechanized',
        name: 'Colheita florestal mecanizada',
        description: 'Harvesters e forwarders cortam e empilham a madeira com poucos operadores.',
        jobs: { farmers: 1300, workers: 900, middle_class: 60, business: 60 },
        inputs: { chemicals: 0.02, machinery: 0.04, fuel: 0.035, transport: 0.04, finance: 0.008 },
        outputs: { wood: 0.265 },
        minTech: 1,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Extração
  // -------------------------------------------------------------------------
  mine: {
    id: 'mine',
    name: 'Mineração',
    icon: 'pickaxe',
    sector: 'extraction',
    description: 'Lavra de minério de ferro e outros minerais, sobretudo em MG e no PA.',
    constructionCost: 400,
    buildableBy: ['private', 'state'],
    resource: 'iron',
    strategic: true,
    profileWeights: { industry: 0.1, agro: 0.05 },
    methods: [
      {
        id: 'mine_open_pit',
        name: 'Mina a céu aberto',
        description: 'Escavação com caminhões fora de estrada e beneficiamento convencional.',
        jobs: { industrial_workers: 2600, middle_class: 300, business: 60 },
        inputs: {
          machinery: 0.12,
          fuel: 0.08,
          electricity: 0.05,
          chemicals: 0.02,
          transport: 0.1,
          finance: 0.04,
          services: 0.03,
        },
        outputs: { iron_ore: 0.76 },
        pollution: 0.5,
      },
      {
        id: 'mine_mechanized',
        name: 'Mineração mecanizada',
        description: 'Correias transportadoras e britagem na cava reduzem o transporte por caminhão.',
        jobs: { industrial_workers: 1700, middle_class: 300, tech_workers: 30, business: 60 },
        inputs: {
          machinery: 0.18,
          fuel: 0.1,
          electricity: 0.07,
          electronics: 0.01,
          chemicals: 0.025,
          transport: 0.12,
          finance: 0.05,
          services: 0.03,
        },
        outputs: { iron_ore: 0.9 },
        minTech: 1,
        pollution: 0.45,
      },
      {
        id: 'mine_autonomous',
        name: 'Mina autônoma',
        description: 'Caminhões e perfuratrizes autônomos operados a partir de centros de controle.',
        jobs: { industrial_workers: 900, middle_class: 250, tech_workers: 120, business: 60 },
        inputs: {
          machinery: 0.22,
          electronics: 0.04,
          software: 0.03,
          fuel: 0.08,
          electricity: 0.1,
          chemicals: 0.025,
          transport: 0.13,
          finance: 0.06,
          services: 0.03,
        },
        outputs: { iron_ore: 1.02 },
        minTech: 3,
        pollution: 0.35,
      },
    ],
  },
  oil_field: {
    id: 'oil_field',
    name: 'Campo de petróleo',
    icon: 'drill',
    sector: 'extraction',
    description: 'Exploração e produção de petróleo e gás em terra e no mar.',
    constructionCost: 500,
    buildableBy: ['private', 'state'],
    resource: 'oil',
    strategic: true,
    profileWeights: { industry: 0.05 },
    methods: [
      {
        id: 'oil_conventional',
        name: 'Produção convencional',
        description: 'Poços em terra e plataformas em águas rasas e profundas.',
        jobs: { industrial_workers: 2200, middle_class: 500, tech_workers: 50, business: 60 },
        inputs: {
          machinery: 0.2,
          steel: 0.04,
          fuel: 0.04,
          chemicals: 0.03,
          electricity: 0.03,
          transport: 0.06,
          finance: 0.08,
          services: 0.05,
        },
        outputs: { oil: 0.95 },
        pollution: 0.4,
      },
      {
        id: 'oil_deepwater',
        name: 'Águas ultraprofundas',
        description: 'Plataformas flutuantes no pré-sal, com poços mais produtivos e caros.',
        jobs: { industrial_workers: 1600, middle_class: 550, tech_workers: 120, business: 60 },
        inputs: {
          machinery: 0.3,
          steel: 0.06,
          electronics: 0.02,
          fuel: 0.05,
          chemicals: 0.035,
          electricity: 0.03,
          transport: 0.07,
          finance: 0.11,
          services: 0.06,
        },
        outputs: { oil: 1.17 },
        minTech: 1,
        pollution: 0.4,
      },
      {
        id: 'oil_digital',
        name: 'Campo digital',
        description: 'Plataformas automatizadas, monitoradas e operadas remotamente.',
        jobs: { industrial_workers: 900, middle_class: 450, tech_workers: 250, business: 60 },
        inputs: {
          machinery: 0.33,
          steel: 0.06,
          electronics: 0.05,
          software: 0.04,
          fuel: 0.04,
          chemicals: 0.035,
          electricity: 0.04,
          transport: 0.07,
          finance: 0.12,
          services: 0.05,
        },
        outputs: { oil: 1.28 },
        minTech: 3,
        pollution: 0.3,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Energia
  // -------------------------------------------------------------------------
  power_hydro: {
    id: 'power_hydro',
    name: 'Usina hidrelétrica',
    icon: 'waves',
    sector: 'energy',
    description: 'Base da matriz elétrica: energia barata, limitada pelos rios disponíveis.',
    constructionCost: 650,
    buildableBy: ['private', 'state'],
    resource: 'hydro',
    strategic: true,
    profileWeights: { industry: 0.2, agro: 0.2 },
    methods: [
      {
        id: 'hydro_dam',
        name: 'Usina com reservatório',
        description: 'Barragem e turbinas convencionais; custo concentrado no capital.',
        jobs: { industrial_workers: 1300, middle_class: 400, business: 40 },
        inputs: { machinery: 0.12, construction_materials: 0.03, services: 0.06, finance: 0.14 },
        outputs: { electricity: 0.6 },
      },
      {
        id: 'hydro_modernized',
        name: 'Turbinas modernizadas',
        description: 'Repotenciação, automação e telemetria ampliam a geração da mesma queda.',
        jobs: { industrial_workers: 800, middle_class: 350, tech_workers: 80, business: 40 },
        inputs: {
          machinery: 0.15,
          electronics: 0.03,
          software: 0.015,
          construction_materials: 0.03,
          services: 0.05,
          finance: 0.15,
        },
        outputs: { electricity: 0.68 },
        minTech: 2,
      },
    ],
  },
  power_thermal: {
    id: 'power_thermal',
    name: 'Usina termelétrica',
    icon: 'flame',
    sector: 'energy',
    description: 'Gera em qualquer lugar e a qualquer hora, mas queima combustível e polui.',
    constructionCost: 420,
    buildableBy: ['private', 'state'],
    profileWeights: { industry: 0.5, urbanization: 0.3 },
    methods: [
      {
        id: 'thermal_gas',
        name: 'Térmica a gás e óleo',
        description: 'Turbinas a gás natural e óleo combustível.',
        jobs: { industrial_workers: 1400, middle_class: 300, business: 40 },
        inputs: { fuel: 0.3, machinery: 0.06, services: 0.03, finance: 0.06 },
        outputs: { electricity: 0.62 },
        pollution: 0.6,
      },
      {
        id: 'thermal_combined',
        name: 'Ciclo combinado',
        description: 'Reaproveita o calor dos gases para gerar mais energia com o mesmo combustível.',
        jobs: { industrial_workers: 900, middle_class: 300, tech_workers: 40, business: 40 },
        inputs: { fuel: 0.32, machinery: 0.09, electronics: 0.01, services: 0.03, finance: 0.07 },
        outputs: { electricity: 0.685 },
        minTech: 1,
        pollution: 0.45,
      },
    ],
  },
  power_renewable: {
    id: 'power_renewable',
    name: 'Parque eólico e solar',
    icon: 'wind',
    sector: 'energy',
    description: 'Vento e sol do Nordeste e do Sul: sem combustível, mas intermitente.',
    constructionCost: 480,
    buildableBy: ['private', 'state'],
    resource: 'wind_solar',
    profileWeights: { agro: 0.2, industry: 0.1 },
    methods: [
      {
        id: 'renewable_wind',
        name: 'Parque eólico',
        description: 'Aerogeradores em terra conectados à rede.',
        jobs: { industrial_workers: 1200, middle_class: 300, business: 40 },
        inputs: { machinery: 0.1, electronics: 0.02, services: 0.04, finance: 0.12 },
        outputs: { electricity: 0.48 },
      },
      {
        id: 'renewable_hybrid',
        name: 'Complexo híbrido com baterias',
        description: 'Eólica, solar e armazenamento em baterias reduzem a intermitência.',
        jobs: { industrial_workers: 700, middle_class: 280, tech_workers: 80, business: 40 },
        inputs: {
          machinery: 0.12,
          electronics: 0.07,
          software: 0.01,
          services: 0.035,
          finance: 0.13,
        },
        outputs: { electricity: 0.56 },
        minTech: 2,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Indústria de base
  // -------------------------------------------------------------------------
  refinery: {
    id: 'refinery',
    name: 'Refinaria',
    icon: 'fuel',
    sector: 'heavy_industry',
    description: 'Transforma petróleo em diesel, gasolina, querosene e nafta petroquímica.',
    constructionCost: 550,
    buildableBy: ['private', 'state'],
    strategic: true,
    profileWeights: { industry: 0.12 },
    methods: [
      {
        id: 'refinery_basic',
        name: 'Refino convencional',
        description: 'Destilação e craqueamento com rendimento padrão de derivados.',
        jobs: { industrial_workers: 2600, middle_class: 600, tech_workers: 60, business: 60 },
        inputs: {
          oil: 1.6,
          electricity: 0.05,
          chemicals: 0.03,
          machinery: 0.05,
          transport: 0.06,
          finance: 0.04,
          services: 0.02,
        },
        outputs: { fuel: 1.85, chemicals: 0.35 },
        pollution: 0.55,
      },
      {
        id: 'refinery_integrated',
        name: 'Refinaria integrada à petroquímica',
        description: 'Unidades de conversão profunda e petroquímica no mesmo complexo.',
        jobs: { industrial_workers: 1800, middle_class: 600, tech_workers: 150, business: 60 },
        inputs: {
          oil: 1.75,
          electricity: 0.06,
          chemicals: 0.04,
          machinery: 0.07,
          electronics: 0.01,
          software: 0.01,
          transport: 0.065,
          finance: 0.05,
          services: 0.02,
        },
        outputs: { fuel: 1.9, chemicals: 0.53 },
        minTech: 2,
        pollution: 0.45,
      },
    ],
  },
  steel_mill: {
    id: 'steel_mill',
    name: 'Siderúrgica',
    icon: 'anvil',
    sector: 'heavy_industry',
    description: 'Produz aço a partir de minério de ferro, carvão e muita energia.',
    constructionCost: 500,
    buildableBy: ['private', 'state'],
    strategic: true,
    profileWeights: { industry: 0.15 },
    methods: [
      {
        id: 'steel_blast_furnace',
        name: 'Alto-forno',
        description: 'Redução do minério com coque ou carvão vegetal e aciaria a oxigênio.',
        jobs: { industrial_workers: 3200, middle_class: 450, business: 70 },
        inputs: {
          iron_ore: 0.16,
          fuel: 0.16,
          electricity: 0.07,
          chemicals: 0.02,
          machinery: 0.05,
          transport: 0.07,
          finance: 0.04,
          services: 0.03,
        },
        outputs: { steel: 0.9 },
        pollution: 0.7,
      },
      {
        id: 'steel_electric_arc',
        name: 'Forno elétrico a arco',
        description: 'Aciaria elétrica: menos carvão e mais eletricidade por tonelada.',
        jobs: { industrial_workers: 2200, middle_class: 450, tech_workers: 50, business: 70 },
        inputs: {
          iron_ore: 0.17,
          electricity: 0.17,
          fuel: 0.06,
          chemicals: 0.02,
          machinery: 0.07,
          electronics: 0.01,
          transport: 0.07,
          finance: 0.045,
          services: 0.03,
        },
        outputs: { steel: 0.93 },
        minTech: 1,
        pollution: 0.45,
      },
      {
        id: 'steel_green',
        name: 'Aço verde',
        description: 'Redução direta com hidrogênio e laminação automatizada.',
        jobs: { industrial_workers: 1300, middle_class: 450, tech_workers: 150, business: 70 },
        inputs: {
          iron_ore: 0.18,
          electricity: 0.24,
          chemicals: 0.03,
          machinery: 0.09,
          electronics: 0.025,
          software: 0.015,
          transport: 0.07,
          finance: 0.05,
          services: 0.03,
        },
        outputs: { steel: 1.01 },
        minTech: 3,
        pollution: 0.2,
      },
    ],
  },
  chemical_plant: {
    id: 'chemical_plant',
    name: 'Indústria química',
    icon: 'flask-conical',
    sector: 'heavy_industry',
    description: 'Fertilizantes, resinas plásticas e insumos para a indústria e o agro.',
    constructionCost: 480,
    buildableBy: ['private', 'state'],
    strategic: true,
    profileWeights: { industry: 0.15 },
    methods: [
      {
        id: 'chem_basic',
        name: 'Petroquímica básica',
        description: 'Craqueamento de nafta e gás em eteno, propeno e amônia.',
        jobs: { industrial_workers: 2800, middle_class: 600, tech_workers: 80, business: 70 },
        inputs: {
          oil: 0.25,
          fuel: 0.05,
          electricity: 0.08,
          machinery: 0.04,
          transport: 0.05,
          finance: 0.04,
          services: 0.03,
        },
        outputs: { chemicals: 0.84 },
        pollution: 0.55,
      },
      {
        id: 'chem_fertilizer',
        name: 'Complexo de fertilizantes e polímeros',
        description: 'Plantas integradas de nitrogenados, fosfatados e plásticos de engenharia.',
        jobs: { industrial_workers: 1900, middle_class: 600, tech_workers: 150, business: 70 },
        inputs: {
          oil: 0.28,
          fuel: 0.06,
          electricity: 0.1,
          machinery: 0.06,
          electronics: 0.01,
          transport: 0.06,
          finance: 0.045,
          services: 0.03,
        },
        outputs: { chemicals: 0.93 },
        minTech: 1,
        pollution: 0.45,
      },
      {
        id: 'chem_fine',
        name: 'Química fina e biotecnologia',
        description: 'Bioinsumos, química verde a partir de biomassa e moléculas de alto valor.',
        jobs: { industrial_workers: 1200, middle_class: 600, tech_workers: 300, business: 70 },
        inputs: {
          oil: 0.25,
          cash_crops: 0.05,
          electricity: 0.11,
          machinery: 0.07,
          electronics: 0.02,
          software: 0.02,
          transport: 0.06,
          finance: 0.05,
          services: 0.03,
        },
        outputs: { chemicals: 0.95 },
        minTech: 3,
        pollution: 0.3,
      },
    ],
  },
  cement_plant: {
    id: 'cement_plant',
    name: 'Cimento e materiais',
    icon: 'brick-wall',
    sector: 'heavy_industry',
    description: 'Cimento, cerâmica e vidro: produzidos perto das obras porque o frete é caro.',
    constructionCost: 380,
    buildableBy: ['private', 'state'],
    profileWeights: { industry: 0.1, urbanization: 0.1 },
    methods: [
      {
        id: 'cement_kiln',
        name: 'Forno de clínquer',
        description: 'Fornos rotativos convencionais e moagem de clínquer.',
        jobs: { industrial_workers: 3000, middle_class: 400, business: 70 },
        inputs: {
          fuel: 0.08,
          electricity: 0.06,
          machinery: 0.03,
          transport: 0.07,
          finance: 0.025,
          services: 0.02,
        },
        outputs: { construction_materials: 0.52 },
        pollution: 0.5,
      },
      {
        id: 'cement_automated',
        name: 'Fábrica automatizada',
        description: 'Controle automatizado dos fornos e coprocessamento de resíduos como combustível.',
        jobs: { industrial_workers: 1800, middle_class: 400, tech_workers: 50, business: 70 },
        inputs: {
          fuel: 0.07,
          electricity: 0.08,
          chemicals: 0.02,
          machinery: 0.06,
          electronics: 0.01,
          transport: 0.08,
          finance: 0.03,
          services: 0.02,
        },
        outputs: { construction_materials: 0.58 },
        minTech: 2,
        pollution: 0.35,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Indústria de transformação
  // -------------------------------------------------------------------------
  food_industry: {
    id: 'food_industry',
    name: 'Indústria de alimentos',
    icon: 'utensils',
    sector: 'manufacturing',
    description: 'Frigoríficos, laticínios, moinhos, óleos, sucos, açúcar e bebidas.',
    constructionCost: 300,
    buildableBy: ['private', 'state'],
    profileWeights: { agro: 0.6, industry: 0.6 },
    methods: [
      {
        id: 'food_traditional',
        name: 'Processamento tradicional',
        description: 'Linhas semimanuais de abate, moagem e envase.',
        jobs: { industrial_workers: 3600, workers: 600, middle_class: 450, business: 80 },
        inputs: {
          grain: 0.18,
          soy: 0.08,
          meat: 0.2,
          cash_crops: 0.08,
          chemicals: 0.02,
          electricity: 0.03,
          transport: 0.05,
          finance: 0.015,
          services: 0.025,
        },
        outputs: { processed_food: 0.98 },
      },
      {
        id: 'food_industrial',
        name: 'Linha industrial contínua',
        description: 'Processamento contínuo, câmaras frias e embalagem automática.',
        jobs: {
          industrial_workers: 2400,
          workers: 400,
          middle_class: 450,
          tech_workers: 30,
          business: 80,
        },
        inputs: {
          grain: 0.2,
          soy: 0.09,
          meat: 0.22,
          cash_crops: 0.09,
          chemicals: 0.025,
          machinery: 0.03,
          electricity: 0.04,
          transport: 0.055,
          finance: 0.02,
          services: 0.025,
        },
        outputs: { processed_food: 1.06 },
        minTech: 1,
      },
      {
        id: 'food_automated',
        name: 'Fábrica automatizada',
        description: 'Robôs de corte e embalagem, rastreabilidade e controle de qualidade digital.',
        jobs: {
          industrial_workers: 1400,
          workers: 250,
          middle_class: 450,
          tech_workers: 100,
          business: 80,
        },
        inputs: {
          grain: 0.21,
          soy: 0.095,
          meat: 0.23,
          cash_crops: 0.095,
          chemicals: 0.03,
          machinery: 0.045,
          electronics: 0.01,
          software: 0.008,
          electricity: 0.05,
          transport: 0.055,
          finance: 0.022,
          services: 0.025,
        },
        outputs: { processed_food: 1.12 },
        minTech: 2,
      },
    ],
  },
  textile_mill: {
    id: 'textile_mill',
    name: 'Têxtil e confecção',
    icon: 'shirt',
    sector: 'manufacturing',
    description: 'Fiação, tecelagem, roupas e calçados: muito emprego e concorrência importada.',
    constructionCost: 260,
    buildableBy: ['private', 'state'],
    profileWeights: { industry: 0.5, urbanization: 0.1 },
    methods: [
      {
        id: 'textile_workshop',
        name: 'Confecção tradicional',
        description: 'Oficinas de costura e teares antigos, intensivos em mão de obra.',
        jobs: { industrial_workers: 4200, workers: 800, middle_class: 300, business: 80 },
        inputs: {
          cash_crops: 0.07,
          chemicals: 0.06,
          electricity: 0.025,
          transport: 0.03,
          finance: 0.01,
          services: 0.02,
        },
        outputs: { textiles: 0.5 },
      },
      {
        id: 'textile_industrial',
        name: 'Tecelagem industrial',
        description: 'Teares automáticos e corte em escala.',
        jobs: {
          industrial_workers: 2700,
          workers: 500,
          middle_class: 300,
          tech_workers: 20,
          business: 80,
        },
        inputs: {
          cash_crops: 0.08,
          chemicals: 0.075,
          machinery: 0.03,
          electricity: 0.035,
          transport: 0.035,
          finance: 0.012,
          services: 0.02,
        },
        outputs: { textiles: 0.52 },
        minTech: 1,
      },
      {
        id: 'textile_automated',
        name: 'Fábrica têxtil automatizada',
        description: 'Corte a laser, costura robotizada e produção sob demanda.',
        jobs: {
          industrial_workers: 1500,
          workers: 300,
          middle_class: 300,
          tech_workers: 80,
          business: 80,
        },
        inputs: {
          cash_crops: 0.085,
          chemicals: 0.08,
          machinery: 0.05,
          electronics: 0.01,
          software: 0.005,
          electricity: 0.045,
          transport: 0.035,
          finance: 0.014,
          services: 0.02,
        },
        outputs: { textiles: 0.545 },
        minTech: 2,
      },
    ],
  },
  consumer_factory: {
    id: 'consumer_factory',
    name: 'Bens de consumo',
    icon: 'sofa',
    sector: 'manufacturing',
    description: 'Móveis, eletrodomésticos, papel, plásticos, higiene e limpeza.',
    constructionCost: 300,
    buildableBy: ['private', 'state'],
    profileWeights: { industry: 0.8, urbanization: 0.2 },
    methods: [
      {
        id: 'consumer_traditional',
        name: 'Manufatura tradicional',
        description: 'Fábricas médias com montagem manual e pouca automação.',
        jobs: { industrial_workers: 3800, workers: 500, middle_class: 450, business: 80 },
        inputs: {
          wood: 0.06,
          steel: 0.06,
          chemicals: 0.08,
          textiles: 0.02,
          electricity: 0.03,
          transport: 0.04,
          finance: 0.015,
          services: 0.025,
        },
        outputs: { consumer_goods: 0.61 },
      },
      {
        id: 'consumer_line',
        name: 'Produção seriada',
        description: 'Linhas de produção em série com componentes eletrônicos embarcados.',
        jobs: {
          industrial_workers: 2500,
          workers: 350,
          middle_class: 450,
          tech_workers: 30,
          business: 80,
        },
        inputs: {
          wood: 0.065,
          steel: 0.07,
          chemicals: 0.09,
          textiles: 0.02,
          machinery: 0.035,
          electronics: 0.02,
          electricity: 0.04,
          transport: 0.045,
          finance: 0.018,
          services: 0.025,
        },
        outputs: { consumer_goods: 0.67 },
        minTech: 1,
      },
      {
        id: 'consumer_smart',
        name: 'Fábrica inteligente',
        description: 'Automação conectada, produção flexível e produtos com eletrônica embarcada.',
        jobs: {
          industrial_workers: 1400,
          workers: 200,
          middle_class: 450,
          tech_workers: 120,
          business: 80,
        },
        inputs: {
          wood: 0.07,
          steel: 0.075,
          chemicals: 0.095,
          textiles: 0.02,
          machinery: 0.05,
          electronics: 0.04,
          software: 0.015,
          electricity: 0.05,
          transport: 0.045,
          finance: 0.02,
          services: 0.025,
        },
        outputs: { consumer_goods: 0.725 },
        minTech: 3,
      },
    ],
  },
  machinery_factory: {
    id: 'machinery_factory',
    name: 'Máquinas e equipamentos',
    icon: 'cog',
    sector: 'manufacturing',
    description: 'Bens de capital: tratores, máquinas industriais, bombas e turbinas.',
    constructionCost: 450,
    buildableBy: ['private', 'state'],
    strategic: true,
    profileWeights: { industry: 0.4, tech: 0.15 },
    methods: [
      {
        id: 'machinery_conventional',
        name: 'Usinagem convencional',
        description: 'Tornos e fresadoras operados manualmente por mão de obra qualificada.',
        jobs: { industrial_workers: 3300, middle_class: 700, tech_workers: 60, business: 80 },
        inputs: {
          steel: 0.22,
          electronics: 0.03,
          chemicals: 0.02,
          electricity: 0.03,
          transport: 0.04,
          finance: 0.02,
          services: 0.03,
        },
        outputs: { machinery: 0.68 },
      },
      {
        id: 'machinery_cnc',
        name: 'Usinagem CNC',
        description: 'Máquinas de comando numérico e projeto assistido por computador.',
        jobs: { industrial_workers: 2200, middle_class: 700, tech_workers: 150, business: 80 },
        inputs: {
          steel: 0.24,
          electronics: 0.07,
          software: 0.02,
          chemicals: 0.02,
          electricity: 0.04,
          transport: 0.045,
          finance: 0.025,
          services: 0.03,
        },
        outputs: { machinery: 0.76 },
        minTech: 1,
      },
      {
        id: 'machinery_robotic',
        name: 'Manufatura robotizada',
        description: 'Células robotizadas e manufatura aditiva para peças complexas.',
        jobs: { industrial_workers: 1300, middle_class: 700, tech_workers: 300, business: 80 },
        inputs: {
          steel: 0.25,
          electronics: 0.11,
          software: 0.04,
          chemicals: 0.02,
          electricity: 0.05,
          transport: 0.045,
          finance: 0.028,
          services: 0.03,
        },
        outputs: { machinery: 0.84 },
        minTech: 3,
      },
    ],
  },
  auto_plant: {
    id: 'auto_plant',
    name: 'Montadora',
    icon: 'car',
    sector: 'manufacturing',
    description: 'Automóveis, motos, ônibus, caminhões e autopeças.',
    constructionCost: 420,
    buildableBy: ['private', 'state'],
    profileWeights: { industry: 0.3, income: 0.1 },
    methods: [
      {
        id: 'auto_manual',
        name: 'Montagem manual',
        description: 'Montagem em estações com muita mão de obra e pouca automação.',
        jobs: { industrial_workers: 3500, middle_class: 600, business: 80 },
        inputs: {
          steel: 0.25,
          electronics: 0.08,
          chemicals: 0.06,
          textiles: 0.02,
          electricity: 0.03,
          transport: 0.05,
          finance: 0.025,
          services: 0.03,
        },
        outputs: { vehicles: 0.86 },
      },
      {
        id: 'auto_assembly_line',
        name: 'Linha de montagem',
        description: 'Esteira contínua, solda automatizada e fornecedores just-in-time.',
        jobs: { industrial_workers: 2400, middle_class: 600, tech_workers: 60, business: 80 },
        inputs: {
          steel: 0.27,
          electronics: 0.1,
          chemicals: 0.065,
          textiles: 0.02,
          machinery: 0.04,
          electricity: 0.04,
          transport: 0.055,
          finance: 0.028,
          services: 0.03,
        },
        outputs: { vehicles: 0.945 },
        minTech: 1,
      },
      {
        id: 'auto_robotic',
        name: 'Montagem robotizada',
        description: 'Robôs de solda e pintura, veículos conectados e elétricos.',
        jobs: { industrial_workers: 1300, middle_class: 600, tech_workers: 200, business: 80 },
        inputs: {
          steel: 0.28,
          electronics: 0.14,
          software: 0.03,
          chemicals: 0.07,
          textiles: 0.02,
          machinery: 0.06,
          electricity: 0.05,
          transport: 0.055,
          finance: 0.03,
          services: 0.03,
        },
        outputs: { vehicles: 1.05 },
        minTech: 2,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Alta tecnologia
  // -------------------------------------------------------------------------
  electronics_factory: {
    id: 'electronics_factory',
    name: 'Indústria eletrônica',
    icon: 'cpu',
    sector: 'high_tech',
    description: 'Celulares, computadores, televisores e componentes eletrônicos.',
    constructionCost: 550,
    buildableBy: ['private', 'state'],
    strategic: true,
    profileWeights: { industry: 0.1, tech: 0.15 },
    methods: [
      {
        id: 'electronics_assembly',
        name: 'Montagem de kits',
        description: 'Montagem final de aparelhos a partir de placas e componentes prontos.',
        jobs: { industrial_workers: 3000, middle_class: 500, tech_workers: 200, business: 80 },
        inputs: {
          chemicals: 0.08,
          steel: 0.03,
          software: 0.02,
          electricity: 0.03,
          transport: 0.05,
          finance: 0.02,
          services: 0.03,
        },
        outputs: { electronics: 0.52 },
      },
      {
        id: 'electronics_smt',
        name: 'Montagem automatizada de placas',
        description: 'Linhas SMT montam as placas no país, com mais valor agregado local.',
        jobs: { industrial_workers: 1800, middle_class: 500, tech_workers: 400, business: 80 },
        inputs: {
          chemicals: 0.09,
          steel: 0.03,
          machinery: 0.04,
          software: 0.035,
          electricity: 0.04,
          transport: 0.05,
          finance: 0.025,
          services: 0.03,
        },
        outputs: { electronics: 0.585 },
        minTech: 2,
      },
      {
        id: 'electronics_semiconductor',
        name: 'Fábrica de semicondutores',
        description: 'Encapsulamento e fabricação de chips: intensiva em engenharia e energia.',
        jobs: { industrial_workers: 1200, middle_class: 600, tech_workers: 900, business: 80 },
        inputs: {
          chemicals: 0.12,
          machinery: 0.08,
          software: 0.05,
          electricity: 0.08,
          transport: 0.04,
          finance: 0.04,
          services: 0.03,
        },
        outputs: { electronics: 0.73 },
        minTech: 3,
      },
    ],
  },
  pharma_plant: {
    id: 'pharma_plant',
    name: 'Indústria farmacêutica',
    icon: 'pill',
    sector: 'high_tech',
    description: 'Medicamentos, vacinas e insumos hospitalares.',
    constructionCost: 500,
    buildableBy: ['private', 'state'],
    profileWeights: { tech: 0.08, income: 0.03 },
    methods: [
      {
        id: 'pharma_generics',
        name: 'Genéricos',
        description: 'Formulação de medicamentos a partir de princípios ativos em grande parte importados.',
        jobs: {
          industrial_workers: 2600,
          middle_class: 700,
          tech_workers: 250,
          health_workers: 100,
          business: 80,
        },
        inputs: {
          chemicals: 0.2,
          electricity: 0.03,
          transport: 0.03,
          finance: 0.02,
          services: 0.04,
        },
        outputs: { pharmaceuticals: 0.61 },
      },
      {
        id: 'pharma_biotech',
        name: 'Biotecnologia e vacinas',
        description: 'Produção de princípios ativos, biológicos e vacinas no país.',
        jobs: {
          industrial_workers: 1600,
          middle_class: 700,
          tech_workers: 600,
          health_workers: 150,
          business: 80,
        },
        inputs: {
          chemicals: 0.23,
          machinery: 0.04,
          electronics: 0.02,
          software: 0.03,
          electricity: 0.04,
          transport: 0.03,
          finance: 0.025,
          services: 0.04,
        },
        outputs: { pharmaceuticals: 0.77 },
        minTech: 2,
      },
    ],
  },
  aerospace: {
    id: 'aerospace',
    name: 'Indústria aeroespacial',
    icon: 'plane',
    sector: 'high_tech',
    description: 'Jatos regionais, aviões agrícolas e de defesa, satélites e peças.',
    constructionCost: 750,
    buildableBy: ['private', 'state'],
    strategic: true,
    profileWeights: { tech: 0.02 },
    methods: [
      {
        id: 'aerospace_assembly',
        name: 'Montagem aeronáutica',
        description: 'Projeto nacional com montagem de estruturas e sistemas em grande parte importados.',
        jobs: { industrial_workers: 2500, middle_class: 800, tech_workers: 700, business: 80 },
        inputs: {
          steel: 0.08,
          electronics: 0.2,
          chemicals: 0.06,
          machinery: 0.04,
          software: 0.03,
          electricity: 0.03,
          transport: 0.03,
          finance: 0.04,
          services: 0.04,
        },
        outputs: { aircraft: 0.95 },
      },
      {
        id: 'aerospace_composite',
        name: 'Compósitos e projeto digital',
        description: 'Estruturas em compósitos, gêmeos digitais e integração de sistemas próprios.',
        jobs: { industrial_workers: 1600, middle_class: 800, tech_workers: 1000, business: 80 },
        inputs: {
          steel: 0.06,
          electronics: 0.25,
          chemicals: 0.1,
          machinery: 0.06,
          software: 0.06,
          electricity: 0.04,
          transport: 0.03,
          finance: 0.045,
          services: 0.04,
        },
        outputs: { aircraft: 1.1 },
        minTech: 2,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Serviços
  // -------------------------------------------------------------------------
  construction_sector: {
    id: 'construction_sector',
    name: 'Construção civil',
    icon: 'hard-hat',
    sector: 'services',
    description: 'Construtoras e empreiteiras: geram os pontos de construção de todas as obras.',
    constructionCost: 200,
    buildableBy: ['private', 'state'],
    profileWeights: { urbanization: 0.6, income: 0.4, industry: 0.2 },
    methods: [
      {
        id: 'construction_traditional',
        name: 'Construção convencional',
        description: 'Canteiros com muita mão de obra, concreto moldado no local e alvenaria.',
        jobs: { workers: 4000, middle_class: 350, business: 100 },
        inputs: {
          construction_materials: 0.17,
          steel: 0.11,
          machinery: 0.055,
          transport: 0.035,
          wood: 0.02,
          fuel: 0.01,
        },
        outputs: {},
        constructionPoints: 10,
      },
      {
        id: 'construction_industrialized',
        name: 'Construção industrializada',
        description: 'Pré-moldados e estruturas metálicas montados no canteiro.',
        jobs: { workers: 2700, industrial_workers: 300, middle_class: 400, business: 100 },
        inputs: {
          construction_materials: 0.2,
          steel: 0.13,
          machinery: 0.08,
          transport: 0.04,
          wood: 0.015,
          fuel: 0.012,
        },
        outputs: {},
        constructionPoints: 13,
        minTech: 1,
      },
      {
        id: 'construction_modular',
        name: 'Construção modular e digital',
        description: 'Módulos fabricados em série, projeto em BIM e canteiro enxuto.',
        jobs: {
          workers: 1700,
          industrial_workers: 300,
          middle_class: 450,
          tech_workers: 60,
          business: 100,
        },
        inputs: {
          construction_materials: 0.22,
          steel: 0.15,
          machinery: 0.1,
          electronics: 0.01,
          software: 0.01,
          transport: 0.045,
          wood: 0.012,
          fuel: 0.012,
        },
        outputs: {},
        constructionPoints: 16,
        minTech: 2,
      },
    ],
  },
  logistics: {
    id: 'logistics',
    name: 'Transporte e logística',
    icon: 'truck',
    sector: 'services',
    description: 'Transportadoras, ferrovias, portos e armazéns que levam a produção ao mercado.',
    constructionCost: 220,
    buildableBy: ['private', 'state'],
    profileWeights: { urbanization: 0.4, industry: 0.4, agro: 0.4 },
    methods: [
      {
        id: 'logistics_road',
        name: 'Frete rodoviário',
        description: 'Caminhões e transportadoras sobre a malha rodoviária.',
        jobs: { workers: 3800, middle_class: 400, business: 100 },
        inputs: {
          fuel: 0.14,
          vehicles: 0.06,
          machinery: 0.01,
          electricity: 0.01,
          services: 0.02,
          finance: 0.02,
        },
        outputs: { transport: 0.5 },
      },
      {
        id: 'logistics_multimodal',
        name: 'Logística multimodal',
        description: 'Ferrovias, cabotagem e terminais integrados ao transporte rodoviário.',
        jobs: { workers: 2500, industrial_workers: 300, middle_class: 450, business: 100 },
        inputs: {
          fuel: 0.12,
          vehicles: 0.05,
          machinery: 0.04,
          steel: 0.02,
          electricity: 0.025,
          software: 0.01,
          services: 0.02,
          finance: 0.03,
        },
        outputs: { transport: 0.54 },
        minTech: 1,
      },
      {
        id: 'logistics_automated',
        name: 'Centros logísticos automatizados',
        description: 'Armazéns robotizados, roteirização por software e frota monitorada.',
        jobs: {
          workers: 1600,
          industrial_workers: 300,
          middle_class: 450,
          tech_workers: 80,
          business: 100,
        },
        inputs: {
          fuel: 0.12,
          vehicles: 0.06,
          machinery: 0.05,
          electronics: 0.02,
          software: 0.02,
          electricity: 0.03,
          services: 0.02,
          finance: 0.03,
        },
        outputs: { transport: 0.565 },
        minTech: 2,
      },
    ],
  },
  commerce: {
    id: 'commerce',
    name: 'Comércio e serviços',
    icon: 'store',
    sector: 'services',
    description: 'Lojas, mercados, restaurantes, turismo e serviços pessoais e profissionais.',
    constructionCost: 160,
    buildableBy: ['private', 'state'],
    profileWeights: { urbanization: 1, income: 0.4 },
    methods: [
      {
        id: 'commerce_traditional',
        name: 'Comércio tradicional',
        description: 'Pequenos e médios negócios de rua, com dono no balcão.',
        jobs: { merchants: 1900, workers: 2500, middle_class: 500, business: 120 },
        inputs: {
          processed_food: 0.02,
          consumer_goods: 0.01,
          electricity: 0.02,
          transport: 0.025,
          finance: 0.015,
        },
        outputs: { services: 0.38 },
      },
      {
        id: 'commerce_retail_chains',
        name: 'Grandes redes varejistas',
        description: 'Supermercados, shoppings e franquias com logística centralizada.',
        jobs: {
          merchants: 1000,
          workers: 2300,
          middle_class: 600,
          tech_workers: 30,
          business: 120,
        },
        inputs: {
          processed_food: 0.02,
          consumer_goods: 0.012,
          electronics: 0.008,
          software: 0.01,
          electricity: 0.03,
          transport: 0.035,
          finance: 0.02,
        },
        outputs: { services: 0.385 },
        minTech: 1,
      },
      {
        id: 'commerce_digital',
        name: 'Comércio digital e plataformas',
        description: 'Comércio eletrônico, aplicativos de entrega e pagamentos digitais.',
        jobs: {
          merchants: 600,
          workers: 1600,
          middle_class: 600,
          tech_workers: 200,
          business: 120,
        },
        inputs: {
          processed_food: 0.015,
          consumer_goods: 0.01,
          electronics: 0.012,
          software: 0.03,
          electricity: 0.03,
          transport: 0.05,
          finance: 0.025,
        },
        outputs: { services: 0.405 },
        minTech: 2,
      },
    ],
  },
  bank: {
    id: 'bank',
    name: 'Bancos e seguros',
    icon: 'landmark',
    sector: 'services',
    description: 'Crédito, seguros, investimentos e meios de pagamento.',
    constructionCost: 260,
    buildableBy: ['private', 'state'],
    profileWeights: { income: 1, urbanization: 0.6 },
    methods: [
      {
        id: 'bank_branches',
        name: 'Rede de agências',
        description: 'Agências físicas, gerentes de conta e compensação tradicional.',
        jobs: { middle_class: 3000, workers: 800, tech_workers: 100, business: 300 },
        inputs: {
          software: 0.04,
          electronics: 0.01,
          electricity: 0.015,
          services: 0.04,
          transport: 0.005,
        },
        outputs: { finance: 0.6 },
      },
      {
        id: 'bank_digital',
        name: 'Banco digital',
        description: 'Atendimento por aplicativo, crédito automatizado e poucas agências.',
        jobs: { middle_class: 1800, workers: 300, tech_workers: 500, business: 300 },
        inputs: {
          software: 0.08,
          electronics: 0.02,
          electricity: 0.02,
          services: 0.035,
          transport: 0.003,
        },
        outputs: { finance: 0.59 },
        minTech: 2,
      },
    ],
  },
  tech_hub: {
    id: 'tech_hub',
    name: 'Polo de tecnologia',
    icon: 'laptop',
    sector: 'services',
    description: 'Empresas de software, nuvem e serviços digitais; exporta e substitui importações.',
    constructionCost: 280,
    buildableBy: ['private', 'state'],
    profileWeights: { tech: 1.2, income: 0.4 },
    methods: [
      {
        id: 'tech_it_services',
        name: 'Serviços de TI',
        description: 'Desenvolvimento sob encomenda, suporte e integração de sistemas.',
        jobs: { tech_workers: 2400, middle_class: 900, business: 120 },
        inputs: { electronics: 0.04, electricity: 0.02, services: 0.04, finance: 0.01 },
        outputs: { software: 0.56 },
      },
      {
        id: 'tech_platforms',
        name: 'Plataformas e nuvem',
        description: 'Produtos próprios vendidos como serviço, com infraestrutura em nuvem.',
        jobs: { tech_workers: 1900, middle_class: 700, business: 120 },
        inputs: { electronics: 0.07, electricity: 0.04, services: 0.04, finance: 0.015 },
        outputs: { software: 0.55 },
        minTech: 2,
      },
      {
        id: 'tech_ai',
        name: 'Inteligência artificial e P&D',
        description: 'Modelos de IA, pesquisa aplicada e centros de dados de alto desempenho.',
        jobs: { tech_workers: 1600, middle_class: 500, business: 120 },
        inputs: { electronics: 0.1, electricity: 0.06, services: 0.035, finance: 0.02 },
        outputs: { software: 0.56 },
        minTech: 3,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Setor público (salários e insumos pagos pelo orçamento)
  // -------------------------------------------------------------------------
  public_admin: {
    id: 'public_admin',
    name: 'Administração pública',
    icon: 'building-2',
    sector: 'public',
    description: 'Ministérios, secretarias, tribunais, polícias e repartições.',
    constructionCost: 250,
    buildableBy: ['state'],
    budgetCategory: 'administration',
    profileWeights: { publicSector: 1.2 },
    methods: [
      {
        id: 'admin_bureaucratic',
        name: 'Burocracia tradicional',
        description: 'Atendimento presencial, processos em papel e muitas etapas.',
        jobs: { civil_servants: 3600, middle_class: 500, workers: 900 },
        inputs: {
          services: 0.05,
          software: 0.015,
          electricity: 0.015,
          consumer_goods: 0.01,
          transport: 0.01,
        },
        outputs: {},
      },
      {
        id: 'admin_digital',
        name: 'Governo digital',
        description: 'Serviços pela internet e processos eletrônicos: menos pessoal por atendimento.',
        jobs: { civil_servants: 2600, middle_class: 600, tech_workers: 150, workers: 500 },
        inputs: {
          services: 0.045,
          software: 0.045,
          electronics: 0.015,
          electricity: 0.02,
          consumer_goods: 0.008,
          transport: 0.008,
        },
        outputs: {},
        minTech: 1,
      },
    ],
  },
  hospital: {
    id: 'hospital',
    name: 'Hospitais e saúde',
    icon: 'hospital',
    sector: 'public',
    description: 'Hospitais, postos de saúde e laboratórios da rede pública.',
    constructionCost: 280,
    buildableBy: ['state'],
    budgetCategory: 'health',
    profileWeights: { urbanization: 0.6, income: 0.3, publicSector: 0.3 },
    methods: [
      {
        id: 'hospital_basic',
        name: 'Rede básica',
        description: 'Postos de saúde e hospitais gerais com equipamentos básicos.',
        jobs: { health_workers: 3000, civil_servants: 500, middle_class: 300, workers: 1000 },
        inputs: {
          pharmaceuticals: 0.08,
          consumer_goods: 0.01,
          processed_food: 0.01,
          electricity: 0.015,
          services: 0.03,
          transport: 0.005,
        },
        outputs: {},
      },
      {
        id: 'hospital_modern',
        name: 'Alta complexidade',
        description: 'Diagnóstico por imagem, telemedicina e prontuário eletrônico.',
        jobs: {
          health_workers: 2600,
          civil_servants: 400,
          middle_class: 400,
          tech_workers: 80,
          workers: 700,
        },
        inputs: {
          pharmaceuticals: 0.11,
          electronics: 0.03,
          machinery: 0.02,
          software: 0.01,
          consumer_goods: 0.01,
          processed_food: 0.01,
          electricity: 0.02,
          services: 0.03,
          transport: 0.005,
        },
        outputs: {},
        minTech: 2,
      },
    ],
  },
  school: {
    id: 'school',
    name: 'Escolas e universidades',
    icon: 'school',
    sector: 'public',
    description: 'Educação básica, técnica e superior pública.',
    constructionCost: 220,
    buildableBy: ['state'],
    budgetCategory: 'education',
    profileWeights: { urbanization: 0.5, publicSector: 0.5 },
    methods: [
      {
        id: 'school_traditional',
        name: 'Ensino tradicional',
        description: 'Aulas expositivas em turno parcial, com material impresso e merenda.',
        jobs: { civil_servants: 2600, middle_class: 1200, workers: 1000 },
        inputs: {
          consumer_goods: 0.02,
          processed_food: 0.02,
          electronics: 0.005,
          electricity: 0.012,
          services: 0.02,
          transport: 0.008,
        },
        outputs: {},
      },
      {
        id: 'school_digital',
        name: 'Ensino com tecnologia',
        description: 'Plataformas digitais, laboratórios e ensino híbrido com turmas maiores.',
        jobs: { civil_servants: 2200, middle_class: 1100, tech_workers: 80, workers: 800 },
        inputs: {
          consumer_goods: 0.02,
          processed_food: 0.02,
          electronics: 0.025,
          software: 0.015,
          electricity: 0.015,
          services: 0.02,
          transport: 0.008,
        },
        outputs: {},
        minTech: 1,
      },
    ],
  },

  // -------------------------------------------------------------------------
  // Economia informal (ninguém constrói: absorve quem não tem emprego formal)
  // -------------------------------------------------------------------------
  informal: {
    id: 'informal',
    name: 'Economia informal',
    icon: 'hand-coins',
    sector: 'informal',
    description: 'Bicos, ambulantes e pequenos serviços sem carteira assinada nem CNPJ.',
    constructionCost: 50,
    buildableBy: [],
    profileWeights: { urbanization: 0.4 },
    methods: [
      {
        id: 'informal_odd_jobs',
        name: 'Bicos e comércio ambulante',
        description: 'Trabalho por conta própria, sem insumos industriais e com baixa produtividade.',
        jobs: { workers: 8000 },
        inputs: {},
        outputs: { services: 0.12, processed_food: 0.015, grain: 0.01 },
      },
      {
        id: 'informal_platforms',
        name: 'Trabalho por aplicativo',
        description: 'Entregas, corridas e serviços contratados por plataformas digitais.',
        jobs: { workers: 8000 },
        inputs: { fuel: 0.012, electronics: 0.004, software: 0.004 },
        outputs: { services: 0.12, transport: 0.04, processed_food: 0.01 },
        minTech: 2,
      },
    ],
  },
};

export const BUILDING_LIST: BuildingDefinition[] = BUILDING_IDS.map((id) => BUILDINGS[id]);

export function getBuilding(id: BuildingId): BuildingDefinition {
  return BUILDINGS[id];
}

/** Método de produção pelo id (cai no padrão se não existir). */
export function getMethod(buildingId: BuildingId, methodId: string): ProductionMethod {
  const def = BUILDINGS[buildingId];
  return def.methods.find((m) => m.id === methodId) ?? (def.methods[0] as ProductionMethod);
}
