import type { GoodDefinition, GoodId } from './types';

/**
 * Bens do mercado nacional. Preços mundiais e volatilidades são PARÂMETROS DO MODELO,
 * escolhidos para que o Brasil do jogo comece exportando commodities e importando
 * manufaturados de alta tecnologia — o dilema de desenvolvimento que o jogador enfrenta.
 */
export const GOODS: Record<GoodId, GoodDefinition> = {
  grain: {
    id: 'grain',
    name: 'Grãos e cereais',
    icon: 'wheat',
    color: '#e9c46a',
    category: 'agro',
    description: 'Arroz, feijão, milho e trigo: base da alimentação e da ração animal.',
    displayPrice: 1500,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1,
    worldVolatility: 0.035,
    transportCost: 0.08,
  },
  soy: {
    id: 'soy',
    name: 'Soja',
    icon: 'sprout',
    color: '#a7c957',
    category: 'agro',
    description: 'Principal commodity agrícola de exportação; vira ração, óleo e farelo.',
    displayPrice: 2300,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1.04,
    worldVolatility: 0.05,
    transportCost: 0.08,
  },
  meat: {
    id: 'meat',
    name: 'Carnes',
    icon: 'beef',
    color: '#c1121f',
    category: 'agro',
    description: 'Bovinos, suínos e aves. Consumo interno forte e grande exportação.',
    displayPrice: 18000,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1.02,
    worldVolatility: 0.035,
    transportCost: 0.1,
  },
  cash_crops: {
    id: 'cash_crops',
    name: 'Café, cana e frutas',
    icon: 'coffee',
    color: '#7f5539',
    category: 'agro',
    description: 'Café, açúcar, laranja, algodão e frutas: culturas de exportação e insumo industrial.',
    displayPrice: 9000,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1.04,
    worldVolatility: 0.05,
    transportCost: 0.08,
  },
  wood: {
    id: 'wood',
    name: 'Madeira e celulose',
    icon: 'trees',
    color: '#606c38',
    category: 'agro',
    description: 'Florestas plantadas: celulose, papel, móveis e construção.',
    displayPrice: 2800,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1.02,
    worldVolatility: 0.035,
    transportCost: 0.1,
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Minério de ferro',
    icon: 'pickaxe',
    color: '#9c6644',
    category: 'mineral',
    description: 'Matéria-prima do aço. Exportado em massa, sobretudo para a Ásia.',
    displayPrice: 550,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1.05,
    worldVolatility: 0.065,
    transportCost: 0.14,
  },
  oil: {
    id: 'oil',
    name: 'Petróleo',
    icon: 'droplet',
    color: '#1f1f1f',
    category: 'energy',
    description: 'Petróleo bruto do pré-sal e de terra. Insumo das refinarias e da petroquímica.',
    displayPrice: 420,
    displayUnit: 'barril',
    tradeable: true,
    worldPrice: 1.02,
    worldVolatility: 0.075,
    transportCost: 0.06,
  },
  fuel: {
    id: 'fuel',
    name: 'Combustíveis',
    icon: 'fuel',
    color: '#ff9f1c',
    category: 'energy',
    description: 'Gasolina, diesel, querosene e etanol. Movem caminhões, máquinas e carros.',
    displayPrice: 6000,
    displayUnit: 'm³',
    tradeable: true,
    worldPrice: 1,
    worldVolatility: 0.05,
    transportCost: 0.07,
  },
  electricity: {
    id: 'electricity',
    name: 'Energia elétrica',
    icon: 'zap',
    color: '#ffd60a',
    category: 'energy',
    description: 'Não pode ser importada em escala: falta de geração vira apagão e preço alto.',
    displayPrice: 600,
    displayUnit: 'MWh',
    tradeable: false,
    worldPrice: 1,
    worldVolatility: 0,
    transportCost: 0,
  },
  steel: {
    id: 'steel',
    name: 'Aço',
    icon: 'anvil',
    color: '#8d99ae',
    category: 'industrial',
    description: 'Base da indústria pesada: máquinas, veículos, construção e estaleiros.',
    displayPrice: 5200,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 0.98,
    worldVolatility: 0.04,
    transportCost: 0.08,
  },
  chemicals: {
    id: 'chemicals',
    name: 'Químicos e fertilizantes',
    icon: 'flask-conical',
    color: '#4cc9f0',
    category: 'industrial',
    description: 'Fertilizantes, plásticos e insumos. O agro importa boa parte deles.',
    displayPrice: 4000,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 0.93,
    worldVolatility: 0.045,
    transportCost: 0.08,
  },
  construction_materials: {
    id: 'construction_materials',
    name: 'Cimento e materiais',
    icon: 'brick-wall',
    color: '#b5838d',
    category: 'industrial',
    description: 'Cimento, cerâmica e vidro. Pesados e caros de transportar: produção local.',
    displayPrice: 600,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1,
    worldVolatility: 0.025,
    transportCost: 0.28,
  },
  textiles: {
    id: 'textiles',
    name: 'Têxteis e vestuário',
    icon: 'shirt',
    color: '#e5989b',
    category: 'consumer',
    description: 'Roupas, calçados e tecidos. Forte concorrência de importados baratos.',
    displayPrice: 60,
    displayUnit: 'peça',
    tradeable: true,
    worldPrice: 0.84,
    worldVolatility: 0.03,
    transportCost: 0.08,
  },
  processed_food: {
    id: 'processed_food',
    name: 'Alimentos industrializados',
    icon: 'cookie',
    color: '#f4a261',
    category: 'consumer',
    description: 'Laticínios, embutidos, massas, bebidas e óleo: a mesa do brasileiro.',
    displayPrice: 9000,
    displayUnit: 't',
    tradeable: true,
    worldPrice: 1,
    worldVolatility: 0.03,
    transportCost: 0.08,
  },
  consumer_goods: {
    id: 'consumer_goods',
    name: 'Bens de consumo',
    icon: 'sofa',
    color: '#cdb4db',
    category: 'consumer',
    description: 'Móveis, eletrodomésticos, utensílios e produtos de higiene.',
    displayPrice: 900,
    displayUnit: 'un.',
    tradeable: true,
    worldPrice: 0.9,
    worldVolatility: 0.03,
    transportCost: 0.08,
  },
  electronics: {
    id: 'electronics',
    name: 'Eletrônicos',
    icon: 'cpu',
    color: '#4361ee',
    category: 'high_tech',
    description: 'Celulares, computadores, chips e componentes. Grande item da pauta de importação.',
    displayPrice: 2000,
    displayUnit: 'un.',
    tradeable: true,
    worldPrice: 0.86,
    worldVolatility: 0.03,
    transportCost: 0.04,
  },
  machinery: {
    id: 'machinery',
    name: 'Máquinas e equipamentos',
    icon: 'cog',
    color: '#6c757d',
    category: 'industrial',
    description: 'Bens de capital: tratores, máquinas industriais, turbinas. Sem eles não há indústria.',
    displayPrice: 150000,
    displayUnit: 'un.',
    tradeable: true,
    worldPrice: 0.95,
    worldVolatility: 0.03,
    transportCost: 0.06,
  },
  vehicles: {
    id: 'vehicles',
    name: 'Veículos',
    icon: 'car',
    color: '#e63946',
    category: 'consumer',
    description: 'Carros, motos, ônibus e caminhões.',
    displayPrice: 95000,
    displayUnit: 'un.',
    tradeable: true,
    worldPrice: 0.97,
    worldVolatility: 0.03,
    transportCost: 0.07,
  },
  pharmaceuticals: {
    id: 'pharmaceuticals',
    name: 'Medicamentos',
    icon: 'pill',
    color: '#80ed99',
    category: 'high_tech',
    description: 'Remédios, vacinas e insumos hospitalares.',
    displayPrice: 40,
    displayUnit: 'cx.',
    tradeable: true,
    worldPrice: 0.95,
    worldVolatility: 0.02,
    transportCost: 0.04,
  },
  aircraft: {
    id: 'aircraft',
    name: 'Aeronaves',
    icon: 'plane',
    color: '#adb5bd',
    category: 'high_tech',
    description: 'Jatos regionais, aviões agrícolas e de defesa: exportação de alto valor.',
    displayPrice: 180_000_000,
    displayUnit: 'un.',
    tradeable: true,
    worldPrice: 1.05,
    worldVolatility: 0.02,
    transportCost: 0.02,
  },
  transport: {
    id: 'transport',
    name: 'Transporte e logística',
    icon: 'truck',
    color: '#bc6c25',
    category: 'service',
    description: 'Frete rodoviário, ferrovias, portos e armazéns. Gargalo clássico do país.',
    displayPrice: 1,
    displayUnit: 't·km',
    tradeable: false,
    worldPrice: 1,
    worldVolatility: 0,
    transportCost: 0,
  },
  services: {
    id: 'services',
    name: 'Comércio e serviços',
    icon: 'store',
    color: '#2a9d8f',
    category: 'service',
    description: 'Varejo, alimentação fora de casa, turismo, serviços pessoais e profissionais.',
    displayPrice: 100,
    displayUnit: 'serviço',
    tradeable: false,
    worldPrice: 1,
    worldVolatility: 0,
    transportCost: 0,
  },
  finance: {
    id: 'finance',
    name: 'Serviços financeiros',
    icon: 'banknote',
    color: '#06d6a0',
    category: 'service',
    description: 'Crédito, seguros e meios de pagamento.',
    displayPrice: 100,
    displayUnit: 'serviço',
    tradeable: false,
    worldPrice: 1,
    worldVolatility: 0,
    transportCost: 0,
  },
  software: {
    id: 'software',
    name: 'Software e serviços digitais',
    icon: 'laptop',
    color: '#7209b7',
    category: 'high_tech',
    description: 'Sistemas, aplicativos, nuvem e serviços de TI. Exportável.',
    displayPrice: 100,
    displayUnit: 'licença',
    tradeable: true,
    worldPrice: 0.95,
    worldVolatility: 0.02,
    transportCost: 0.02,
  },
};

export const GOOD_LIST: GoodDefinition[] = Object.values(GOODS);

export function getGood(id: GoodId): GoodDefinition {
  return GOODS[id];
}
