server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 25m;

  location /api/ {
    proxy_pass http://server:3333;
    proxy_set_header Host $host;
  }

  # SPA: todas as rotas caem no index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
