import type { Rng } from '../core/rng';

export const FIRST_NAMES_M = [
  'João',
  'Pedro',
  'Lucas',
  'Gabriel',
  'Rafael',
  'Carlos',
  'Marcos',
  'Paulo',
  'Ricardo',
  'Fernando',
  'André',
  'Eduardo',
  'Gustavo',
  'Thiago',
  'Roberto',
  'Antônio',
  'Francisco',
  'José',
  'Sérgio',
  'Márcio',
  'Diego',
  'Felipe',
  'Renato',
  'Leandro',
  'Wagner',
  'Ademir',
  'Cícero',
  'Raimundo',
  'Valdir',
  'Heitor',
];
export const FIRST_NAMES_F = [
  'Maria',
  'Ana',
  'Juliana',
  'Fernanda',
  'Patrícia',
  'Camila',
  'Beatriz',
  'Larissa',
  'Cláudia',
  'Simone',
  'Renata',
  'Luciana',
  'Adriana',
  'Tatiana',
  'Vanessa',
  'Raquel',
  'Débora',
  'Márcia',
  'Sônia',
  'Tereza',
  'Aline',
  'Bianca',
  'Rosana',
  'Eliane',
  'Francisca',
  'Joana',
  'Lívia',
  'Priscila',
  'Regina',
  'Yara',
];
export const FIRST_NAMES_N = [
  'Alex',
  'Ariel',
  'Dani',
  'Jordan',
  'Rafa',
  'Sami',
  'Cris',
  'Andy',
  'Kim',
  'Noa',
];
export const LAST_NAMES = [
  'Silva',
  'Santos',
  'Oliveira',
  'Souza',
  'Rodrigues',
  'Ferreira',
  'Alves',
  'Pereira',
  'Lima',
  'Gomes',
  'Costa',
  'Ribeiro',
  'Martins',
  'Carvalho',
  'Almeida',
  'Lopes',
  'Soares',
  'Fernandes',
  'Vieira',
  'Barbosa',
  'Rocha',
  'Dias',
  'Nascimento',
  'Andrade',
  'Moreira',
  'Nunes',
  'Marques',
  'Machado',
  'Mendes',
  'Freitas',
  'Cardoso',
  'Ramos',
  'Gonçalves',
  'Santana',
  'Teixeira',
  'Moura',
  'Cavalcanti',
  'Monteiro',
  'Pinheiro',
  'Siqueira',
];

export function randomName(
  rng: Rng,
  gender: 'male' | 'female' | 'neutral',
): { firstName: string; lastName: string } {
  const pool =
    gender === 'male' ? FIRST_NAMES_M : gender === 'female' ? FIRST_NAMES_F : FIRST_NAMES_N;
  return { firstName: rng.pick(pool), lastName: rng.pick(LAST_NAMES) };
}
