import type { OfficeLevel } from '../election/offices';
import type { IdeologyVector } from '../ideology/axes';
import type { IssueId } from '../ideology/issues';
import type { PromiseTarget } from './types';

export interface ProposalDefinition {
  id: string;
  issue: IssueId;
  title: string;
  description: string;
  /** Deslocamento na posição percebida do candidato. */
  ideologyShift: Partial<IdeologyVector>;
  /** Como a promessa será avaliada no fim do mandato (executivo). */
  promise: PromiseTarget;
  /** Avaliação alternativa para mandatos legislativos. */
  legislativePromise?: PromiseTarget;
  levels: OfficeLevel[];
}

const ALL: OfficeLevel[] = ['municipal', 'estadual', 'federal'];
const SUB: OfficeLevel[] = ['estadual', 'federal'];

/**
 * Catálogo de propostas. Há propostas em direções ideológicas opostas para o mesmo tema —
 * o jogo não favorece nenhuma; o efeito eleitoral depende de quem é o eleitorado.
 */
export const PROPOSALS: ProposalDefinition[] = [
  {
    id: 'jobs_public_works',
    issue: 'jobs',
    title: 'Frentes de trabalho e obras públicas',
    description: 'O Estado puxa o emprego com obras.',
    ideologyShift: { economy: -6 },
    promise: { kind: 'indicator', indicator: 'unemployment', direction: 'down', amount: 1 },
    legislativePromise: { kind: 'billProposed', categoryId: 'infrastructure' },
    levels: ALL,
  },
  {
    id: 'jobs_lower_payroll',
    issue: 'jobs',
    title: 'Menos encargos para contratar',
    description: 'Desonerar a folha para gerar vagas.',
    ideologyShift: { economy: 6, fiscal: 4 },
    promise: { kind: 'law', categoryId: 'labor', optionIds: ['labor_flexible'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'labor' },
    levels: ['federal'],
  },
  {
    id: 'labor_min_wage',
    issue: 'jobs',
    title: 'Valorização do salário mínimo',
    description: 'Aumentos reais e proteção ao trabalhador.',
    ideologyShift: { economy: -6 },
    promise: { kind: 'law', categoryId: 'labor', optionIds: ['labor_protective'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'labor' },
    levels: ['federal'],
  },
  {
    id: 'tax_cut',
    issue: 'taxes',
    title: 'Reduzir impostos',
    description: 'Simplificar e cortar a carga tributária.',
    ideologyShift: { fiscal: 9, economy: 4 },
    promise: { kind: 'law', categoryId: 'taxation', optionIds: ['tax_low'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'taxation' },
    levels: ALL,
  },
  {
    id: 'tax_no_raise',
    issue: 'taxes',
    title: 'Nenhum imposto novo',
    description: 'Compromisso de não aumentar tributos.',
    ideologyShift: { fiscal: 5 },
    promise: {
      kind: 'noLaw',
      categoryId: 'taxation',
      forbiddenOptionIds: ['tax_progressive', 'tax_wealth'],
    },
    levels: ALL,
  },
  {
    id: 'tax_wealth',
    issue: 'taxes',
    title: 'Taxar os super-ricos',
    description: 'Imposto sobre grandes fortunas e alívio para os mais pobres.',
    ideologyShift: { fiscal: -9, economy: -5 },
    promise: { kind: 'law', categoryId: 'taxation', optionIds: ['tax_progressive', 'tax_wealth'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'taxation' },
    levels: SUB,
  },
  {
    id: 'health_more',
    issue: 'healthcare',
    title: 'Mais médicos e hospitais',
    description: 'Ampliar o investimento na saúde pública.',
    ideologyShift: { economy: -4 },
    promise: { kind: 'budget', category: 'health', minRatio: 1.12 },
    legislativePromise: { kind: 'billProposed', categoryId: 'healthcare' },
    levels: ALL,
  },
  {
    id: 'health_partnerships',
    issue: 'healthcare',
    title: 'Parcerias na saúde',
    description: 'Gestão com o setor privado para zerar filas.',
    ideologyShift: { economy: 7 },
    promise: {
      kind: 'law',
      categoryId: 'healthcare',
      optionIds: ['health_mixed', 'health_private'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'healthcare' },
    levels: ALL,
  },
  {
    id: 'edu_fulltime',
    issue: 'education',
    title: 'Escola em tempo integral',
    description: 'Mais horas de aula e investimento em educação.',
    ideologyShift: { economy: -3, social: -3 },
    promise: { kind: 'law', categoryId: 'education', optionIds: ['edu_fulltime'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'education' },
    levels: ALL,
  },
  {
    id: 'edu_vouchers',
    issue: 'education',
    title: 'Vouchers educacionais',
    description: 'A família escolhe a escola, pública ou privada.',
    ideologyShift: { economy: 8, social: 3 },
    promise: { kind: 'law', categoryId: 'education', optionIds: ['edu_vouchers'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'education' },
    levels: ALL,
  },
  {
    id: 'edu_technical',
    issue: 'education',
    title: 'Ensino técnico para todos',
    description: 'Formar jovens para o mercado de trabalho.',
    ideologyShift: { economy: 2 },
    promise: { kind: 'law', categoryId: 'education', optionIds: ['edu_tech'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'education' },
    levels: ALL,
  },
  {
    id: 'sec_tough',
    issue: 'security',
    title: 'Tolerância zero com o crime',
    description: 'Mais polícia nas ruas e penas mais duras.',
    ideologyShift: { security: 11, social: 3 },
    promise: { kind: 'law', categoryId: 'security', optionIds: ['sec_punitive'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'security' },
    levels: ALL,
  },
  {
    id: 'sec_prevention',
    issue: 'security',
    title: 'Segurança com prevenção',
    description: 'Políticas sociais, iluminação e inteligência.',
    ideologyShift: { security: -9 },
    promise: {
      kind: 'law',
      categoryId: 'security',
      optionIds: ['sec_preventive', 'sec_intelligence'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'security' },
    levels: ALL,
  },
  {
    id: 'sec_budget',
    issue: 'security',
    title: 'Reforçar o orçamento da segurança',
    description: 'Viaturas, câmeras e efetivo.',
    ideologyShift: { security: 4 },
    promise: { kind: 'budget', category: 'security', minRatio: 1.15 },
    levels: ALL,
  },
  {
    id: 'anticorruption',
    issue: 'corruption',
    title: 'Pacote anticorrupção',
    description: 'Transparência total nos gastos públicos.',
    ideologyShift: { institutions: 6 },
    promise: { kind: 'law', categoryId: 'institutions', optionIds: ['inst_transparency'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'institutions' },
    levels: ALL,
  },
  {
    id: 'env_zero_deforestation',
    issue: 'environment',
    title: 'Desmatamento zero',
    description: 'Fiscalização rígida e metas ambientais.',
    ideologyShift: { environment: -11 },
    promise: {
      kind: 'law',
      categoryId: 'environment',
      optionIds: ['env_strict', 'env_green_economy'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'environment' },
    levels: SUB,
  },
  {
    id: 'env_fast_licensing',
    issue: 'agriculture',
    title: 'Licenciamento ágil para produzir',
    description: 'Destravar obras e o agronegócio.',
    ideologyShift: { environment: 11, economy: 3 },
    promise: { kind: 'law', categoryId: 'environment', optionIds: ['env_flexible'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'environment' },
    levels: SUB,
  },
  {
    id: 'agro_exports',
    issue: 'agriculture',
    title: 'Abrir mercados para o agro',
    description: 'Acordos comerciais para exportar mais.',
    ideologyShift: { trade: 9 },
    promise: { kind: 'law', categoryId: 'trade', optionIds: ['trade_open'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'trade' },
    levels: ['federal'],
  },
  {
    id: 'industry_protection',
    issue: 'jobs',
    title: 'Proteger a indústria nacional',
    description: 'Tarifas e conteúdo local para gerar empregos.',
    ideologyShift: { trade: -9, foreign: 4 },
    promise: { kind: 'law', categoryId: 'trade', optionIds: ['trade_protectionist'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'trade' },
    levels: ['federal'],
  },
  {
    id: 'pensions_protect',
    issue: 'pensions',
    title: 'Proteger as aposentadorias',
    description: 'Nenhuma perda de direitos previdenciários.',
    ideologyShift: { economy: -4 },
    promise: {
      kind: 'noLaw',
      categoryId: 'pensions',
      forbiddenOptionIds: ['pen_reform', 'pen_capitalization'],
    },
    levels: SUB,
  },
  {
    id: 'pensions_reform',
    issue: 'pensions',
    title: 'Reforma da Previdência',
    description: 'Equilibrar as contas para as próximas gerações.',
    ideologyShift: { fiscal: 5, economy: 6 },
    promise: {
      kind: 'law',
      categoryId: 'pensions',
      optionIds: ['pen_reform', 'pen_capitalization'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'pensions' },
    levels: SUB,
  },
  {
    id: 'housing_program',
    issue: 'housing',
    title: 'Casa própria para todos',
    description: 'Programa habitacional para baixa renda.',
    ideologyShift: { economy: -5 },
    promise: { kind: 'budget', category: 'social', minRatio: 1.12 },
    levels: ALL,
  },
  {
    id: 'welfare_income',
    issue: 'welfare',
    title: 'Renda básica ampliada',
    description: 'Ampliar a transferência de renda.',
    ideologyShift: { economy: -8, fiscal: -4 },
    promise: { kind: 'budget', category: 'social', minRatio: 1.2 },
    levels: SUB,
  },
  {
    id: 'infra_big_plan',
    issue: 'infrastructure',
    title: 'Grande plano de obras',
    description: 'Estradas, saneamento e mobilidade.',
    ideologyShift: { economy: -4 },
    promise: { kind: 'budget', category: 'infrastructure', minRatio: 1.2 },
    legislativePromise: { kind: 'billProposed', categoryId: 'infrastructure' },
    levels: ALL,
  },
  {
    id: 'infra_concessions',
    issue: 'infrastructure',
    title: 'Concessões e privatizações',
    description: 'Atrair investimento privado para a infraestrutura.',
    ideologyShift: { economy: 10 },
    promise: {
      kind: 'law',
      categoryId: 'infrastructure',
      optionIds: ['infra_concessions', 'infra_ppp'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'infrastructure' },
    levels: ALL,
  },
  {
    id: 'transport_fare',
    issue: 'transport',
    title: 'Transporte público melhor e mais barato',
    description: 'Subsídio e novas linhas.',
    ideologyShift: { economy: -4, federalism: -2 },
    promise: { kind: 'budget', category: 'infrastructure', minRatio: 1.1 },
    levels: ['municipal', 'estadual'],
  },
  {
    id: 'digital_gov',
    issue: 'technology',
    title: 'Governo digital',
    description: 'Serviços públicos pelo celular e apoio a startups.',
    ideologyShift: { institutions: 5, trade: 3 },
    promise: { kind: 'law', categoryId: 'administration', optionIds: ['adm_digital'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'administration' },
    levels: ALL,
  },
  {
    id: 'cut_red_tape',
    issue: 'regulation',
    title: 'Fim da burocracia',
    description: 'Estado enxuto e menos papelada.',
    ideologyShift: { economy: 7, institutions: 4 },
    promise: { kind: 'law', categoryId: 'administration', optionIds: ['adm_lean'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'administration' },
    levels: ALL,
  },
  {
    id: 'inflation_control',
    issue: 'inflation',
    title: 'Controlar a inflação',
    description: 'Responsabilidade fiscal para proteger o poder de compra.',
    ideologyShift: { fiscal: 5 },
    promise: { kind: 'indicator', indicator: 'inflation', direction: 'down', amount: 0.8 },
    levels: ['federal'],
  },
  {
    id: 'cheap_credit',
    issue: 'credit',
    title: 'Crédito barato para pequenos negócios',
    description: 'Bancos públicos financiando quem produz.',
    ideologyShift: { economy: -4 },
    promise: { kind: 'indicator', indicator: 'growth', direction: 'up', amount: 0.5 },
    levels: SUB,
  },
  {
    id: 'decentralize',
    issue: 'infrastructure',
    title: 'Mais recursos para estados e municípios',
    description: 'Novo pacto federativo.',
    ideologyShift: { federalism: 10 },
    promise: { kind: 'law', categoryId: 'federalism', optionIds: ['fed_decentralized'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'federalism' },
    levels: ['federal'],
  },
  {
    id: 'income_growth',
    issue: 'inflation',
    title: 'Aumentar a renda das famílias',
    description: 'Crescimento com ganhos reais.',
    ideologyShift: {},
    promise: { kind: 'indicator', indicator: 'income', direction: 'up', amount: 4 },
    levels: ALL,
  },

  // --- Nação: propostas federais ligadas às novas leis (pares em direções opostas) ---
  {
    id: 'agrarian_reform',
    issue: 'agriculture',
    title: 'Reforma agrária',
    description: 'Redistribuir terras improdutivas e assentar famílias.',
    ideologyShift: { economy: -8, social: -3 },
    promise: { kind: 'law', categoryId: 'land', optionIds: ['land_reform', 'land_collective'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'land' },
    levels: ['federal'],
  },
  {
    id: 'land_property_rights',
    issue: 'agriculture',
    title: 'Segurança jurídica no campo',
    description: 'Proteger a propriedade rural e destravar o investimento no agro.',
    ideologyShift: { economy: 8, social: 3 },
    promise: { kind: 'law', categoryId: 'land', optionIds: ['land_latifundio'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'land' },
    levels: ['federal'],
  },
  {
    id: 'oil_is_ours',
    issue: 'infrastructure',
    title: 'O petróleo é nosso',
    description: 'Monopólio estatal dos recursos naturais estratégicos.',
    ideologyShift: { economy: -8, foreign: 6 },
    promise: { kind: 'law', categoryId: 'resources', optionIds: ['res_monopoly'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'resources' },
    levels: ['federal'],
  },
  {
    id: 'resources_concessions',
    issue: 'regulation',
    title: 'Abrir o petróleo ao capital privado',
    description: 'Concessões para atrair investimento e tecnologia na exploração.',
    ideologyShift: { economy: 8, trade: 4 },
    promise: { kind: 'law', categoryId: 'resources', optionIds: ['res_concession'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'resources' },
    levels: ['federal'],
  },
  {
    id: 'open_economy',
    issue: 'jobs',
    title: 'Abrir a economia',
    description: 'Cortar tarifas e integrar o país às cadeias globais.',
    ideologyShift: { trade: 10, economy: 4 },
    promise: { kind: 'law', categoryId: 'trade', optionIds: ['trade_open'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'trade' },
    levels: ['federal'],
  },
  {
    id: 'import_substitution',
    issue: 'jobs',
    title: 'Substituir importações',
    description: 'Tarifas altas e crédito para a indústria nacional ocupar o mercado interno.',
    ideologyShift: { trade: -11, economy: -3, foreign: 5 },
    promise: { kind: 'law', categoryId: 'trade', optionIds: ['trade_isi', 'trade_autarky'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'trade' },
    levels: ['federal'],
  },
  {
    id: 'new_industrial_policy',
    issue: 'jobs',
    title: 'Nova política industrial',
    description: 'Crédito público e metas para setores estratégicos.',
    ideologyShift: { economy: -6, trade: -3 },
    promise: {
      kind: 'law',
      categoryId: 'industrial_policy',
      optionIds: ['ind_bndes', 'ind_local_content', 'ind_national_plan'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'industrial_policy' },
    levels: ['federal'],
  },
  {
    id: 'industrial_neutrality',
    issue: 'regulation',
    title: 'Neutralidade industrial',
    description: 'O Estado não escolhe vencedores: sem subsídios setoriais, só regras iguais.',
    ideologyShift: { economy: 7, fiscal: 4 },
    promise: { kind: 'law', categoryId: 'industrial_policy', optionIds: ['ind_neutral'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'industrial_policy' },
    levels: ['federal'],
  },
  {
    id: 'universal_basic_income',
    issue: 'welfare',
    title: 'Renda básica universal',
    description: 'Um valor mensal garantido a todos os cidadãos.',
    ideologyShift: { economy: -9, fiscal: -6, social: -3 },
    promise: { kind: 'law', categoryId: 'welfare', optionIds: ['wel_universal_income'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'welfare' },
    levels: ['federal'],
  },
  {
    id: 'welfare_no_universal',
    issue: 'taxes',
    title: 'Assistência só para quem precisa',
    description: 'Compromisso de não instituir renda universal nem ampliar as transferências.',
    ideologyShift: { fiscal: 6, economy: 4 },
    promise: {
      kind: 'noLaw',
      categoryId: 'welfare',
      forbiddenOptionIds: ['wel_universal_income', 'wel_expanded'],
    },
    levels: ['federal'],
  },
  {
    id: 'independent_central_bank',
    issue: 'inflation',
    title: 'Banco Central independente',
    description: 'Blindar a moeda: mandato fixo, sem interferência do governo.',
    ideologyShift: { fiscal: 5, institutions: 4 },
    promise: {
      kind: 'noLaw',
      categoryId: 'central_bank',
      forbiddenOptionIds: ['cb_government', 'cb_dual_mandate'],
    },
    levels: ['federal'],
  },
  {
    id: 'government_central_bank',
    issue: 'credit',
    title: 'Banco Central a serviço do crescimento',
    description: 'Juros e crédito alinhados à política de desenvolvimento do governo.',
    ideologyShift: { economy: -6, institutions: -3 },
    promise: {
      kind: 'law',
      categoryId: 'central_bank',
      optionIds: ['cb_government', 'cb_dual_mandate'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'central_bank' },
    levels: ['federal'],
  },
  {
    id: 'raise_minimum_wage',
    issue: 'jobs',
    title: 'Salário mínimo com ganho real',
    description: 'Um piso nacional alto, com aumentos acima da inflação.',
    ideologyShift: { economy: -7 },
    promise: { kind: 'law', categoryId: 'minimum_wage', optionIds: ['mw_high'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'minimum_wage' },
    levels: ['federal'],
  },
  {
    id: 'lower_minimum_wage',
    issue: 'jobs',
    title: 'Piso que cabe no bolso das empresas',
    description: 'Um salário mínimo menor para estimular contratações formais.',
    ideologyShift: { economy: 7, fiscal: 3 },
    promise: { kind: 'law', categoryId: 'minimum_wage', optionIds: ['mw_low', 'mw_none'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'minimum_wage' },
    levels: ['federal'],
  },
  {
    id: 'minimal_state',
    issue: 'regulation',
    title: 'Estado mínimo',
    description: 'Privatizar, desregular e deixar o mercado alocar os investimentos.',
    ideologyShift: { economy: 11, fiscal: 6 },
    promise: { kind: 'law', categoryId: 'economic_system', optionIds: ['econ_laissez_faire'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'economic_system' },
    levels: ['federal'],
  },
  {
    id: 'cooperative_economy',
    issue: 'jobs',
    title: 'Economia de cooperativas',
    description: 'Empresas geridas por quem trabalha, com participação nos lucros.',
    ideologyShift: { economy: -10, social: -2 },
    promise: { kind: 'law', categoryId: 'economic_system', optionIds: ['econ_cooperative'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'economic_system' },
    levels: ['federal'],
  },
  {
    id: 'planned_economy',
    issue: 'jobs',
    title: 'Planejamento econômico central',
    description: 'O Estado define metas, preços e investimentos para toda a economia.',
    ideologyShift: { economy: -14, fiscal: -6, trade: -6 },
    promise: { kind: 'law', categoryId: 'economic_system', optionIds: ['econ_planned'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'economic_system' },
    levels: ['federal'],
  },
  {
    id: 'parliamentarism',
    issue: 'corruption',
    title: 'Parlamentarismo',
    description: 'O governo passa a depender da confiança do Congresso.',
    ideologyShift: { institutions: 5 },
    promise: {
      kind: 'law',
      categoryId: 'regime',
      optionIds: ['reg_parliamentary', 'reg_semi_presidential'],
    },
    legislativePromise: { kind: 'billProposed', categoryId: 'regime' },
    levels: ['federal'],
  },
  {
    id: 'strong_presidency',
    issue: 'corruption',
    title: 'Presidência forte',
    description: 'Mais instrumentos para o Executivo governar sem paralisia.',
    ideologyShift: { institutions: -6, security: 3 },
    promise: { kind: 'law', categoryId: 'institutions', optionIds: ['inst_strong_executive'] },
    legislativePromise: { kind: 'billProposed', categoryId: 'institutions' },
    levels: ['federal'],
  },
];

export function getProposal(id: string): ProposalDefinition | undefined {
  return PROPOSALS.find((p) => p.id === id);
}

export function proposalsFor(level: OfficeLevel): ProposalDefinition[] {
  return PROPOSALS.filter((p) => p.levels.includes(level));
}
