import type { Party } from './types';

export type PartySeed = Omit<Party, 'candidateIds' | 'unity' | 'lawPositions'>;

/**
 * Partidos FICTÍCIOS do cenário padrão. Qualquer semelhança com siglas reais é coincidência.
 * As posições são coordenadas do modelo e nenhuma é tratada como "certa" ou "errada".
 */
export const DEFAULT_PARTIES: PartySeed[] = [
  {
    id: 'ftu',
    name: 'Frente Trabalhista Unida',
    acronym: 'FTU',
    symbol: 'gear',
    color: '#d62839',
    ideology: {
      economy: 25,
      social: 35,
      fiscal: 30,
      security: 35,
      federalism: 40,
      environment: 45,
      trade: 30,
      institutions: 45,
      foreign: 35,
    },
    popularity: 58,
    influence: 72,
    money: 70,
    militancy: 80,
    strongRegions: ['nordeste'],
    weakRegions: ['sul', 'centro_oeste'],
    priorities: ['jobs', 'welfare', 'pensions'],
    priorityPopTypes: ['workers', 'industrial_workers', 'unemployed', 'civil_servants'],
    factions: [
      {
        id: 'sindical',
        name: 'Ala Sindical',
        ideologyShift: { economy: -8, trade: -6 },
        size: 0.45,
        satisfaction: 65,
      },
      {
        id: 'moderada',
        name: 'Ala Moderada',
        ideologyShift: { economy: 12, fiscal: 8 },
        size: 0.55,
        satisfaction: 60,
      },
    ],
    leaderName: 'Helena Batista',
    provenance: { kind: 'fictional' },
    description:
      'Partido de base sindical, defende presença forte do Estado na economia e proteção ao emprego.',
  },
  {
    id: 'alb',
    name: 'Aliança Liberal Brasileira',
    acronym: 'ALB',
    symbol: 'torch',
    color: '#f2a541',
    ideology: {
      economy: 82,
      social: 45,
      fiscal: 82,
      security: 55,
      federalism: 70,
      environment: 60,
      trade: 85,
      institutions: 70,
      foreign: 40,
    },
    popularity: 42,
    influence: 45,
    money: 75,
    militancy: 45,
    strongRegions: ['sudeste', 'sul'],
    weakRegions: ['norte', 'nordeste'],
    priorities: ['taxes', 'regulation', 'technology'],
    priorityPopTypes: ['business', 'tech_workers', 'merchants', 'middle_class'],
    factions: [
      {
        id: 'economica',
        name: 'Liberais Econômicos',
        ideologyShift: { economy: 8, fiscal: 6 },
        size: 0.6,
        satisfaction: 62,
      },
      {
        id: 'social',
        name: 'Liberais Sociais',
        ideologyShift: { social: -15 },
        size: 0.4,
        satisfaction: 58,
      },
    ],
    leaderName: 'Rodrigo Valente',
    provenance: { kind: 'fictional' },
    description: 'Defende abertura econômica, impostos menores e desburocratização.',
  },
  {
    id: 'pop',
    name: 'Partido da Ordem Popular',
    acronym: 'POP',
    symbol: 'shield',
    color: '#1d3557',
    ideology: {
      economy: 65,
      social: 80,
      fiscal: 68,
      security: 88,
      federalism: 55,
      environment: 72,
      trade: 50,
      institutions: 40,
      foreign: 78,
    },
    popularity: 55,
    influence: 60,
    money: 60,
    militancy: 75,
    strongRegions: ['sul', 'centro_oeste', 'norte'],
    weakRegions: ['nordeste'],
    priorities: ['security', 'corruption', 'taxes'],
    priorityPopTypes: ['merchants', 'retirees', 'farmers', 'middle_class'],
    factions: [
      {
        id: 'linha_dura',
        name: 'Linha Dura',
        ideologyShift: { security: 8, social: 6 },
        size: 0.55,
        satisfaction: 66,
      },
      {
        id: 'pragmaticos',
        name: 'Pragmáticos',
        ideologyShift: { social: -10, institutions: 10 },
        size: 0.45,
        satisfaction: 58,
      },
    ],
    leaderName: 'Coronel Augusto Prado',
    provenance: { kind: 'fictional' },
    description: 'Prioriza segurança pública, valores tradicionais e soberania nacional.',
  },
  {
    id: 'udc',
    name: 'União Democrática do Centro',
    acronym: 'UDC',
    symbol: 'compass',
    color: '#7b2cbf',
    ideology: {
      economy: 55,
      social: 55,
      fiscal: 52,
      security: 58,
      federalism: 60,
      environment: 55,
      trade: 55,
      institutions: 50,
      foreign: 50,
    },
    popularity: 50,
    influence: 88,
    money: 85,
    militancy: 35,
    strongRegions: ['nordeste', 'sudeste'],
    weakRegions: [],
    priorities: ['infrastructure', 'healthcare', 'jobs'],
    priorityPopTypes: ['civil_servants', 'retirees', 'merchants'],
    factions: [
      {
        id: 'governista',
        name: 'Bloco Governista',
        ideologyShift: {},
        size: 0.5,
        satisfaction: 60,
      },
      {
        id: 'regional',
        name: 'Lideranças Regionais',
        ideologyShift: { federalism: 12 },
        size: 0.5,
        satisfaction: 60,
      },
    ],
    leaderName: 'Senador Otávio Mendes',
    provenance: { kind: 'fictional' },
    description:
      'Grande partido de centro, pragmático, com forte presença no Congresso e nos municípios.',
  },
  {
    id: 'ren',
    name: 'Rede Ecológica Nacional',
    acronym: 'REN',
    symbol: 'leaf',
    color: '#2a9d8f',
    ideology: {
      economy: 40,
      social: 25,
      fiscal: 40,
      security: 30,
      federalism: 45,
      environment: 10,
      trade: 45,
      institutions: 60,
      foreign: 25,
    },
    popularity: 30,
    influence: 28,
    money: 30,
    militancy: 55,
    strongRegions: ['sudeste', 'norte'],
    weakRegions: ['centro_oeste'],
    priorities: ['environment', 'education', 'healthcare'],
    priorityPopTypes: ['students', 'health_workers', 'middle_class', 'tech_workers'],
    factions: [
      {
        id: 'ambientalistas',
        name: 'Ambientalistas',
        ideologyShift: { environment: -8 },
        size: 0.6,
        satisfaction: 64,
      },
      {
        id: 'desenvolvimentistas',
        name: 'Desenvolvimento Sustentável',
        ideologyShift: { environment: 12, economy: 8 },
        size: 0.4,
        satisfaction: 58,
      },
    ],
    leaderName: 'Marina Ferraz',
    provenance: { kind: 'fictional' },
    description: 'Partido ambientalista, defende regulação ambiental e investimento em educação.',
  },
  {
    id: 'psa',
    name: 'Partido Social Agrário',
    acronym: 'PSA',
    symbol: 'wheat',
    color: '#8d6e3f',
    ideology: {
      economy: 65,
      social: 70,
      fiscal: 70,
      security: 72,
      federalism: 78,
      environment: 88,
      trade: 70,
      institutions: 65,
      foreign: 62,
    },
    popularity: 38,
    influence: 55,
    money: 70,
    militancy: 40,
    strongRegions: ['centro_oeste', 'sul', 'norte'],
    weakRegions: ['sudeste'],
    priorities: ['agriculture', 'credit', 'infrastructure'],
    priorityPopTypes: ['farmers', 'business', 'merchants'],
    factions: [
      {
        id: 'produtores',
        name: 'Produtores Rurais',
        ideologyShift: { environment: 6 },
        size: 0.65,
        satisfaction: 63,
      },
      {
        id: 'cooperativistas',
        name: 'Cooperativistas',
        ideologyShift: { economy: -10 },
        size: 0.35,
        satisfaction: 60,
      },
    ],
    leaderName: 'Deputada Rosa Albuquerque',
    provenance: { kind: 'fictional' },
    description: 'Representa o setor agropecuário, crédito rural e infraestrutura logística.',
  },
  {
    id: 'nes',
    name: 'Nova Esquerda Socialista',
    acronym: 'NES',
    symbol: 'star',
    color: '#9b2226',
    ideology: {
      economy: 10,
      social: 18,
      fiscal: 18,
      security: 20,
      federalism: 35,
      environment: 25,
      trade: 22,
      institutions: 40,
      foreign: 30,
    },
    popularity: 22,
    influence: 20,
    money: 20,
    militancy: 85,
    strongRegions: ['sudeste', 'nordeste'],
    weakRegions: ['centro_oeste', 'sul'],
    priorities: ['welfare', 'housing', 'education'],
    priorityPopTypes: ['students', 'unemployed', 'workers', 'civil_servants'],
    factions: [
      {
        id: 'movimentos',
        name: 'Movimentos Sociais',
        ideologyShift: { economy: -5 },
        size: 0.55,
        satisfaction: 68,
      },
      {
        id: 'institucional',
        name: 'Ala Institucional',
        ideologyShift: { economy: 10, institutions: 8 },
        size: 0.45,
        satisfaction: 60,
      },
    ],
    leaderName: 'Caio Antunes',
    provenance: { kind: 'fictional' },
    description:
      'Partido de esquerda radical, defende redistribuição de renda e serviços públicos amplos.',
  },
  {
    id: 'renova',
    name: 'Movimento Renova',
    acronym: 'RENOVA',
    symbol: 'bolt',
    color: '#00a6c8',
    ideology: {
      economy: 62,
      social: 48,
      fiscal: 62,
      security: 55,
      federalism: 60,
      environment: 50,
      trade: 68,
      institutions: 80,
      foreign: 50,
    },
    popularity: 35,
    influence: 25,
    money: 40,
    militancy: 50,
    strongRegions: ['sudeste', 'sul'],
    weakRegions: ['nordeste'],
    priorities: ['corruption', 'technology', 'regulation'],
    priorityPopTypes: ['tech_workers', 'students', 'middle_class'],
    factions: [
      {
        id: 'digital',
        name: 'Ala Digital',
        ideologyShift: { institutions: 6 },
        size: 0.6,
        satisfaction: 65,
      },
      {
        id: 'gestores',
        name: 'Gestores',
        ideologyShift: { economy: 8 },
        size: 0.4,
        satisfaction: 60,
      },
    ],
    leaderName: 'Bruno Kaiser',
    provenance: { kind: 'fictional' },
    description: 'Movimento de renovação política, foco em transparência, inovação e gestão.',
  },
  {
    id: 'pfr',
    name: 'Partido Federalista Republicano',
    acronym: 'PFR',
    symbol: 'mountain',
    color: '#457b9d',
    ideology: {
      economy: 58,
      social: 58,
      fiscal: 60,
      security: 62,
      federalism: 85,
      environment: 62,
      trade: 58,
      institutions: 72,
      foreign: 55,
    },
    popularity: 32,
    influence: 50,
    money: 55,
    militancy: 30,
    strongRegions: ['sul', 'centro_oeste'],
    weakRegions: ['norte'],
    priorities: ['infrastructure', 'transport', 'regulation'],
    priorityPopTypes: ['business', 'merchants', 'civil_servants'],
    factions: [
      {
        id: 'municipalistas',
        name: 'Municipalistas',
        ideologyShift: { federalism: 6 },
        size: 0.55,
        satisfaction: 62,
      },
      {
        id: 'tecnicos',
        name: 'Técnicos',
        ideologyShift: { economy: 6, institutions: -6 },
        size: 0.45,
        satisfaction: 58,
      },
    ],
    leaderName: 'Governadora Lúcia Tavares',
    provenance: { kind: 'fictional' },
    description:
      'Defende mais autonomia para estados e municípios e investimento em infraestrutura.',
  },
];
