import type { PartyId } from '../core/types';
import type { IdeologyVector } from '../ideology/axes';
import type { PartySeed } from './parties.data';
import type { DataProvenance, PartyFaction } from './types';

/**
 * Os 30 partidos REAIS com registro no TSE (out/2026), em ordem aproximada de bancada na Câmara.
 * Sigla, nome, número e logo são oficiais; presidentes conforme a Wikipédia na mesma data.
 * Ideologia, popularidade, influência etc. são COORDENADAS DO MODELO do jogo (aproximações
 * para a simulação), não medições. Logos: Wikimedia Commons — fontes e licenças em
 * docs/PARTIDOS_REAIS.md.
 */

const SOURCE: DataProvenance = {
  kind: 'historical',
  source: 'TSE (partidos registrados) e Wikipédia (Lista de partidos políticos do Brasil)',
  sourceDate: '2026-10',
};

/** Vetor na ordem: economia, costumes, fiscal, segurança, federalismo, meio ambiente, comércio, instituições, exterior. */
function iv(
  ...v: [number, number, number, number, number, number, number, number, number]
): IdeologyVector {
  const [economy, social, fiscal, security, federalism, environment, trade, institutions, foreign] =
    v;
  return {
    economy,
    social,
    fiscal,
    security,
    federalism,
    environment,
    trade,
    institutions,
    foreign,
  };
}

function faction(
  id: string,
  name: string,
  ideologyShift: PartyFaction['ideologyShift'],
  size: number,
  satisfaction = 60,
): PartyFaction {
  return { id, name, ideologyShift, size, satisfaction };
}

/** Partidos pequenos: uma direção nacional coesa. */
const direcao = (name = 'Direção Nacional'): PartyFaction[] => [
  faction('direcao', name, {}, 1, 64),
];

export const REAL_PARTIES: PartySeed[] = [
  {
    id: 'pl',
    name: 'Partido Liberal',
    acronym: 'PL',
    number: 22,
    logo: 'partidos/pl.png',
    symbol: 'flag',
    color: '#1d3c8f',
    ideology: iv(68, 85, 72, 90, 55, 78, 55, 40, 80),
    popularity: 63,
    influence: 98,
    money: 88,
    militancy: 82,
    strongRegions: ['sul', 'centro_oeste', 'norte'],
    weakRegions: ['nordeste'],
    priorities: ['security', 'corruption', 'taxes'],
    priorityPopTypes: ['merchants', 'farmers', 'retirees', 'middle_class'],
    factions: [
      faction('bolsonaristas', 'Bolsonaristas', { security: 6, social: 6 }, 0.6, 66),
      faction('pragmaticos', 'Ala Pragmática', { social: -12, institutions: 10 }, 0.4, 58),
    ],
    leaderName: 'Valdemar Costa Neto',
    provenance: SOURCE,
    description:
      'Principal partido da direita e maior bancada eleita para a Câmara em 2022. Pauta de segurança, costumes conservadores e oposição ao governo federal.',
  },
  {
    id: 'pt',
    name: 'Partido dos Trabalhadores',
    acronym: 'PT',
    number: 13,
    logo: 'partidos/pt.png',
    symbol: 'star',
    color: '#c8102e',
    ideology: iv(25, 32, 30, 32, 40, 42, 32, 42, 38),
    popularity: 56,
    influence: 80,
    money: 82,
    militancy: 85,
    strongRegions: ['nordeste'],
    weakRegions: ['sul', 'centro_oeste'],
    priorities: ['jobs', 'welfare', 'healthcare'],
    priorityPopTypes: ['workers', 'industrial_workers', 'unemployed', 'civil_servants'],
    factions: [
      faction('majoritaria', 'Ala Majoritária', { economy: 8, fiscal: 6 }, 0.6, 64),
      faction('esquerda', 'Esquerda Petista', { economy: -8, trade: -6 }, 0.4, 60),
    ],
    leaderName: 'Edinho Silva',
    provenance: SOURCE,
    description:
      'Fundado em 1980 a partir do sindicalismo do ABC paulista; partido do presidente Lula. Integra a Federação Brasil da Esperança com PCdoB e PV.',
  },
  {
    id: 'uniao',
    name: 'União Brasil',
    acronym: 'UNIÃO',
    number: 44,
    logo: 'partidos/uniao.png',
    symbol: 'compass',
    color: '#3a86ff',
    ideology: iv(62, 62, 66, 68, 68, 66, 62, 56, 55),
    popularity: 43,
    influence: 88,
    money: 84,
    militancy: 35,
    strongRegions: ['centro_oeste', 'norte'],
    weakRegions: [],
    priorities: ['security', 'infrastructure', 'taxes'],
    priorityPopTypes: ['merchants', 'business', 'civil_servants'],
    factions: [
      faction('governista', 'Ala Governista', { economy: -6, institutions: 6 }, 0.45, 58),
      faction('oposicao', 'Ala Oposicionista', { social: 8, security: 6 }, 0.55, 60),
    ],
    leaderName: 'Antônio de Rueda',
    provenance: SOURCE,
    description:
      'Criado em 2022 pela fusão do DEM com o PSL, com bancada numerosa e fundo eleitoral robusto. Forma a federação União Progressista com o PP.',
  },
  {
    id: 'pp',
    name: 'Progressistas',
    acronym: 'PP',
    number: 11,
    logo: 'partidos/pp.png',
    symbol: 'wheat',
    color: '#56b4e9',
    ideology: iv(66, 68, 70, 72, 72, 82, 66, 60, 60),
    popularity: 38,
    influence: 68,
    money: 78,
    militancy: 35,
    strongRegions: ['sul', 'centro_oeste', 'nordeste'],
    weakRegions: ['sudeste'],
    priorities: ['agriculture', 'infrastructure', 'credit'],
    priorityPopTypes: ['farmers', 'business', 'merchants'],
    factions: [
      faction('agro', 'Agro', { environment: 6 }, 0.55, 62),
      faction('centrao', 'Centrão', { social: -6, institutions: 6 }, 0.45, 60),
    ],
    leaderName: 'Ciro Nogueira',
    provenance: SOURCE,
    description:
      'Herdeiro da Arena e do PDS, peça central do Centrão e da bancada ruralista. Forma a federação União Progressista com o União Brasil.',
  },
  {
    id: 'psd',
    name: 'Partido Social Democrático',
    acronym: 'PSD',
    number: 55,
    logo: 'partidos/psd.png',
    symbol: 'mountain',
    color: '#f4b400',
    ideology: iv(58, 56, 60, 60, 80, 62, 60, 70, 52),
    popularity: 40,
    influence: 66,
    money: 75,
    militancy: 30,
    strongRegions: ['sul', 'nordeste', 'sudeste'],
    weakRegions: [],
    priorities: ['infrastructure', 'healthcare', 'jobs'],
    priorityPopTypes: ['civil_servants', 'merchants', 'business'],
    factions: [
      faction('municipalistas', 'Governadores e Prefeitos', { federalism: 6 }, 0.55, 62),
      faction('governista', 'Ala Governista', { economy: -6 }, 0.45, 60),
    ],
    leaderName: 'Gilberto Kassab',
    provenance: SOURCE,
    description:
      'Fundado em 2011 por Gilberto Kassab, pragmático e de centro. Saiu das eleições de 2024 com o maior número de prefeituras do país.',
  },
  {
    id: 'republicanos',
    name: 'Republicanos',
    acronym: 'REPUBLICANOS',
    number: 10,
    logo: 'partidos/republicanos.png',
    symbol: 'book',
    color: '#3949ab',
    ideology: iv(64, 82, 68, 80, 60, 66, 58, 52, 66),
    popularity: 38,
    influence: 58,
    money: 70,
    militancy: 60,
    strongRegions: ['sudeste', 'norte'],
    weakRegions: [],
    priorities: ['security', 'education', 'jobs'],
    priorityPopTypes: ['workers', 'merchants', 'retirees'],
    factions: [
      faction('evangelica', 'Ala Evangélica', { social: 6 }, 0.55, 64),
      faction('gestora', 'Ala Gestora', { social: -10, economy: 6 }, 0.45, 60),
    ],
    leaderName: 'Marcos Pereira',
    provenance: SOURCE,
    description:
      'Antigo PRB, rebatizado em 2019; base evangélica e costumes conservadores. Partido do governador paulista Tarcísio de Freitas.',
  },
  {
    id: 'mdb',
    name: 'Movimento Democrático Brasileiro',
    acronym: 'MDB',
    number: 15,
    logo: 'partidos/mdb.png',
    symbol: 'compass',
    color: '#2e9e44',
    ideology: iv(55, 55, 54, 58, 64, 58, 56, 54, 50),
    popularity: 42,
    influence: 60,
    money: 78,
    militancy: 35,
    strongRegions: ['norte', 'nordeste', 'sul'],
    weakRegions: [],
    priorities: ['infrastructure', 'healthcare', 'jobs'],
    priorityPopTypes: ['civil_servants', 'retirees', 'merchants'],
    factions: [
      faction('governista', 'Bloco Governista', {}, 0.5),
      faction('regional', 'Lideranças Regionais', { federalism: 12 }, 0.5),
    ],
    leaderName: 'Baleia Rossi',
    provenance: SOURCE,
    description:
      'Herdeiro da oposição ao regime militar (1966) e uma das maiores máquinas municipais do país. Centro pragmático, presente em quase todos os governos.',
  },
  {
    id: 'pdt',
    name: 'Partido Democrático Trabalhista',
    acronym: 'PDT',
    number: 12,
    logo: 'partidos/pdt.png',
    symbol: 'rose',
    color: '#b23a48',
    ideology: iv(30, 38, 34, 38, 42, 45, 30, 48, 40),
    popularity: 18,
    influence: 26,
    money: 45,
    militancy: 50,
    strongRegions: ['nordeste', 'sul'],
    weakRegions: ['centro_oeste'],
    priorities: ['education', 'jobs', 'pensions'],
    priorityPopTypes: ['workers', 'civil_servants', 'students'],
    factions: [
      faction('trabalhistas', 'Trabalhistas', { economy: -6 }, 0.6),
      faction('moderados', 'Moderados', { economy: 8 }, 0.4, 58),
    ],
    leaderName: 'Carlos Lupi',
    provenance: SOURCE,
    description:
      'Fundado por Leonel Brizola, herdeiro do trabalhismo de Vargas e Jango. Bandeira histórica da escola em tempo integral.',
  },
  {
    id: 'psb',
    name: 'Partido Socialista Brasileiro',
    acronym: 'PSB',
    number: 40,
    logo: 'partidos/psb.png',
    symbol: 'sun',
    color: '#ff8f00',
    ideology: iv(35, 38, 38, 40, 45, 42, 42, 52, 38),
    popularity: 18,
    influence: 28,
    money: 50,
    militancy: 45,
    strongRegions: ['nordeste'],
    weakRegions: ['centro_oeste', 'sul'],
    priorities: ['healthcare', 'education', 'jobs'],
    priorityPopTypes: ['middle_class', 'civil_servants', 'workers'],
    factions: [
      faction('socialistas', 'Socialistas', { economy: -6 }, 0.45),
      faction('moderada', 'Ala Moderada', { economy: 8, fiscal: 6 }, 0.55),
    ],
    leaderName: 'João Henrique Campos',
    provenance: SOURCE,
    description:
      'Centro-esquerda com força em Pernambuco. Partido do vice-presidente Geraldo Alckmin.',
  },
  {
    id: 'podemos',
    name: 'Podemos',
    acronym: 'PODE',
    number: 20,
    logo: 'partidos/podemos.png',
    symbol: 'bolt',
    color: '#7cb342',
    ideology: iv(60, 62, 64, 66, 62, 62, 60, 66, 55),
    popularity: 16,
    influence: 23,
    money: 50,
    militancy: 35,
    strongRegions: ['sul', 'sudeste'],
    weakRegions: ['nordeste'],
    priorities: ['corruption', 'jobs', 'taxes'],
    priorityPopTypes: ['middle_class', 'merchants', 'tech_workers'],
    factions: [
      faction('liberal', 'Ala Liberal', { economy: 6 }, 0.55),
      faction('conservadora', 'Ala Conservadora', { social: 10 }, 0.45),
    ],
    leaderName: 'Renata Abreu',
    provenance: SOURCE,
    description:
      'Antigo PTN, rebatizado em 2017 com discurso de democracia participativa. Incorporou o PSC em 2023.',
  },
  {
    id: 'psdb',
    name: 'Partido da Social Democracia Brasileira',
    acronym: 'PSDB',
    number: 45,
    logo: 'partidos/psdb.png',
    symbol: 'book',
    color: '#0b5ed7',
    ideology: iv(62, 48, 62, 58, 58, 55, 72, 60, 42),
    popularity: 15,
    influence: 22,
    money: 50,
    militancy: 30,
    strongRegions: ['sudeste', 'centro_oeste'],
    weakRegions: ['nordeste'],
    priorities: ['education', 'healthcare', 'regulation'],
    priorityPopTypes: ['middle_class', 'business', 'tech_workers'],
    factions: [
      faction('historicos', 'Tucanos Históricos', { social: -6 }, 0.5, 56),
      faction('renovacao', 'Renovação', { economy: 6, social: 6 }, 0.5, 56),
    ],
    leaderName: 'Aécio Neves',
    provenance: SOURCE,
    description:
      'Fundado em 1988 por dissidentes do PMDB; governou o país com Fernando Henrique Cardoso (1995–2002). Federado ao Cidadania.',
  },
  {
    id: 'psol',
    name: 'Partido Socialismo e Liberdade',
    acronym: 'PSOL',
    number: 50,
    logo: 'partidos/psol.png',
    symbol: 'sun',
    color: '#8e24aa',
    ideology: iv(10, 15, 18, 18, 35, 22, 22, 42, 30),
    popularity: 15,
    influence: 20,
    money: 35,
    militancy: 88,
    strongRegions: ['sudeste'],
    weakRegions: ['centro_oeste', 'sul', 'norte'],
    priorities: ['housing', 'welfare', 'education'],
    priorityPopTypes: ['students', 'civil_servants', 'workers', 'unemployed'],
    factions: [
      faction('movimentos', 'Movimentos Sociais', { economy: -5 }, 0.55, 66),
      faction('institucional', 'Ala Institucional', { economy: 10, institutions: 8 }, 0.45),
    ],
    leaderName: 'Paula Coradi',
    provenance: SOURCE,
    description:
      'Fundado em 2004 por dissidentes do PT; esquerda socialista ligada a movimentos sociais. Federado à Rede Sustentabilidade.',
  },
  {
    id: 'pcdob',
    name: 'Partido Comunista do Brasil',
    acronym: 'PCdoB',
    number: 65,
    logo: 'partidos/pcdob.png',
    symbol: 'star',
    color: '#a4161a',
    ideology: iv(18, 30, 25, 30, 38, 40, 25, 40, 25),
    popularity: 10,
    influence: 13,
    money: 25,
    militancy: 70,
    strongRegions: ['nordeste'],
    weakRegions: ['sul', 'centro_oeste'],
    priorities: ['jobs', 'education', 'welfare'],
    priorityPopTypes: ['students', 'workers', 'industrial_workers'],
    factions: direcao('Comitê Central'),
    leaderName: 'Luciana Santos',
    provenance: SOURCE,
    description:
      'Partido Comunista do Brasil, fundado em 1962. Aliado histórico do PT, integra a Federação Brasil da Esperança.',
  },
  {
    id: 'avante',
    name: 'Avante',
    acronym: 'AVANTE',
    number: 70,
    logo: 'partidos/avante.png',
    symbol: 'bolt',
    color: '#f4511e',
    ideology: iv(52, 58, 56, 62, 60, 60, 55, 55, 52),
    popularity: 9,
    influence: 14,
    money: 30,
    militancy: 25,
    strongRegions: ['sudeste', 'nordeste'],
    weakRegions: [],
    priorities: ['jobs', 'healthcare', 'infrastructure'],
    priorityPopTypes: ['workers', 'merchants'],
    factions: direcao(),
    leaderName: 'Luis Tibé',
    provenance: SOURCE,
    description:
      'Antigo PTdoB, rebatizado em 2017. Partido de centro com base forte em Minas Gerais.',
  },
  {
    id: 'solidariedade',
    name: 'Solidariedade',
    acronym: 'SOLIDARIEDADE',
    number: 77,
    logo: 'partidos/solidariedade.png',
    symbol: 'gear',
    color: '#ffa000',
    ideology: iv(45, 55, 48, 55, 55, 55, 45, 52, 50),
    popularity: 8,
    influence: 9,
    money: 30,
    militancy: 40,
    strongRegions: ['sudeste'],
    weakRegions: [],
    priorities: ['jobs', 'pensions', 'welfare'],
    priorityPopTypes: ['workers', 'industrial_workers'],
    factions: direcao(),
    leaderName: 'Eurípedes Júnior',
    provenance: SOURCE,
    description:
      'Fundado em 2013 por lideranças da Força Sindical; incorporou o PROS em 2023. Forma a federação Renovação Solidária com o PRD.',
  },
  {
    id: 'prd',
    name: 'Partido Renovação Democrática',
    acronym: 'PRD',
    number: 25,
    logo: 'partidos/prd.png',
    symbol: 'shield',
    color: '#00897b',
    ideology: iv(62, 72, 66, 76, 60, 66, 58, 55, 66),
    popularity: 8,
    influence: 9,
    money: 35,
    militancy: 30,
    strongRegions: ['sudeste', 'centro_oeste'],
    weakRegions: [],
    priorities: ['security', 'jobs', 'taxes'],
    priorityPopTypes: ['merchants', 'workers'],
    factions: direcao(),
    leaderName: 'Marcus Vinícius Neskau',
    provenance: SOURCE,
    description:
      'Criado em 2023 pela fusão do PTB com o Patriota. Centro-direita; forma a federação Renovação Solidária com o Solidariedade.',
  },
  {
    id: 'pv',
    name: 'Partido Verde',
    acronym: 'PV',
    number: 43,
    logo: 'partidos/pv.png',
    symbol: 'leaf',
    color: '#1b5e20',
    ideology: iv(40, 32, 40, 35, 48, 15, 45, 55, 30),
    popularity: 8,
    influence: 8,
    money: 25,
    militancy: 40,
    strongRegions: ['sudeste'],
    weakRegions: ['centro_oeste'],
    priorities: ['environment', 'healthcare', 'education'],
    priorityPopTypes: ['middle_class', 'students', 'health_workers'],
    factions: direcao(),
    leaderName: 'José Luiz Penna',
    provenance: SOURCE,
    description:
      'Fundado em 1986, defende a ecologia política. Integra a Federação Brasil da Esperança com PT e PCdoB.',
  },
  {
    id: 'novo',
    name: 'Partido Novo',
    acronym: 'NOVO',
    number: 30,
    logo: 'partidos/novo.png',
    symbol: 'torch',
    color: '#f26722',
    ideology: iv(88, 60, 88, 68, 72, 64, 88, 72, 45),
    popularity: 10,
    influence: 6,
    money: 40,
    militancy: 50,
    strongRegions: ['sudeste', 'sul'],
    weakRegions: ['nordeste', 'norte'],
    priorities: ['taxes', 'regulation', 'corruption'],
    priorityPopTypes: ['business', 'tech_workers', 'middle_class', 'merchants'],
    factions: [
      faction('liberais', 'Liberais', { economy: 4 }, 0.6, 62),
      faction('conservadores', 'Conservadores', { social: 12, security: 8 }, 0.4),
    ],
    leaderName: 'Eduardo Ribeiro',
    provenance: SOURCE,
    description:
      'Registrado em 2015, defende liberalismo econômico e Estado enxuto. Partido do governador mineiro Romeu Zema.',
  },
  {
    id: 'cidadania',
    name: 'Cidadania',
    acronym: 'CIDADANIA',
    number: 23,
    logo: 'partidos/cidadania.png',
    symbol: 'dove',
    color: '#ec407a',
    ideology: iv(52, 38, 52, 48, 55, 42, 62, 60, 38),
    popularity: 6,
    influence: 9,
    money: 25,
    militancy: 30,
    strongRegions: ['sudeste'],
    weakRegions: [],
    priorities: ['education', 'corruption', 'healthcare'],
    priorityPopTypes: ['middle_class', 'civil_servants'],
    factions: direcao(),
    leaderName: 'Roberto Freire',
    provenance: SOURCE,
    description:
      'Antigo PPS, sucessor do Partido Comunista Brasileiro de 1922 e hoje de centro. Federado ao PSDB.',
  },
  {
    id: 'rede',
    name: 'Rede Sustentabilidade',
    acronym: 'REDE',
    number: 18,
    logo: 'partidos/rede.png',
    symbol: 'leaf',
    color: '#00a19a',
    ideology: iv(38, 25, 40, 30, 45, 10, 45, 62, 25),
    popularity: 6,
    influence: 5,
    money: 18,
    militancy: 50,
    strongRegions: ['norte', 'sudeste'],
    weakRegions: ['centro_oeste'],
    priorities: ['environment', 'education', 'corruption'],
    priorityPopTypes: ['students', 'middle_class', 'health_workers'],
    factions: direcao('Porta-vozes'),
    leaderName: 'Paulo Lamac (porta-voz)',
    provenance: SOURCE,
    description:
      'Criada por Marina Silva e registrada em 2015; sustentabilidade e renovação da política. Federada ao PSOL.',
  },
  {
    id: 'missao',
    name: 'Partido Missão',
    acronym: 'MISSÃO',
    number: 14,
    logo: 'partidos/missao.jpg',
    symbol: 'bolt',
    color: '#1f1f1f',
    ideology: iv(76, 50, 76, 72, 62, 60, 78, 74, 55),
    popularity: 7,
    influence: 3,
    money: 20,
    militancy: 75,
    strongRegions: ['sudeste', 'sul'],
    weakRegions: ['nordeste'],
    priorities: ['corruption', 'security', 'taxes'],
    priorityPopTypes: ['students', 'tech_workers', 'middle_class'],
    factions: direcao(),
    leaderName: 'Renan Santos',
    provenance: SOURCE,
    description:
      'Partido do Movimento Brasil Livre (MBL), registrado pelo TSE em novembro de 2025. Direita liberal com forte presença nas redes.',
  },
  {
    id: 'mobiliza',
    name: 'Mobilização Nacional',
    acronym: 'MOBILIZA',
    number: 33,
    logo: 'partidos/mobiliza.png',
    symbol: 'mountain',
    color: '#b71c1c',
    ideology: iv(55, 62, 58, 64, 60, 60, 55, 55, 55),
    popularity: 3,
    influence: 2,
    money: 12,
    militancy: 20,
    strongRegions: [],
    weakRegions: [],
    priorities: ['jobs', 'security', 'infrastructure'],
    priorityPopTypes: ['merchants', 'workers'],
    factions: direcao(),
    leaderName: 'Antonio Massarollo',
    provenance: SOURCE,
    description:
      'Antigo Partido da Mobilização Nacional (PMN), registrado em 1990. Centro-direita.',
  },
  {
    id: 'agir',
    name: 'Agir',
    acronym: 'AGIR',
    number: 36,
    logo: 'partidos/agir.png',
    symbol: 'compass',
    color: '#283593',
    ideology: iv(58, 66, 60, 68, 60, 62, 58, 52, 58),
    popularity: 3,
    influence: 2,
    money: 12,
    militancy: 20,
    strongRegions: [],
    weakRegions: [],
    priorities: ['security', 'jobs', 'taxes'],
    priorityPopTypes: ['merchants', 'retirees'],
    factions: direcao(),
    leaderName: 'Daniel Tourinho',
    provenance: SOURCE,
    description:
      'Antigo PTC e, antes, PRN — legenda que elegeu Fernando Collor em 1989. Rebatizado em 2022.',
  },
  {
    id: 'dc',
    name: 'Democracia Cristã',
    acronym: 'DC',
    number: 27,
    logo: 'partidos/dc.png',
    symbol: 'dove',
    color: '#303f9f',
    ideology: iv(58, 78, 62, 72, 58, 62, 56, 52, 62),
    popularity: 3,
    influence: 2,
    money: 10,
    militancy: 25,
    strongRegions: [],
    weakRegions: [],
    priorities: ['security', 'education', 'healthcare'],
    priorityPopTypes: ['retirees', 'workers'],
    factions: direcao(),
    leaderName: 'João Caldas',
    provenance: SOURCE,
    description:
      'Antigo PSDC, rebatizado em 2017; inspiração democrata-cristã e costumes conservadores.',
  },
  {
    id: 'prtb',
    name: 'Partido Renovador Trabalhista Brasileiro',
    acronym: 'PRTB',
    number: 28,
    logo: 'partidos/prtb.png',
    symbol: 'shield',
    color: '#263238',
    ideology: iv(70, 80, 74, 86, 60, 70, 60, 50, 74),
    popularity: 4,
    influence: 2,
    money: 12,
    militancy: 45,
    strongRegions: [],
    weakRegions: [],
    priorities: ['security', 'taxes', 'corruption'],
    priorityPopTypes: ['merchants', 'middle_class'],
    factions: direcao(),
    leaderName: 'Leonardo Araujo',
    provenance: SOURCE,
    description: 'Fundado por Levy Fidelix. Lançou Pablo Marçal à Prefeitura de São Paulo em 2024.',
  },
  {
    id: 'democrata',
    name: 'Democrata',
    acronym: 'DEMOCRATA',
    number: 35,
    logo: 'partidos/democrata.png',
    symbol: 'dove',
    color: '#1976d2',
    ideology: iv(52, 58, 54, 58, 58, 56, 54, 54, 52),
    popularity: 3,
    influence: 1,
    money: 10,
    militancy: 15,
    strongRegions: [],
    weakRegions: [],
    priorities: ['healthcare', 'jobs', 'welfare'],
    priorityPopTypes: ['workers', 'retirees'],
    factions: direcao(),
    leaderName: 'Suêd Haidar',
    provenance: SOURCE,
    description:
      'Antigo Partido da Mulher Brasileira (PMB), registrado em 2015 e rebatizado Democrata.',
  },
  {
    id: 'up',
    name: 'Unidade Popular',
    acronym: 'UP',
    number: 80,
    logo: 'partidos/up.png',
    logoBackground: '#d62828',
    symbol: 'star',
    color: '#d62828',
    ideology: iv(5, 18, 12, 15, 32, 25, 15, 38, 30),
    popularity: 3,
    influence: 1,
    money: 5,
    militancy: 70,
    strongRegions: [],
    weakRegions: [],
    priorities: ['housing', 'jobs', 'welfare'],
    priorityPopTypes: ['unemployed', 'workers', 'students'],
    factions: direcao(),
    leaderName: 'Léo Péricles',
    provenance: SOURCE,
    description:
      'Registrada em 2019; esquerda socialista revolucionária ligada a movimentos de moradia.',
  },
  {
    id: 'pstu',
    name: 'Partido Socialista dos Trabalhadores Unificado',
    acronym: 'PSTU',
    number: 16,
    logo: 'partidos/pstu.png',
    symbol: 'star',
    color: '#e53935',
    ideology: iv(4, 20, 10, 15, 30, 25, 12, 38, 28),
    popularity: 3,
    influence: 1,
    money: 4,
    militancy: 70,
    strongRegions: [],
    weakRegions: [],
    priorities: ['jobs', 'welfare', 'pensions'],
    priorityPopTypes: ['industrial_workers', 'workers', 'students'],
    factions: direcao(),
    leaderName: 'Zé Maria',
    provenance: SOURCE,
    description: 'Trotskista, fundado em 1994 a partir da Convergência Socialista.',
  },
  {
    id: 'pcb',
    name: 'Partido Comunista Brasileiro',
    acronym: 'PCB',
    number: 21,
    logo: 'partidos/pcb.png',
    symbol: 'star',
    color: '#b00020',
    ideology: iv(5, 25, 12, 20, 30, 30, 15, 35, 22),
    popularity: 3,
    influence: 1,
    money: 4,
    militancy: 65,
    strongRegions: [],
    weakRegions: [],
    priorities: ['jobs', 'welfare', 'education'],
    priorityPopTypes: ['students', 'industrial_workers', 'workers'],
    factions: direcao('Comitê Central'),
    leaderName: 'Edmilson Costa (secretário-geral)',
    provenance: SOURCE,
    description:
      'Reivindica a fundação de 1922; reorganizado nos anos 1990, depois que a maioria do partido criou o PPS.',
  },
  {
    id: 'pco',
    name: 'Partido da Causa Operária',
    acronym: 'PCO',
    number: 29,
    logo: 'partidos/pco.jpg',
    symbol: 'star',
    color: '#7f0000',
    ideology: iv(3, 35, 10, 22, 30, 35, 12, 30, 15),
    popularity: 3,
    influence: 1,
    money: 4,
    militancy: 65,
    strongRegions: [],
    weakRegions: [],
    priorities: ['jobs', 'welfare', 'housing'],
    priorityPopTypes: ['industrial_workers', 'workers'],
    factions: direcao(),
    leaderName: 'Rui Costa Pimenta',
    provenance: SOURCE,
    description: 'Trotskista, registrado em 1997.',
  },
];

/** Equivalente real de cada partido do modelo fictício (cenários e trocas de mundo). */
export const REAL_PARTY_EQUIVALENTS: Record<PartyId, PartyId> = {
  ftu: 'pt',
  alb: 'novo',
  pop: 'pl',
  udc: 'mdb',
  ren: 'rede',
  psa: 'pp',
  nes: 'psol',
  renova: 'missao',
  pfr: 'psd',
};

/** Presidente em exercício no início do jogo (Lula, PT, mandato 2023–2026). */
export const REAL_INCUMBENT_PRESIDENT = { partyId: 'pt', lastYear: 2026 } as const;
