import {
  Activity,
  Anchor,
  Anvil,
  Armchair,
  ArrowLeftRight,
  Atom,
  Award,
  BadgeCheck,
  BadgePercent,
  Ban,
  Banknote,
  BarChart3,
  Bed,
  Beef,
  Bell,
  Bird,
  BookMarked,
  BookOpen,
  Book,
  BrickWall,
  Briefcase,
  Building,
  Building2,
  Bus,
  CalendarCheck,
  Car,
  Castle,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Coffee,
  Cog,
  Coins,
  Compass,
  Construction,
  Container,
  Cookie,
  Cpu,
  Crown,
  DoorOpen,
  Download,
  Drill,
  Droplet,
  Droplets,
  Earth,
  Factory,
  FileCheck,
  FileClock,
  FilePen,
  FilePenLine,
  FileStack,
  FileText,
  FileX,
  Flag,
  Flame,
  FlaskConical,
  Footprints,
  Fuel,
  Gauge,
  Gavel,
  Gem,
  Globe,
  GraduationCap,
  HandCoins,
  HandFist,
  HandHeart,
  Handshake,
  HardHat,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  Hourglass,
  House,
  Info,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  MessageCircle,
  Mic,
  MicVocal,
  Microscope,
  Milestone,
  Milk,
  Minimize2,
  Mountain,
  Newspaper,
  PanelLeftClose,
  PanelRightClose,
  PanelRightOpen,
  PartyPopper,
  Pause,
  Percent,
  Pickaxe,
  PiggyBank,
  Pill,
  Plane,
  Play,
  PlugZap,
  Presentation,
  Radio,
  Receipt,
  RectangleHorizontal,
  Rocket,
  Rose,
  Route,
  Save,
  Scale,
  School,
  Scroll,
  ScrollText,
  Share2,
  Shield,
  Ship,
  Shirt,
  Siren,
  Smartphone,
  Smile,
  Sofa,
  SolarPanel,
  Sparkles,
  Sprout,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Swords,
  Thermometer,
  Tractor,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Tv,
  University,
  UserCheck,
  UserX,
  Users,
  Utensils,
  Vote,
  Wallet,
  Warehouse,
  Waves,
  Wheat,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Mapa nome → ícone. Os dados do motor referenciam ícones por nome (kebab-case). */
export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  anvil: Anvil,
  armchair: Armchair,
  'arrow-left-right': ArrowLeftRight,
  atom: Atom,
  award: Award,
  'badge-check': BadgeCheck,
  'badge-percent': BadgePercent,
  ban: Ban,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bed: Bed,
  beef: Beef,
  bell: Bell,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  book: Book,
  'brick-wall': BrickWall,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  bus: Bus,
  'calendar-check': CalendarCheck,
  car: Car,
  castle: Castle,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  'circle-x': CircleX,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  coffee: Coffee,
  cog: Cog,
  coins: Coins,
  compass: Compass,
  construction: Construction,
  container: Container,
  cookie: Cookie,
  cpu: Cpu,
  crown: Crown,
  'door-open': DoorOpen,
  download: Download,
  drill: Drill,
  droplet: Droplet,
  droplets: Droplets,
  earth: Earth,
  factory: Factory,
  'file-check': FileCheck,
  'file-clock': FileClock,
  'file-pen': FilePen,
  'file-signature': FilePenLine,
  'file-stack': FileStack,
  'file-text': FileText,
  'file-x': FileX,
  flag: Flag,
  flame: Flame,
  'flask-conical': FlaskConical,
  footprints: Footprints,
  fuel: Fuel,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'hand-fist': HandFist,
  'hand-heart': HandHeart,
  handshake: Handshake,
  'hard-hat': HardHat,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  home: Home,
  hospital: Hospital,
  hourglass: Hourglass,
  house: House,
  info: Info,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  lock: Lock,
  map: Map,
  'map-pin': MapPin,
  'maximize-2': Maximize2,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  mic: Mic,
  'mic-vocal': MicVocal,
  microscope: Microscope,
  milestone: Milestone,
  milk: Milk,
  'minimize-2': Minimize2,
  mountain: Mountain,
  newspaper: Newspaper,
  'panel-left-close': PanelLeftClose,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  'party-popper': PartyPopper,
  pause: Pause,
  percent: Percent,
  pickaxe: Pickaxe,
  'piggy-bank': PiggyBank,
  pill: Pill,
  plane: Plane,
  play: Play,
  'plug-zap': PlugZap,
  presentation: Presentation,
  radio: Radio,
  receipt: Receipt,
  'rectangle-horizontal': RectangleHorizontal,
  rocket: Rocket,
  rose: Rose,
  route: Route,
  save: Save,
  scale: Scale,
  school: School,
  scroll: Scroll,
  'scroll-text': ScrollText,
  'share-2': Share2,
  shield: Shield,
  ship: Ship,
  shirt: Shirt,
  siren: Siren,
  smartphone: Smartphone,
  smile: Smile,
  sofa: Sofa,
  'solar-panel': SolarPanel,
  sparkles: Sparkles,
  sprout: Sprout,
  stamp: Stamp,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  swords: Swords,
  thermometer: Thermometer,
  tractor: Tractor,
  'tree-pine': TreePine,
  trees: Trees,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  truck: Truck,
  tv: Tv,
  university: University,
  'user-check': UserCheck,
  'user-x': UserX,
  users: Users,
  utensils: Utensils,
  vote: Vote,
  wallet: Wallet,
  warehouse: Warehouse,
  waves: Waves,
  wheat: Wheat,
  wind: Wind,
  x: X,
  zap: Zap,
  // Símbolos de partido
  gear: Cog,
  dove: Bird,
  torch: Flame,
  tree: TreePine,
  bolt: Zap,
};

export interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 18, className, strokeWidth = 2.1 }: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} aria-hidden />;
}
