import { deepClone } from '../core/clone';
import type { InterestGroup, InterestGroupId } from './types';

type Seed = Omit<InterestGroup, 'approval'>;

/** Grupos de interesse do cenário padrão (nomes de lideranças fictícios). */
export const INTEREST_GROUP_SEEDS: Seed[] = [
  {
    id: 'business',
    name: 'Empresários',
    icon: 'briefcase',
    size: 0.03,
    influence: 80,
    power: 70,
    priorities: ['taxes', 'regulation', 'credit'],
    ideology: {
      economy: 82,
      social: 55,
      fiscal: 85,
      security: 65,
      federalism: 60,
      environment: 68,
      trade: 72,
      institutions: 60,
      foreign: 45,
    },
    relatedPopTypes: ['business'],
    preferredLaws: {
      taxation: 'tax_low',
      labor: 'labor_flexible',
      administration: 'adm_lean',
      infrastructure: 'infra_concessions',
      pensions: 'pen_reform',
      banking: 'bank_liberal',
      central_bank: 'cb_independent',
      economic_system: 'econ_laissez_faire',
      minimum_wage: 'mw_low',
      resources: 'res_concession',
    },
    leaderName: 'Confederação Nacional do Empresariado',
  },
  {
    id: 'workers',
    name: 'Trabalhadores',
    icon: 'hard-hat',
    size: 0.28,
    influence: 50,
    power: 55,
    priorities: ['jobs', 'inflation', 'healthcare'],
    ideology: {
      economy: 35,
      social: 55,
      fiscal: 40,
      security: 60,
      federalism: 45,
      environment: 55,
      trade: 40,
      institutions: 50,
      foreign: 55,
    },
    relatedPopTypes: ['workers', 'industrial_workers'],
    preferredLaws: {
      labor: 'labor_protective',
      infrastructure: 'infra_big_plan',
      taxation: 'tax_progressive',
      minimum_wage: 'mw_high',
      welfare: 'wel_expanded',
      unions: 'unions_free',
    },
    leaderName: 'Movimento dos Trabalhadores Urbanos',
  },
  {
    id: 'agribusiness',
    name: 'Agronegócio',
    icon: 'wheat',
    size: 0.07,
    influence: 75,
    power: 72,
    priorities: ['agriculture', 'credit', 'infrastructure'],
    ideology: {
      economy: 68,
      social: 70,
      fiscal: 72,
      security: 72,
      federalism: 78,
      environment: 90,
      trade: 80,
      institutions: 65,
      foreign: 55,
    },
    relatedPopTypes: ['farmers'],
    preferredLaws: {
      environment: 'env_flexible',
      trade: 'trade_open',
      federalism: 'fed_decentralized',
      land: 'land_latifundio',
      taxation: 'tax_low',
      unions: 'unions_restricted',
    },
    leaderName: 'Frente Nacional do Agro',
  },
  {
    id: 'unions',
    name: 'Sindicatos',
    icon: 'megaphone',
    size: 0.1,
    influence: 55,
    power: 60,
    priorities: ['jobs', 'pensions', 'welfare'],
    ideology: {
      economy: 18,
      social: 40,
      fiscal: 25,
      security: 40,
      federalism: 40,
      environment: 45,
      trade: 25,
      institutions: 45,
      foreign: 50,
    },
    relatedPopTypes: ['industrial_workers', 'civil_servants', 'workers'],
    preferredLaws: {
      labor: 'labor_protective',
      pensions: 'pen_expanded',
      trade: 'trade_protectionist',
      minimum_wage: 'mw_high',
      unions: 'unions_free',
      welfare: 'wel_expanded',
      economic_system: 'econ_developmental',
    },
    leaderName: 'Central Única Sindical',
  },
  {
    id: 'civil_servants',
    name: 'Servidores públicos',
    icon: 'landmark',
    size: 0.05,
    influence: 60,
    power: 58,
    priorities: ['pensions', 'education', 'healthcare'],
    ideology: {
      economy: 28,
      social: 42,
      fiscal: 32,
      security: 48,
      federalism: 40,
      environment: 38,
      trade: 45,
      institutions: 38,
      foreign: 45,
    },
    relatedPopTypes: ['civil_servants'],
    preferredLaws: {
      administration: 'adm_expanded',
      pensions: 'pen_current',
      education: 'edu_fulltime',
      unions: 'unions_free',
    },
    leaderName: 'Fórum dos Servidores',
  },
  {
    id: 'youth',
    name: 'Juventude',
    icon: 'graduation-cap',
    size: 0.12,
    influence: 35,
    power: 40,
    priorities: ['education', 'jobs', 'environment'],
    ideology: {
      economy: 40,
      social: 28,
      fiscal: 45,
      security: 35,
      federalism: 50,
      environment: 25,
      trade: 55,
      institutions: 60,
      foreign: 35,
    },
    relatedPopTypes: ['students'],
    preferredLaws: {
      education: 'edu_fulltime',
      environment: 'env_strict',
      institutions: 'inst_transparency',
      welfare: 'wel_expanded',
      science: 'sci_innovation_state',
    },
    leaderName: 'União Nacional Estudantil',
  },
  {
    id: 'retirees',
    name: 'Aposentados',
    icon: 'armchair',
    size: 0.15,
    influence: 45,
    power: 50,
    priorities: ['pensions', 'healthcare', 'inflation'],
    ideology: {
      economy: 45,
      social: 70,
      fiscal: 50,
      security: 72,
      federalism: 45,
      environment: 55,
      trade: 45,
      institutions: 45,
      foreign: 60,
    },
    relatedPopTypes: ['retirees'],
    preferredLaws: {
      pensions: 'pen_expanded',
      healthcare: 'health_expanded',
      security: 'sec_punitive',
      central_bank: 'cb_independent',
    },
    leaderName: 'Confederação dos Aposentados',
  },
  {
    id: 'social_movements',
    name: 'Movimentos sociais',
    icon: 'heart-handshake',
    size: 0.06,
    influence: 45,
    power: 55,
    priorities: ['welfare', 'housing', 'environment'],
    ideology: {
      economy: 15,
      social: 18,
      fiscal: 20,
      security: 20,
      federalism: 45,
      environment: 20,
      trade: 35,
      institutions: 75,
      foreign: 30,
    },
    relatedPopTypes: ['unemployed', 'students'],
    preferredLaws: {
      taxation: 'tax_wealth',
      institutions: 'inst_participatory',
      security: 'sec_preventive',
      land: 'land_reform',
      welfare: 'wel_expanded',
      environment: 'env_strict',
      economic_system: 'econ_cooperative',
      minimum_wage: 'mw_high',
    },
    leaderName: 'Articulação dos Movimentos Populares',
  },
  {
    id: 'industry',
    name: 'Setor industrial',
    icon: 'factory',
    size: 0.04,
    influence: 70,
    power: 65,
    priorities: ['jobs', 'credit', 'taxes'],
    ideology: {
      economy: 60,
      social: 52,
      fiscal: 70,
      security: 60,
      federalism: 50,
      environment: 65,
      trade: 25,
      institutions: 50,
      foreign: 65,
    },
    relatedPopTypes: ['industrial_workers', 'business'],
    preferredLaws: {
      trade: 'trade_protectionist',
      infrastructure: 'infra_ppp',
      education: 'edu_tech',
      industrial_policy: 'ind_bndes',
      economic_system: 'econ_developmental',
      banking: 'bank_public',
    },
    leaderName: 'Federação das Indústrias',
  },
  {
    id: 'tech',
    name: 'Setor tecnológico',
    icon: 'cpu',
    size: 0.02,
    influence: 50,
    power: 45,
    priorities: ['technology', 'regulation', 'education'],
    ideology: {
      economy: 68,
      social: 35,
      fiscal: 62,
      security: 45,
      federalism: 58,
      environment: 35,
      trade: 80,
      institutions: 72,
      foreign: 30,
    },
    relatedPopTypes: ['tech_workers'],
    preferredLaws: {
      administration: 'adm_digital',
      environment: 'env_green_economy',
      trade: 'trade_open',
      science: 'sci_innovation_state',
      education: 'edu_tech',
    },
    leaderName: 'Associação Brasileira de Startups',
  },
  {
    id: 'commerce',
    name: 'Comércio',
    icon: 'store',
    size: 0.07,
    influence: 55,
    power: 55,
    priorities: ['taxes', 'security', 'credit'],
    ideology: {
      economy: 70,
      social: 60,
      fiscal: 78,
      security: 72,
      federalism: 55,
      environment: 58,
      trade: 55,
      institutions: 55,
      foreign: 52,
    },
    relatedPopTypes: ['merchants'],
    preferredLaws: {
      taxation: 'tax_low',
      security: 'sec_punitive',
      administration: 'adm_lean',
      trade: 'trade_open',
      central_bank: 'cb_independent',
      minimum_wage: 'mw_low',
    },
    leaderName: 'Câmara Nacional do Comércio',
  },
];

export function initInterestGroups(): Record<InterestGroupId, InterestGroup> {
  const out = {} as Record<InterestGroupId, InterestGroup>;
  for (const seed of INTEREST_GROUP_SEEDS) out[seed.id] = { ...deepClone(seed), approval: 50 };
  return out;
}
