import type { IdeologyVector } from '../ideology/axes';
import type { IssueWeights } from '../ideology/issues';
import type { MediaChannel } from '../media/channels';

export const POP_TYPE_IDS = [
  'workers',
  'industrial_workers',
  'farmers',
  'business',
  'merchants',
  'middle_class',
  'civil_servants',
  'health_workers',
  'tech_workers',
  'students',
  'retirees',
  'unemployed',
] as const;
export type PopTypeId = (typeof POP_TYPE_IDS)[number];

/** Fatores regionais que alteram a composição demográfica de cada estado. */
export type RegionalFactor =
  'urbanization' | 'agro' | 'industry' | 'publicSector' | 'tech' | 'income' | 'unemployment';

/**
 * Arquétipo de grupo de eleitores. Os valores ideológicos são PARÂMETROS DO MODELO
 * do cenário fictício, não afirmações sobre grupos sociais reais.
 */
export interface PopTypeDefinition {
  id: PopTypeId;
  name: string;
  plural: string;
  icon: string;
  color: string;
  /** Participação nacional no eleitorado (soma = 1). */
  baseShare: number;
  /** Coeficientes de variação regional (positivo = mais comum onde o fator é alto). */
  regional: Partial<Record<RegionalFactor, number>>;
  income: number;
  education: number;
  avgAge: number;
  ideology: IdeologyVector;
  priorities: IssueWeights;
  turnout: number;
  media: Record<MediaChannel, number>;
  /** Engajamento político (0..1): reduz indecisão. */
  engagement: number;
  /** Quão persuadível é o grupo (0..1). */
  volatility: number;
}

export const POP_TYPES: Record<PopTypeId, PopTypeDefinition> = {
  workers: {
    id: 'workers',
    name: 'Trabalhador',
    plural: 'Trabalhadores',
    icon: 'hard-hat',
    color: '#e76f51',
    baseShare: 0.2,
    regional: { urbanization: 0.6, unemployment: 0.3 },
    income: 2200,
    education: 45,
    avgAge: 38,
    ideology: {
      economy: 40,
      social: 58,
      fiscal: 45,
      security: 62,
      federalism: 45,
      environment: 52,
      trade: 42,
      institutions: 50,
      foreign: 55,
    },
    priorities: {
      jobs: 82,
      healthcare: 64,
      security: 71,
      taxes: 58,
      education: 49,
      inflation: 70,
      transport: 55,
      housing: 50,
    },
    turnout: 0.78,
    media: {
      tv: 0.8,
      radio: 0.5,
      internet: 0.6,
      social: 0.75,
      newspaper: 0.15,
      podcast: 0.2,
      influencer: 0.45,
      outdoor: 0.6,
      events: 0.3,
    },
    engagement: 0.4,
    volatility: 0.6,
  },
  industrial_workers: {
    id: 'industrial_workers',
    name: 'Operário',
    plural: 'Trabalhadores industriais',
    icon: 'factory',
    color: '#d62828',
    baseShare: 0.08,
    regional: { industry: 2.2, urbanization: 0.4 },
    income: 2800,
    education: 45,
    avgAge: 40,
    ideology: {
      economy: 35,
      social: 55,
      fiscal: 45,
      security: 60,
      federalism: 45,
      environment: 60,
      trade: 25,
      institutions: 50,
      foreign: 60,
    },
    priorities: { jobs: 85, inflation: 65, healthcare: 60, security: 60, pensions: 45, taxes: 50 },
    turnout: 0.8,
    media: {
      tv: 0.8,
      radio: 0.55,
      internet: 0.55,
      social: 0.7,
      newspaper: 0.2,
      podcast: 0.2,
      influencer: 0.35,
      outdoor: 0.6,
      events: 0.35,
    },
    engagement: 0.5,
    volatility: 0.5,
  },
  farmers: {
    id: 'farmers',
    name: 'Agricultor',
    plural: 'Agricultores',
    icon: 'tractor',
    color: '#6a994e',
    baseShare: 0.07,
    regional: { agro: 2.6, urbanization: -2.2 },
    income: 2500,
    education: 35,
    avgAge: 47,
    ideology: {
      economy: 60,
      social: 72,
      fiscal: 65,
      security: 70,
      federalism: 70,
      environment: 82,
      trade: 60,
      institutions: 65,
      foreign: 60,
    },
    priorities: {
      agriculture: 90,
      credit: 75,
      infrastructure: 70,
      security: 65,
      taxes: 60,
      regulation: 55,
    },
    turnout: 0.82,
    media: {
      tv: 0.7,
      radio: 0.85,
      internet: 0.4,
      social: 0.55,
      newspaper: 0.2,
      podcast: 0.15,
      influencer: 0.25,
      outdoor: 0.4,
      events: 0.5,
    },
    engagement: 0.55,
    volatility: 0.45,
  },
  business: {
    id: 'business',
    name: 'Empresário',
    plural: 'Empresários',
    icon: 'briefcase',
    color: '#264653',
    baseShare: 0.03,
    regional: { income: 1.2, industry: 0.6 },
    income: 15000,
    education: 70,
    avgAge: 48,
    ideology: {
      economy: 80,
      social: 55,
      fiscal: 80,
      security: 65,
      federalism: 60,
      environment: 65,
      trade: 70,
      institutions: 60,
      foreign: 45,
    },
    priorities: {
      taxes: 88,
      regulation: 80,
      credit: 72,
      infrastructure: 65,
      security: 60,
      inflation: 55,
    },
    turnout: 0.85,
    media: {
      tv: 0.6,
      radio: 0.4,
      internet: 0.8,
      social: 0.6,
      newspaper: 0.65,
      podcast: 0.45,
      influencer: 0.25,
      outdoor: 0.3,
      events: 0.45,
    },
    engagement: 0.75,
    volatility: 0.4,
  },
  merchants: {
    id: 'merchants',
    name: 'Comerciante',
    plural: 'Comerciantes',
    icon: 'store',
    color: '#f4a261',
    baseShare: 0.07,
    regional: { urbanization: 0.3 },
    income: 4500,
    education: 50,
    avgAge: 45,
    ideology: {
      economy: 68,
      social: 60,
      fiscal: 75,
      security: 70,
      federalism: 55,
      environment: 58,
      trade: 55,
      institutions: 55,
      foreign: 52,
    },
    priorities: { taxes: 80, security: 78, credit: 65, inflation: 70, regulation: 60, jobs: 45 },
    turnout: 0.82,
    media: {
      tv: 0.75,
      radio: 0.6,
      internet: 0.6,
      social: 0.7,
      newspaper: 0.35,
      podcast: 0.2,
      influencer: 0.35,
      outdoor: 0.55,
      events: 0.35,
    },
    engagement: 0.55,
    volatility: 0.5,
  },
  middle_class: {
    id: 'middle_class',
    name: 'Classe média',
    plural: 'Classe média',
    icon: 'house',
    color: '#2a9d8f',
    baseShare: 0.13,
    regional: { income: 1.4, urbanization: 0.8 },
    income: 7000,
    education: 70,
    avgAge: 42,
    ideology: {
      economy: 55,
      social: 48,
      fiscal: 62,
      security: 58,
      federalism: 50,
      environment: 45,
      trade: 55,
      institutions: 52,
      foreign: 45,
    },
    priorities: {
      education: 75,
      healthcare: 70,
      taxes: 68,
      security: 72,
      corruption: 70,
      inflation: 60,
    },
    turnout: 0.84,
    media: {
      tv: 0.65,
      radio: 0.35,
      internet: 0.85,
      social: 0.8,
      newspaper: 0.45,
      podcast: 0.55,
      influencer: 0.45,
      outdoor: 0.35,
      events: 0.25,
    },
    engagement: 0.6,
    volatility: 0.55,
  },
  civil_servants: {
    id: 'civil_servants',
    name: 'Servidor público',
    plural: 'Servidores públicos',
    icon: 'landmark',
    color: '#457b9d',
    baseShare: 0.05,
    regional: { publicSector: 2.6 },
    income: 6500,
    education: 75,
    avgAge: 44,
    ideology: {
      economy: 30,
      social: 42,
      fiscal: 35,
      security: 48,
      federalism: 40,
      environment: 38,
      trade: 45,
      institutions: 38,
      foreign: 45,
    },
    priorities: {
      pensions: 70,
      education: 65,
      healthcare: 65,
      corruption: 55,
      jobs: 40,
      inflation: 55,
    },
    turnout: 0.88,
    media: {
      tv: 0.6,
      radio: 0.4,
      internet: 0.85,
      social: 0.7,
      newspaper: 0.55,
      podcast: 0.45,
      influencer: 0.3,
      outdoor: 0.3,
      events: 0.3,
    },
    engagement: 0.7,
    volatility: 0.4,
  },
  health_workers: {
    id: 'health_workers',
    name: 'Profissional de saúde',
    plural: 'Profissionais de saúde',
    icon: 'stethoscope',
    color: '#e63946',
    baseShare: 0.03,
    regional: { urbanization: 0.7, income: 0.4 },
    income: 5500,
    education: 78,
    avgAge: 39,
    ideology: {
      economy: 38,
      social: 40,
      fiscal: 42,
      security: 45,
      federalism: 45,
      environment: 35,
      trade: 48,
      institutions: 45,
      foreign: 40,
    },
    priorities: {
      healthcare: 92,
      education: 60,
      jobs: 50,
      security: 50,
      pensions: 45,
      corruption: 50,
    },
    turnout: 0.85,
    media: {
      tv: 0.55,
      radio: 0.3,
      internet: 0.85,
      social: 0.8,
      newspaper: 0.45,
      podcast: 0.5,
      influencer: 0.4,
      outdoor: 0.3,
      events: 0.25,
    },
    engagement: 0.6,
    volatility: 0.5,
  },
  tech_workers: {
    id: 'tech_workers',
    name: 'Profissional de tecnologia',
    plural: 'Profissionais de tecnologia',
    icon: 'laptop',
    color: '#8338ec',
    baseShare: 0.02,
    regional: { tech: 3, income: 1 },
    income: 9000,
    education: 85,
    avgAge: 31,
    ideology: {
      economy: 62,
      social: 35,
      fiscal: 60,
      security: 45,
      federalism: 58,
      environment: 40,
      trade: 75,
      institutions: 62,
      foreign: 35,
    },
    priorities: {
      technology: 85,
      education: 65,
      taxes: 60,
      regulation: 60,
      security: 55,
      corruption: 55,
    },
    turnout: 0.8,
    media: {
      tv: 0.3,
      radio: 0.15,
      internet: 0.95,
      social: 0.85,
      newspaper: 0.4,
      podcast: 0.8,
      influencer: 0.55,
      outdoor: 0.25,
      events: 0.2,
    },
    engagement: 0.6,
    volatility: 0.6,
  },
  students: {
    id: 'students',
    name: 'Estudante',
    plural: 'Estudantes',
    icon: 'graduation-cap',
    color: '#ffb703',
    baseShare: 0.07,
    regional: { urbanization: 0.5, tech: 0.4 },
    income: 1200,
    education: 65,
    avgAge: 21,
    ideology: {
      economy: 38,
      social: 30,
      fiscal: 45,
      security: 38,
      federalism: 48,
      environment: 28,
      trade: 50,
      institutions: 50,
      foreign: 38,
    },
    priorities: {
      education: 92,
      jobs: 70,
      environment: 60,
      transport: 55,
      technology: 50,
      housing: 45,
    },
    turnout: 0.7,
    media: {
      tv: 0.35,
      radio: 0.15,
      internet: 0.95,
      social: 0.95,
      newspaper: 0.2,
      podcast: 0.65,
      influencer: 0.8,
      outdoor: 0.3,
      events: 0.45,
    },
    engagement: 0.45,
    volatility: 0.75,
  },
  retirees: {
    id: 'retirees',
    name: 'Aposentado',
    plural: 'Aposentados',
    icon: 'armchair',
    color: '#9d8189',
    baseShare: 0.15,
    regional: { income: 0.3 },
    income: 2600,
    education: 40,
    avgAge: 69,
    ideology: {
      economy: 45,
      social: 70,
      fiscal: 50,
      security: 70,
      federalism: 45,
      environment: 55,
      trade: 45,
      institutions: 45,
      foreign: 60,
    },
    priorities: { pensions: 92, healthcare: 88, inflation: 75, security: 65, corruption: 50 },
    turnout: 0.8,
    media: {
      tv: 0.95,
      radio: 0.75,
      internet: 0.35,
      social: 0.45,
      newspaper: 0.45,
      podcast: 0.1,
      influencer: 0.1,
      outdoor: 0.4,
      events: 0.3,
    },
    engagement: 0.65,
    volatility: 0.35,
  },
  unemployed: {
    id: 'unemployed',
    name: 'Desempregado',
    plural: 'Desempregados',
    icon: 'user-x',
    color: '#6c757d',
    baseShare: 0.1,
    regional: { unemployment: 1.8, income: -0.6 },
    income: 600,
    education: 38,
    avgAge: 33,
    ideology: {
      economy: 30,
      social: 55,
      fiscal: 40,
      security: 58,
      federalism: 45,
      environment: 55,
      trade: 40,
      institutions: 48,
      foreign: 55,
    },
    priorities: { jobs: 95, welfare: 80, inflation: 72, healthcare: 65, housing: 55, security: 55 },
    turnout: 0.68,
    media: {
      tv: 0.8,
      radio: 0.5,
      internet: 0.6,
      social: 0.8,
      newspaper: 0.1,
      podcast: 0.2,
      influencer: 0.5,
      outdoor: 0.55,
      events: 0.3,
    },
    engagement: 0.3,
    volatility: 0.7,
  },
};

export const POP_TYPE_LIST: PopTypeDefinition[] = POP_TYPE_IDS.map((id) => POP_TYPES[id]);
