import type { LawCategoryDefinition, LawOptionDefinition } from './types';

type Opt = Omit<LawOptionDefinition, 'economy' | 'budget' | 'pops' | 'groups' | 'issues'> &
  Partial<Pick<LawOptionDefinition, 'economy' | 'budget' | 'pops' | 'groups' | 'issues'>>;

function opt(o: Opt): LawOptionDefinition {
  return { economy: {}, budget: {}, pops: {}, groups: {}, issues: {}, ...o };
}

type Cat = Omit<LawCategoryDefinition, 'constitutional'>;

/** `constitutional` decorre do instrumento: só a PEC exige 3/5 em dois turnos. */
function category(c: Cat): LawCategoryDefinition {
  return { ...c, constitutional: c.instrument === 'pec' };
}

/** Renda básica universal: o mesmo valor (R$/mês por pessoa) para todos os tipos de Pop. */
const UNIVERSAL_INCOME = 600;

/**
 * Leis do cenário, em três ramos (Estado, Economia, Sociedade), como no Victoria 3.
 * Os efeitos são do MODELO SIMPLIFICADO do jogo — não são previsões nem afirmações sobre o
 * mundo real. Toda opção não padrão tem ganhadores e perdedores; nenhuma domina as demais.
 *
 * Convenções:
 * - todas as opções de uma categoria usam os MESMOS eixos ideológicos (a afinidade dos
 *   partidos compara opções em pé de igualdade);
 * - `modifiers` é o efeito no motor industrial; `economy` legado fica só com confiança e
 *   inflação monetária nas opções que têm `modifiers` (sem contar em dobro);
 * - opções padrão não têm efeitos em Pops/grupos (são a linha de base do jogo).
 */
export const LAW_CATEGORIES: LawCategoryDefinition[] = [
  // ===========================================================================
  // ESTADO
  // ===========================================================================
  category({
    id: 'regime',
    branch: 'estado',
    name: 'Regime de governo',
    icon: 'flag',
    instrument: 'pec',
    levels: ['federal'],
    description:
      'Sistema de governo: quem chefia o Executivo e como o governo se sustenta no Congresso.',
    defaultOptionId: 'reg_presidential',
    options: [
      opt({
        id: 'reg_presidential',
        name: 'Presidencialismo',
        description:
          'O presidente eleito chefia o Estado e o governo e governa com uma coalizão no Congresso.',
        ideology: { institutions: 45, security: 60, federalism: 50 },
        special: 'presidential',
        tags: ['democratic'],
        politicalCost: 35,
        implementationMonths: 12,
      }),
      opt({
        id: 'reg_semi_presidential',
        name: 'Semipresidencialismo',
        description:
          'O presidente eleito divide o poder com um primeiro-ministro que depende da maioria na Câmara.',
        ideology: { institutions: 62, security: 52, federalism: 55 },
        economy: { confidence: 3 },
        pops: { business: 3, middle_class: 3, workers: -2, unemployed: -2 },
        groups: { business: 5, commerce: 3, social_movements: -6, unions: -4 },
        issues: { corruption: 2 },
        caucuses: { ruralista: 3, empresarial: 4, evangelica: 2, sindical: -3 },
        plebiscite: true,
        special: 'semi_presidential',
        legitimacyShock: 2,
        tags: ['democratic'],
        politicalCost: 70,
        implementationMonths: 12,
      }),
      opt({
        id: 'reg_parliamentary',
        name: 'Parlamentarismo',
        description:
          'Um primeiro-ministro escolhido pela maioria da Câmara chefia o governo; o gabinete cai com moção de desconfiança.',
        ideology: { institutions: 72, security: 50, federalism: 58 },
        economy: { confidence: 2 },
        pops: { business: 4, middle_class: 4, workers: -3, retirees: -3, unemployed: -3 },
        groups: { business: 6, commerce: 4, tech: 3, social_movements: -8, unions: -5, retirees: -3 },
        issues: { corruption: 3 },
        caucuses: { ruralista: 5, empresarial: 5, evangelica: 3, sindical: -4 },
        plebiscite: true,
        special: 'parliamentary',
        legitimacyShock: 2,
        tags: ['democratic'],
        politicalCost: 75,
        implementationMonths: 12,
      }),
      opt({
        id: 'reg_one_party',
        name: 'Partido único',
        description:
          'O partido do governo assume o controle do Congresso e as eleições para o Executivo são suspensas.',
        ideology: { institutions: 0, security: 95, federalism: 5 },
        budget: { security: 0.15 },
        economy: { confidence: -15 },
        pops: {
          retirees: 3,
          civil_servants: 2,
          business: -10,
          middle_class: -12,
          students: -15,
          tech_workers: -10,
          merchants: -6,
          health_workers: -5,
          workers: -4,
        },
        groups: {
          civil_servants: 5,
          retirees: 2,
          youth: -35,
          social_movements: -35,
          tech: -25,
          business: -25,
          unions: -20,
          commerce: -15,
        },
        issues: { corruption: -12, security: 4 },
        caucuses: {
          seguranca: 4,
          ruralista: -5,
          evangelica: -10,
          sindical: -8,
          empresarial: -10,
          ambientalista: -8,
        },
        plebiscite: true,
        special: 'one_party',
        legitimacyShock: -45,
        tags: ['authoritarian'],
        politicalCost: 100,
        implementationMonths: 6,
      }),
    ],
  }),
  category({
    id: 'electoral_system',
    branch: 'estado',
    name: 'Sistema eleitoral',
    icon: 'vote',
    instrument: 'pec',
    levels: ['federal'],
    description: 'Como deputados e vereadores são eleitos.',
    defaultOptionId: 'elec_open_list',
    options: [
      opt({
        id: 'elec_open_list',
        name: 'Lista aberta',
        description: 'O eleitor vota no candidato; as cadeiras saem do total de votos do partido.',
        ideology: { institutions: 55, federalism: 50 },
        politicalCost: 20,
        implementationMonths: 6,
      }),
      opt({
        id: 'elec_closed_list',
        name: 'Lista fechada',
        description: 'O eleitor vota no partido, que define a ordem dos eleitos.',
        ideology: { institutions: 30, federalism: 45 },
        economy: { confidence: -1 },
        pops: { civil_servants: 2, students: 2, middle_class: -4, merchants: -2 },
        groups: { social_movements: 6, unions: 3, business: -4, commerce: -2 },
        caucuses: { sindical: 3, ambientalista: 2, evangelica: -5, ruralista: -3, seguranca: -3 },
        politicalCost: 35,
        implementationMonths: 12,
      }),
      opt({
        id: 'elec_district',
        name: 'Voto distrital misto',
        description: 'Metade das cadeiras por distritos, metade por lista partidária.',
        ideology: { institutions: 72, federalism: 68 },
        economy: { confidence: 1 },
        pops: { middle_class: 3, merchants: 2, farmers: 2, students: -3, unemployed: -2 },
        groups: { business: 4, commerce: 4, agribusiness: 3, social_movements: -6, youth: -3 },
        caucuses: { ruralista: 4, empresarial: 2, seguranca: 2, sindical: -3, ambientalista: -4 },
        politicalCost: 40,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'federalism',
    branch: 'estado',
    name: 'Pacto federativo',
    icon: 'map',
    instrument: 'pec',
    levels: ['federal'],
    description: 'Divisão de recursos e competências entre União, estados e municípios.',
    defaultOptionId: 'fed_current',
    options: [
      opt({
        id: 'fed_current',
        name: 'Divisão atual',
        description: 'Repartição de receitas e competências vigente.',
        ideology: { federalism: 45, institutions: 50 },
        politicalCost: 20,
        implementationMonths: 6,
      }),
      opt({
        id: 'fed_decentralized',
        name: 'Descentralização',
        description: 'Mais recursos e poder para estados e municípios.',
        ideology: { federalism: 85, institutions: 70 },
        economy: { revenue: -0.04 },
        pops: { farmers: 3, merchants: 3, civil_servants: 2, unemployed: -3 },
        groups: { agribusiness: 4, commerce: 4, social_movements: -5, unions: -3 },
        issues: { infrastructure: 5 },
        caucuses: { ruralista: 6, empresarial: 3, sindical: -3 },
        politicalCost: 35,
        implementationMonths: 12,
      }),
      opt({
        id: 'fed_centralized',
        name: 'Centralização',
        description: 'A União coordena as políticas públicas e concentra os recursos.',
        ideology: { federalism: 15, institutions: 30 },
        economy: { revenue: 0.03 },
        pops: { civil_servants: 3, unemployed: 2, farmers: -3, merchants: -2 },
        groups: { civil_servants: 4, unions: 2, agribusiness: -4, commerce: -2 },
        caucuses: { sindical: 2, ruralista: -5 },
        politicalCost: 35,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'institutions',
    branch: 'estado',
    name: 'Instituições',
    icon: 'landmark',
    instrument: 'pec',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Transparência, controles sobre o governo e participação popular.',
    defaultOptionId: 'inst_current',
    options: [
      opt({
        id: 'inst_current',
        name: 'Regras atuais',
        description: 'Controles e órgãos de fiscalização vigentes.',
        ideology: { institutions: 50, security: 60, federalism: 50 },
        politicalCost: 20,
        implementationMonths: 4,
      }),
      opt({
        id: 'inst_transparency',
        name: 'Transparência total',
        description: 'Gastos públicos abertos em tempo real e controle externo forte.',
        ideology: { institutions: 75, security: 50, federalism: 55 },
        budget: { administration: 0.02 },
        economy: { confidence: 4 },
        pops: { middle_class: 5, tech_workers: 4, students: 3, civil_servants: -3 },
        groups: { tech: 4, youth: 4, civil_servants: -5 },
        issues: { corruption: 14 },
        caucuses: { ambientalista: 3, empresarial: 2, ruralista: -2 },
        legitimacyShock: 4,
        tags: ['democratic'],
        politicalCost: 25,
        implementationMonths: 8,
      }),
      opt({
        id: 'inst_strong_executive',
        name: 'Executivo forte',
        description:
          'Mais poderes ao Executivo: decretos com força de lei e controles externos mais fracos.',
        ideology: { institutions: 10, security: 75, federalism: 25 },
        economy: { confidence: -4 },
        pops: { retirees: 3, merchants: 2, students: -6, middle_class: -3 },
        groups: { business: 3, commerce: 2, social_movements: -10, youth: -8 },
        issues: { corruption: -6, security: 3 },
        caucuses: { seguranca: 6, evangelica: 2, sindical: -4, ambientalista: -5, empresarial: -2 },
        legitimacyShock: -8,
        tags: ['authoritarian'],
        politicalCost: 50,
        implementationMonths: 6,
      }),
      opt({
        id: 'inst_participatory',
        name: 'Democracia participativa',
        description: 'Conselhos populares e orçamento participativo.',
        ideology: { institutions: 85, security: 40, federalism: 65 },
        budget: { administration: 0.03 },
        pops: { students: 5, workers: 3, business: -3 },
        groups: { social_movements: 14, youth: 6, business: -5 },
        issues: { corruption: 4 },
        caucuses: { sindical: 4, ambientalista: 4, empresarial: -4, ruralista: -4, evangelica: -2 },
        legitimacyShock: 3,
        tags: ['democratic', 'progressive'],
        politicalCost: 30,
        implementationMonths: 10,
      }),
    ],
  }),
  category({
    id: 'central_bank',
    branch: 'estado',
    name: 'Banco Central',
    icon: 'badge-percent',
    instrument: 'plp',
    levels: ['federal'],
    description: 'Quem define a taxa de juros e com qual mandato.',
    defaultOptionId: 'cb_independent',
    options: [
      opt({
        id: 'cb_independent',
        name: 'Banco Central independente',
        description:
          'Diretoria com mandato fixo persegue a meta de inflação, sem interferência do governo.',
        ideology: { economy: 62, institutions: 68 },
        modifiers: { centralBank: 'independent' },
        tags: ['liberal'],
        politicalCost: 20,
        implementationMonths: 6,
      }),
      opt({
        id: 'cb_dual_mandate',
        name: 'Mandato duplo',
        description: 'O Banco Central persegue a meta de inflação e também o pleno emprego.',
        ideology: { economy: 42, institutions: 58 },
        modifiers: { centralBank: 'dual' },
        economy: { inflation: 0.3, confidence: -2 },
        pops: { workers: 3, industrial_workers: 3, unemployed: 3, retirees: -3, business: -2 },
        groups: { unions: 6, industry: 4, workers: 3, business: -5, retirees: -3 },
        issues: { jobs: 3, inflation: -2 },
        caucuses: { sindical: 5, empresarial: -3 },
        tags: ['social_democratic'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'cb_government',
        name: 'Banco Central do governo',
        description: 'O Executivo define diretamente a taxa básica de juros (Selic).',
        ideology: { economy: 22, institutions: 20 },
        modifiers: { centralBank: 'government' },
        economy: { inflation: 0.8, confidence: -8 },
        pops: {
          unemployed: 4,
          industrial_workers: 3,
          workers: 2,
          retirees: -5,
          middle_class: -4,
          business: -6,
        },
        groups: { industry: 6, unions: 6, business: -15, retirees: -6, commerce: -4 },
        issues: { credit: 4, inflation: -4 },
        caucuses: { sindical: 4, empresarial: -8, ruralista: -2 },
        tags: ['developmentalist'],
        politicalCost: 45,
        implementationMonths: 4,
      }),
    ],
  }),
  category({
    id: 'media',
    branch: 'estado',
    name: 'Imprensa e comunicação',
    icon: 'newspaper',
    instrument: 'pl',
    levels: ['federal'],
    description:
      'Propriedade dos meios de comunicação, concessões de rádio e TV e regras para as plataformas.',
    defaultOptionId: 'media_free',
    options: [
      opt({
        id: 'media_free',
        name: 'Imprensa livre',
        description: 'Mídia privada, concessões por critérios técnicos e regulação mínima das redes.',
        ideology: { institutions: 65, social: 50, economy: 65 },
        tags: ['democratic', 'liberal'],
        politicalCost: 15,
        implementationMonths: 4,
      }),
      opt({
        id: 'media_regulated',
        name: 'Regulação da mídia',
        description:
          'Limites à concentração de veículos, direito de resposta e regras para plataformas digitais.',
        ideology: { institutions: 50, social: 30, economy: 35 },
        economy: { confidence: -2 },
        pops: { students: 3, workers: 2, middle_class: -3, business: -3 },
        groups: { social_movements: 8, unions: 4, business: -8, tech: -8 },
        issues: { corruption: 2 },
        caucuses: { sindical: 3, ambientalista: 2, evangelica: -6, empresarial: -4 },
        legitimacyShock: -2,
        tags: ['progressive'],
        politicalCost: 35,
        implementationMonths: 8,
      }),
      opt({
        id: 'media_state',
        name: 'Comunicação estatal',
        description:
          'Concessões controladas pelo governo, emissora estatal dominante e censura prévia.',
        ideology: { institutions: 5, social: 55, economy: 20 },
        budget: { administration: 0.03 },
        economy: { confidence: -6 },
        pops: {
          retirees: 2,
          civil_servants: 2,
          middle_class: -10,
          students: -12,
          tech_workers: -10,
          business: -6,
        },
        groups: {
          civil_servants: 3,
          youth: -30,
          tech: -30,
          social_movements: -20,
          business: -20,
          commerce: -8,
        },
        issues: { corruption: -10 },
        caucuses: {
          seguranca: 3,
          evangelica: -10,
          empresarial: -8,
          ambientalista: -6,
          sindical: -4,
          ruralista: -2,
        },
        legitimacyShock: -20,
        tags: ['authoritarian'],
        politicalCost: 70,
        implementationMonths: 6,
      }),
    ],
  }),
  category({
    id: 'administration',
    branch: 'estado',
    name: 'Administração pública',
    icon: 'building-2',
    instrument: 'pl',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Tamanho e funcionamento da máquina pública.',
    defaultOptionId: 'adm_current',
    options: [
      opt({
        id: 'adm_current',
        name: 'Máquina atual',
        description: 'Estrutura administrativa vigente.',
        ideology: { economy: 45, fiscal: 45, institutions: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'adm_lean',
        name: 'Estado enxuto',
        description: 'Corte de cargos, órgãos e burocracia.',
        ideology: { economy: 85, fiscal: 75, institutions: 60 },
        budget: { administration: -0.18 },
        economy: { confidence: 6 },
        pops: { business: 6, merchants: 5, middle_class: 2, civil_servants: -12, unemployed: -2 },
        groups: { business: 10, commerce: 8, civil_servants: -18, unions: -8 },
        issues: { regulation: 10 },
        caucuses: { empresarial: 6, sindical: -6 },
        tags: ['liberal'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
      opt({
        id: 'adm_digital',
        name: 'Governo digital',
        description: 'Serviços pela internet, dados integrados e menos papelada.',
        ideology: { economy: 58, fiscal: 55, institutions: 70 },
        budget: { administration: 0.05 },
        modifiers: { productivity: 0.005, productivityBySector: { public: 0.03 } },
        economy: { confidence: 3 },
        pops: { tech_workers: 6, middle_class: 4, students: 3, retirees: -2, civil_servants: -2 },
        groups: { tech: 12, business: 4, civil_servants: -3, unions: -4 },
        issues: { technology: 10, regulation: 6 },
        caucuses: { empresarial: 3 },
        politicalCost: 20,
        implementationMonths: 10,
      }),
      opt({
        id: 'adm_expanded',
        name: 'Expansão e concursos',
        description: 'Mais servidores e novos órgãos públicos.',
        ideology: { economy: 20, fiscal: 25, institutions: 40 },
        budget: { administration: 0.15 },
        economy: { unemployment: -0.15, confidence: -3 },
        pops: { civil_servants: 10, students: 3, business: -4, merchants: -2 },
        groups: { civil_servants: 16, unions: 6, business: -8, commerce: -4 },
        caucuses: { sindical: 4, empresarial: -5 },
        politicalCost: 25,
        implementationMonths: 8,
      }),
    ],
  }),

  // ===========================================================================
  // ECONOMIA
  // ===========================================================================
  category({
    id: 'economic_system',
    branch: 'economia',
    name: 'Sistema econômico',
    icon: 'scale',
    instrument: 'pec',
    levels: ['federal'],
    description:
      'Quem é dono das empresas e quem decide o investimento: o mercado, o Estado ou os trabalhadores.',
    defaultOptionId: 'econ_mixed',
    options: [
      opt({
        id: 'econ_laissez_faire',
        name: 'Liberalismo econômico',
        description:
          'Estado mínimo: privatizações, nenhuma estatal nova e investimento decidido pelo mercado.',
        ideology: { economy: 96, fiscal: 90, trade: 85, institutions: 70, foreign: 40 },
        modifiers: {
          reinvestment: 0.15,
          privateInvestmentMult: 1.3,
          banStateIndustry: true,
          privatizationRate: 0.02,
          corporateTax: -0.04,
          foreignInvestmentMult: 1.3,
          productivity: 0.02,
        },
        budget: { industry: -0.6, administration: -0.08 },
        economy: { confidence: 10 },
        pops: {
          business: 12,
          merchants: 8,
          tech_workers: 4,
          middle_class: 3,
          civil_servants: -10,
          industrial_workers: -5,
          workers: -4,
          unemployed: -6,
        },
        groups: {
          business: 20,
          commerce: 14,
          tech: 8,
          agribusiness: 8,
          civil_servants: -25,
          unions: -25,
          social_movements: -20,
          workers: -10,
          industry: -6,
        },
        issues: { taxes: 6, regulation: 8, welfare: -6 },
        caucuses: { ruralista: 6, empresarial: 5, evangelica: 2, sindical: -10, ambientalista: -3 },
        tags: ['liberal'],
        politicalCost: 75,
        implementationMonths: 18,
      }),
      opt({
        id: 'econ_mixed',
        name: 'Economia mista',
        description: 'Mercado com estatais estratégicas, bancos públicos e regulação.',
        ideology: { economy: 52, fiscal: 50, trade: 50, institutions: 50, foreign: 50 },
        politicalCost: 30,
        implementationMonths: 12,
      }),
      opt({
        id: 'econ_developmental',
        name: 'Desenvolvimentismo',
        description:
          'O Estado planeja e financia a industrialização: estatais nos setores de base, crédito dirigido e grandes obras.',
        ideology: { economy: 32, fiscal: 38, trade: 28, institutions: 40, foreign: 68 },
        modifiers: {
          stateConstructionDiscount: 0.15,
          stateShareFloor: {
            oil_field: 0.5,
            refinery: 0.5,
            power_hydro: 0.5,
            mine: 0.3,
            steel_mill: 0.3,
          },
          creditSubsidy: { heavy_industry: 1.5, high_tech: 1.5 },
          privateInvestmentMult: 0.92,
        },
        budget: { industry: 0.5 },
        economy: { inflation: 0.3, confidence: -4 },
        pops: {
          industrial_workers: 8,
          workers: 3,
          civil_servants: 3,
          unemployed: 3,
          business: -4,
          merchants: -3,
          farmers: -4,
          middle_class: -2,
        },
        groups: {
          industry: 15,
          unions: 10,
          workers: 6,
          civil_servants: 5,
          agribusiness: -12,
          business: -8,
          commerce: -8,
        },
        issues: { jobs: 6, credit: 4, infrastructure: 3 },
        caucuses: { sindical: 6, empresarial: -2, ruralista: -5, ambientalista: -3 },
        tags: ['developmentalist', 'nationalist'],
        politicalCost: 60,
        implementationMonths: 18,
      }),
      opt({
        id: 'econ_cooperative',
        name: 'Socialismo de mercado',
        description:
          'Mercado com empresas geridas pelos trabalhadores: negócios novos nascem como cooperativas e os lucros são repartidos.',
        ideology: { economy: 14, fiscal: 25, trade: 40, institutions: 78, foreign: 40 },
        modifiers: {
          newPrivateAsCooperative: true,
          cooperativizationRate: 0.02,
          profitSharing: 0.4,
          privateInvestmentMult: 0.7,
          foreignInvestmentMult: 0.6,
          dividendTax: 0.15,
        },
        budget: { industry: 0.2 },
        economy: { confidence: -12 },
        pops: {
          industrial_workers: 10,
          workers: 8,
          farmers: 3,
          unemployed: 3,
          business: -15,
          merchants: -8,
          middle_class: -5,
          tech_workers: -3,
        },
        groups: {
          unions: 16,
          workers: 14,
          social_movements: 12,
          business: -35,
          industry: -25,
          commerce: -20,
          agribusiness: -15,
          tech: -10,
        },
        issues: { jobs: 4, welfare: 4 },
        caucuses: { sindical: 8, ambientalista: 2, empresarial: -10, ruralista: -8, evangelica: -4 },
        legitimacyShock: -3,
        tags: ['socialist'],
        politicalCost: 85,
        implementationMonths: 24,
      }),
      opt({
        id: 'econ_planned',
        name: 'Economia planificada',
        description:
          'O Estado é dono das empresas, fixa os preços e decide o que produzir; o investimento privado é proibido.',
        ideology: { economy: 0, fiscal: 8, trade: 12, institutions: 12, foreign: 78 },
        modifiers: {
          banPrivateInvestment: true,
          nationalizationRate: 0.08,
          expropriationRate: 0.1,
          priceControls: true,
          stateConstructionDiscount: 0.25,
          productivity: -0.06,
          foreignInvestmentMult: 0,
          tradeOpenness: 0.6,
        },
        budget: { industry: 1, administration: 0.15 },
        economy: { inflation: -0.5, confidence: -20 },
        pops: {
          unemployed: 12,
          industrial_workers: 6,
          workers: 5,
          civil_servants: 5,
          business: -15,
          merchants: -15,
          middle_class: -10,
          tech_workers: -10,
          farmers: -6,
        },
        groups: {
          social_movements: 14,
          unions: 8,
          workers: 8,
          civil_servants: 8,
          business: -40,
          commerce: -40,
          industry: -35,
          agribusiness: -35,
          tech: -30,
          youth: -5,
        },
        issues: { jobs: 8, welfare: 6, inflation: 4, regulation: -10, credit: -6 },
        caucuses: {
          sindical: 3,
          ambientalista: -2,
          seguranca: -4,
          evangelica: -8,
          ruralista: -10,
          empresarial: -10,
        },
        legitimacyShock: -10,
        tags: ['communist'],
        politicalCost: 95,
        implementationMonths: 24,
      }),
    ],
  }),
  category({
    id: 'taxation',
    branch: 'economia',
    name: 'Tributação',
    icon: 'receipt',
    instrument: 'pl',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Quanto e de quem o Estado arrecada.',
    defaultOptionId: 'tax_mixed',
    options: [
      opt({
        id: 'tax_low',
        name: 'Imposto baixo e simplificado',
        description: 'Menos tributos sobre renda, lucro e consumo e um sistema mais simples.',
        ideology: { fiscal: 88, economy: 75 },
        modifiers: { incomeTax: -0.03, corporateTax: -0.07, consumptionTax: -0.02, reinvestment: 0.05 },
        economy: { confidence: 7 },
        pops: {
          business: 9,
          merchants: 7,
          middle_class: 3,
          tech_workers: 3,
          civil_servants: -5,
          unemployed: -3,
          retirees: -2,
        },
        groups: {
          business: 14,
          commerce: 10,
          industry: 6,
          agribusiness: 6,
          civil_servants: -8,
          unions: -6,
          social_movements: -6,
        },
        issues: { taxes: 10 },
        caucuses: { empresarial: 8, ruralista: 5, sindical: -5 },
        tags: ['liberal'],
        politicalCost: 25,
        implementationMonths: 6,
      }),
      opt({
        id: 'tax_mixed',
        name: 'Sistema misto',
        description: 'O sistema atual, com impostos sobre consumo e renda.',
        ideology: { fiscal: 50, economy: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'tax_progressive',
        name: 'Progressivo',
        description: 'Quem ganha mais paga proporcionalmente mais; dividendos voltam a ser tributados.',
        ideology: { fiscal: 25, economy: 35 },
        modifiers: { incomeTax: 0.03, corporateTax: 0.02, consumptionTax: -0.02, dividendTax: 0.1 },
        economy: { confidence: -4 },
        pops: { workers: 4, unemployed: 3, industrial_workers: 3, business: -9, middle_class: -3 },
        groups: { unions: 9, social_movements: 8, workers: 6, business: -12, commerce: -4 },
        issues: { welfare: 4 },
        caucuses: { sindical: 5, empresarial: -6, ruralista: -3 },
        tags: ['social_democratic'],
        politicalCost: 25,
        implementationMonths: 6,
      }),
      opt({
        id: 'tax_wealth',
        name: 'Imposto sobre grandes fortunas',
        description: 'Tributação pesada sobre grandes patrimônios, lucros e dividendos.',
        ideology: { fiscal: 10, economy: 18 },
        modifiers: {
          incomeTax: 0.03,
          corporateTax: 0.03,
          dividendTax: 0.15,
          wealthTax: 0.02,
          privateInvestmentMult: 0.9,
          foreignInvestmentMult: 0.85,
        },
        economy: { confidence: -10 },
        pops: { workers: 5, unemployed: 5, students: 3, business: -14, middle_class: -5 },
        groups: { social_movements: 14, unions: 10, business: -20, industry: -8, commerce: -6 },
        issues: { welfare: 6 },
        caucuses: { sindical: 6, ambientalista: 2, empresarial: -10, ruralista: -6 },
        tags: ['social_democratic'],
        politicalCost: 35,
        implementationMonths: 8,
      }),
    ],
  }),
  category({
    id: 'trade',
    branch: 'economia',
    name: 'Comércio exterior',
    icon: 'ship',
    instrument: 'pl',
    allowsMP: true,
    levels: ['federal'],
    description: 'Tarifas de importação e grau de abertura ao comércio mundial.',
    defaultOptionId: 'trade_mixed',
    options: [
      opt({
        id: 'trade_open',
        name: 'Livre comércio',
        description: 'Corta tarifas de importação e assina grandes acordos comerciais.',
        ideology: { trade: 92, foreign: 25 },
        modifiers: { tariff: -0.1, tradeOpenness: 1.15 },
        economy: { inflation: -0.2, confidence: 4 },
        pops: {
          farmers: 7,
          business: 4,
          tech_workers: 3,
          middle_class: 3,
          industrial_workers: -8,
          workers: -2,
        },
        groups: { agribusiness: 14, tech: 6, commerce: 6, industry: -14, unions: -8 },
        issues: { agriculture: 6, inflation: 3 },
        caucuses: { ruralista: 8, empresarial: 3, sindical: -5 },
        tags: ['liberal'],
        politicalCost: 25,
        implementationMonths: 8,
      }),
      opt({
        id: 'trade_mixed',
        name: 'Abertura moderada',
        description: 'Tarifas médias e acordos pontuais.',
        ideology: { trade: 50, foreign: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'trade_protectionist',
        name: 'Protecionismo',
        description: 'Tarifas de importação altas para todos os bens.',
        ideology: { trade: 15, foreign: 75 },
        modifiers: { tariff: 0.18, tradeOpenness: 0.85 },
        economy: { inflation: 0.2, confidence: -3 },
        pops: { industrial_workers: 8, workers: 3, farmers: -6, middle_class: -3, tech_workers: -2 },
        groups: { industry: 14, unions: 8, agribusiness: -12, commerce: -6, tech: -4 },
        issues: { jobs: 4, inflation: -2 },
        caucuses: { sindical: 4, empresarial: 1, ruralista: -6 },
        tags: ['nationalist'],
        politicalCost: 25,
        implementationMonths: 8,
      }),
      opt({
        id: 'trade_isi',
        name: 'Substituição de importações',
        description:
          'Tarifas altas sobre bens industriais e de consumo e crédito para produzir no país o que hoje se importa.',
        ideology: { trade: 8, foreign: 82 },
        modifiers: {
          tariffByCategory: { consumer: 0.38, industrial: 0.04, high_tech: 0.35 },
          tradeOpenness: 0.75,
          creditSubsidy: { manufacturing: 1 },
        },
        budget: { industry: 0.1 },
        economy: { inflation: 0.4, confidence: -5 },
        pops: {
          industrial_workers: 10,
          workers: 3,
          unemployed: 2,
          farmers: -6,
          middle_class: -6,
          tech_workers: -4,
          merchants: -3,
        },
        groups: {
          industry: 18,
          unions: 10,
          workers: 4,
          agribusiness: -16,
          commerce: -12,
          tech: -10,
          business: -4,
        },
        issues: { jobs: 6, inflation: -4, technology: -2 },
        caucuses: { sindical: 5, empresarial: -1, ruralista: -8 },
        tags: ['developmentalist', 'nationalist'],
        politicalCost: 45,
        implementationMonths: 10,
      }),
      opt({
        id: 'trade_autarky',
        name: 'Autarquia',
        description:
          'Comércio exterior quase fechado: o país produz o que consome e importa só o indispensável.',
        ideology: { trade: 0, foreign: 95 },
        modifiers: { tradeOpenness: 0.05, tariff: 0.5 },
        economy: { inflation: 1, confidence: -12 },
        pops: {
          industrial_workers: 4,
          farmers: -12,
          middle_class: -10,
          tech_workers: -10,
          business: -8,
          merchants: -6,
        },
        groups: {
          industry: 6,
          unions: 2,
          agribusiness: -35,
          commerce: -25,
          tech: -25,
          business: -20,
          youth: -6,
        },
        issues: { jobs: 2, inflation: -8, technology: -6 },
        caucuses: { sindical: 1, empresarial: -8, ruralista: -10 },
        tags: ['nationalist'],
        politicalCost: 65,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'industrial_policy',
    branch: 'economia',
    name: 'Política industrial',
    icon: 'factory',
    instrument: 'pl',
    allowsMP: true,
    levels: ['federal'],
    description: 'Como o Estado estimula — ou deixa de estimular — a indústria nacional.',
    defaultOptionId: 'ind_incentives',
    options: [
      opt({
        id: 'ind_neutral',
        name: 'Sem política industrial',
        description: 'Fim dos incentivos e regimes especiais: a mesma regra para todos os setores.',
        ideology: { economy: 80, trade: 72, fiscal: 70 },
        modifiers: { corporateTax: -0.01 },
        budget: { industry: -0.4 },
        economy: { confidence: 3 },
        pops: { merchants: 3, business: 2, farmers: 2, industrial_workers: -5, tech_workers: -3 },
        groups: { commerce: 6, agribusiness: 6, business: 4, industry: -14, tech: -8, unions: -4 },
        issues: { regulation: 4, jobs: -2 },
        caucuses: { ruralista: 3, empresarial: 1, sindical: -3 },
        tags: ['liberal'],
        politicalCost: 25,
        implementationMonths: 6,
      }),
      opt({
        id: 'ind_incentives',
        name: 'Incentivos fiscais',
        description:
          'Isenções e regimes especiais para setores e regiões, como a Zona Franca de Manaus.',
        ideology: { economy: 55, trade: 50, fiscal: 50 },
        modifiers: { productivityBySector: { high_tech: 0.01 } },
        politicalCost: 15,
        implementationMonths: 4,
      }),
      opt({
        id: 'ind_bndes',
        name: 'Crédito do banco de fomento',
        description:
          'O BNDES empresta a juros baixos para a indústria de base, de transformação e de alta tecnologia.',
        ideology: { economy: 32, trade: 40, fiscal: 40 },
        modifiers: {
          creditSubsidy: { heavy_industry: 1.5, manufacturing: 1.5, high_tech: 1.5 },
          interestRateOffset: -0.5,
        },
        budget: { industry: 0.3 },
        economy: { inflation: 0.2, confidence: -1 },
        pops: { industrial_workers: 6, business: 3, tech_workers: 2, merchants: -2, middle_class: -2 },
        groups: { industry: 16, unions: 6, workers: 3, agribusiness: -6, commerce: -5, business: -3 },
        issues: { credit: 8, jobs: 4 },
        caucuses: { sindical: 4, empresarial: 3, ruralista: -3 },
        tags: ['developmentalist'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'ind_local_content',
        name: 'Conteúdo local',
        description:
          'Grandes projetos e compras públicas são obrigados a usar máquinas e insumos feitos no país.',
        ideology: { economy: 38, trade: 20, fiscal: 45 },
        modifiers: {
          tariffByCategory: { industrial: 0.08, high_tech: 0.08 },
          creditSubsidy: { heavy_industry: 1 },
          productivity: -0.01,
        },
        economy: { inflation: 0.2, confidence: -2 },
        pops: { industrial_workers: 6, workers: 2, business: -3, middle_class: -2, farmers: -2 },
        groups: { industry: 12, unions: 6, agribusiness: -6, commerce: -4, tech: -4 },
        issues: { jobs: 5 },
        caucuses: { sindical: 3, ruralista: -3 },
        tags: ['nationalist', 'developmentalist'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
      opt({
        id: 'ind_national_plan',
        name: 'Plano nacional de industrialização',
        description:
          'Metas por setor, estatais à frente e crédito em massa para toda a indústria (exige desenvolvimentismo ou planificação).',
        ideology: { economy: 10, trade: 25, fiscal: 30 },
        requires: ['econ_developmental', 'econ_planned'],
        modifiers: {
          stateConstructionDiscount: 0.1,
          creditSubsidy: { heavy_industry: 2, manufacturing: 2, high_tech: 2 },
        },
        budget: { industry: 0.6 },
        economy: { inflation: 0.4, confidence: -5 },
        pops: {
          industrial_workers: 9,
          workers: 4,
          unemployed: 4,
          civil_servants: 2,
          business: -6,
          merchants: -5,
          farmers: -4,
          middle_class: -3,
        },
        groups: {
          industry: 12,
          unions: 12,
          workers: 6,
          civil_servants: 4,
          business: -12,
          agribusiness: -12,
          commerce: -10,
          tech: -4,
        },
        issues: { jobs: 8, infrastructure: 4, inflation: -3 },
        caucuses: { sindical: 6, empresarial: -5, ruralista: -6 },
        tags: ['developmentalist'],
        politicalCost: 60,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'resources',
    branch: 'economia',
    name: 'Recursos naturais',
    icon: 'pickaxe',
    instrument: 'pl',
    levels: ['federal'],
    description: 'Quem explora o petróleo e os minérios e quanto da renda fica com o Estado.',
    defaultOptionId: 'res_sharing',
    options: [
      opt({
        id: 'res_concession',
        name: 'Concessão',
        description:
          'Empresas privadas e estrangeiras exploram petróleo e minérios e pagam royalties.',
        ideology: { economy: 80, foreign: 30 },
        modifiers: { foreignInvestmentMult: 1.15 },
        economy: { confidence: 4 },
        pops: { business: 4, middle_class: 2, civil_servants: -3, industrial_workers: -2 },
        groups: { business: 8, commerce: 2, unions: -8, social_movements: -6, civil_servants: -4 },
        caucuses: { empresarial: 5, sindical: -4 },
        tags: ['liberal'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
      opt({
        id: 'res_sharing',
        name: 'Partilha',
        description:
          'A estatal tem participação mínima nos campos e parte do óleo fica com a União.',
        ideology: { economy: 50, foreign: 55 },
        modifiers: { resourceStateShare: 0.3 },
        politicalCost: 15,
        implementationMonths: 6,
      }),
      opt({
        id: 'res_monopoly',
        name: 'Monopólio estatal',
        description:
          '"O petróleo é nosso": só a estatal explora petróleo e minérios, e o lucro vai para o Tesouro.',
        ideology: { economy: 18, foreign: 85 },
        modifiers: { resourceStateShare: 1, foreignInvestmentMult: 0.85 },
        budget: { industry: 0.15 },
        economy: { confidence: -6 },
        pops: { industrial_workers: 4, civil_servants: 3, workers: 2, business: -6, middle_class: -2 },
        groups: { unions: 10, social_movements: 6, civil_servants: 4, business: -14, commerce: -3 },
        issues: { jobs: 3 },
        caucuses: { sindical: 6, empresarial: -6, ruralista: -2 },
        tags: ['nationalist', 'developmentalist'],
        politicalCost: 55,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'banking',
    branch: 'economia',
    name: 'Sistema financeiro',
    icon: 'banknote',
    instrument: 'plp',
    levels: ['federal'],
    description: 'Regras dos bancos e papel dos bancos públicos no crédito.',
    defaultOptionId: 'bank_regulated',
    options: [
      opt({
        id: 'bank_liberal',
        name: 'Mercado financeiro livre',
        description:
          'Menos exigências aos bancos, entrada de bancos estrangeiros e fim do crédito direcionado.',
        ideology: { economy: 85, foreign: 35 },
        modifiers: {
          privateInvestmentMult: 1.1,
          foreignInvestmentMult: 1.05,
          creditSubsidy: { agro: -0.3 },
        },
        economy: { confidence: 5 },
        pops: { business: 6, middle_class: 2, tech_workers: 2, farmers: -4, workers: -2 },
        groups: { business: 12, tech: 4, commerce: 2, agribusiness: -8, unions: -6, social_movements: -4 },
        issues: { credit: 3 },
        caucuses: { empresarial: 3, ruralista: -4, sindical: -3 },
        tags: ['liberal'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
      opt({
        id: 'bank_regulated',
        name: 'Regulação prudencial',
        description: 'Bancos privados e públicos convivem sob as regras do Banco Central.',
        ideology: { economy: 52, foreign: 50 },
        politicalCost: 15,
        implementationMonths: 6,
      }),
      opt({
        id: 'bank_public',
        name: 'Bancos públicos fortes',
        description: 'Bancos estatais ampliam o crédito barato para empresas, agro e habitação.',
        ideology: { economy: 30, foreign: 58 },
        modifiers: {
          interestRateOffset: -1,
          creditSubsidy: { agro: 0.5 },
          privateInvestmentMult: 1.05,
        },
        budget: { industry: 0.1 },
        economy: { inflation: 0.2, confidence: -3 },
        pops: { farmers: 4, workers: 3, merchants: 2, industrial_workers: 2, business: -4 },
        groups: { agribusiness: 6, industry: 6, unions: 4, workers: 3, business: -10 },
        issues: { credit: 10, housing: 3 },
        caucuses: { ruralista: 4, sindical: 3, empresarial: -2 },
        tags: ['developmentalist'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
      opt({
        id: 'bank_nationalized',
        name: 'Sistema financeiro estatal',
        description: 'Os grandes bancos são estatizados e o Estado decide para onde vai o crédito.',
        ideology: { economy: 8, foreign: 80 },
        modifiers: {
          interestRateOffset: -1.5,
          stateShareFloor: { bank: 1 },
          foreignInvestmentMult: 0.7,
        },
        budget: { industry: 0.3 },
        economy: { inflation: 0.4, confidence: -12 },
        pops: {
          workers: 3,
          unemployed: 3,
          industrial_workers: 3,
          business: -12,
          middle_class: -6,
          tech_workers: -4,
        },
        groups: {
          unions: 8,
          social_movements: 8,
          business: -35,
          commerce: -10,
          tech: -8,
          agribusiness: -6,
          industry: -5,
        },
        issues: { credit: 8 },
        caucuses: { sindical: 4, empresarial: -10, ruralista: -6, evangelica: -3 },
        legitimacyShock: -3,
        tags: ['socialist'],
        politicalCost: 70,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'labor',
    branch: 'economia',
    name: 'Trabalho',
    icon: 'hard-hat',
    instrument: 'pl',
    levels: ['federal'],
    description: 'Regras de contratação, demissão e direitos trabalhistas.',
    defaultOptionId: 'labor_clt',
    options: [
      opt({
        id: 'labor_deregulated',
        name: 'Livre contratação',
        description:
          'Fim da CLT: contratos individuais livres, sem multa rescisória nem encargos obrigatórios.',
        ideology: { economy: 95, institutions: 60 },
        modifiers: { laborFlexibility: 1.8, wageMult: 0.9, informality: -0.05 },
        economy: { confidence: 8 },
        pops: { business: 12, merchants: 8, unemployed: 2, workers: -10, industrial_workers: -12 },
        groups: {
          business: 18,
          commerce: 12,
          agribusiness: 6,
          unions: -35,
          workers: -25,
          social_movements: -12,
        },
        issues: { jobs: 4, regulation: 6 },
        caucuses: { empresarial: 8, ruralista: 4, sindical: -10 },
        tags: ['liberal'],
        politicalCost: 50,
        implementationMonths: 6,
      }),
      opt({
        id: 'labor_flexible',
        name: 'Flexibilização',
        description: 'Contratos mais livres e menos encargos, mantendo direitos básicos.',
        ideology: { economy: 80, institutions: 55 },
        modifiers: { laborFlexibility: 1.4, wageMult: 0.96, informality: -0.04 },
        economy: { confidence: 6 },
        pops: { business: 8, merchants: 6, workers: -5, industrial_workers: -6 },
        groups: { business: 12, commerce: 8, industry: 6, unions: -16, workers: -10 },
        issues: { jobs: 4 },
        caucuses: { empresarial: 8, ruralista: 3, sindical: -8 },
        tags: ['liberal'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'labor_clt',
        name: 'CLT atual',
        description: 'Regras trabalhistas vigentes.',
        ideology: { economy: 45, institutions: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'labor_protective',
        name: 'Mais proteção ao trabalhador',
        description: 'Jornada menor, estabilidade no emprego e novos direitos.',
        ideology: { economy: 18, institutions: 48 },
        modifiers: { laborFlexibility: 0.7, wageMult: 1.06, informality: 0.05 },
        economy: { inflation: 0.2, confidence: -5 },
        pops: { workers: 7, industrial_workers: 7, unemployed: 2, business: -9, merchants: -6 },
        groups: { unions: 16, workers: 12, business: -12, commerce: -8 },
        issues: { jobs: 3 },
        caucuses: { sindical: 8, empresarial: -6 },
        tags: ['social_democratic'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'labor_councils',
        name: 'Conselhos de trabalhadores',
        description:
          'Cogestão: conselhos eleitos pelos empregados decidem junto com a direção e dividem os lucros (exige socialismo de mercado ou planificação).',
        ideology: { economy: 8, institutions: 85 },
        requires: ['econ_cooperative', 'econ_planned'],
        modifiers: { laborFlexibility: 0.6, profitSharing: 0.3, wageMult: 1.05, productivity: -0.02 },
        economy: { confidence: -6 },
        pops: { industrial_workers: 10, workers: 8, business: -12, merchants: -5, middle_class: -3 },
        groups: { unions: 18, workers: 14, social_movements: 6, business: -30, industry: -15, commerce: -10 },
        issues: { jobs: 3 },
        caucuses: { sindical: 8, empresarial: -10, ruralista: -4 },
        tags: ['socialist'],
        politicalCost: 65,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'minimum_wage',
    branch: 'economia',
    name: 'Salário mínimo',
    icon: 'coins',
    instrument: 'pl',
    allowsMP: true,
    levels: ['federal'],
    description:
      'Piso salarial nacional e sua regra de reajuste (o mínimo também corrige aposentadorias).',
    defaultOptionId: 'mw_valorization',
    options: [
      opt({
        id: 'mw_none',
        name: 'Sem salário mínimo',
        description: 'Salários definidos apenas pela negociação entre empresas e empregados.',
        ideology: { economy: 100, fiscal: 95 },
        modifiers: { minimumWage: 0, informality: -0.03 },
        budget: { pensions: -0.04 },
        economy: { confidence: 4 },
        pops: {
          business: 8,
          merchants: 8,
          unemployed: 2,
          workers: -12,
          industrial_workers: -6,
          retirees: -6,
        },
        groups: {
          business: 12,
          commerce: 12,
          agribusiness: 4,
          unions: -30,
          workers: -25,
          retirees: -12,
          social_movements: -10,
        },
        issues: { jobs: 3, welfare: -4 },
        caucuses: { empresarial: 6, ruralista: 3, sindical: -10 },
        tags: ['liberal'],
        politicalCost: 45,
        implementationMonths: 3,
      }),
      opt({
        id: 'mw_low',
        name: 'Mínimo sem ganho real',
        description: 'Piso baixo, corrigido apenas pela inflação.',
        ideology: { economy: 78, fiscal: 75 },
        modifiers: { minimumWage: 0.45, informality: -0.01 },
        budget: { pensions: -0.02 },
        economy: { confidence: 3 },
        pops: { business: 5, merchants: 5, workers: -6, retirees: -4, industrial_workers: -3 },
        groups: { business: 6, commerce: 8, unions: -14, workers: -10, retirees: -6 },
        issues: { jobs: 2 },
        caucuses: { empresarial: 4, sindical: -8 },
        tags: ['liberal'],
        politicalCost: 30,
        implementationMonths: 3,
      }),
      opt({
        id: 'mw_valorization',
        name: 'Valorização gradual',
        description: 'Reajuste pela inflação mais o crescimento do PIB.',
        ideology: { economy: 45, fiscal: 45 },
        modifiers: { minimumWage: 0.6 },
        politicalCost: 15,
        implementationMonths: 3,
      }),
      opt({
        id: 'mw_high',
        name: 'Salário mínimo forte',
        description: 'Aumentos reais fortes para aproximar o mínimo do custo de vida.',
        ideology: { economy: 18, fiscal: 30 },
        modifiers: { minimumWage: 0.8, informality: 0.04 },
        budget: { pensions: 0.05, social: 0.03 },
        economy: { inflation: 0.3, confidence: -5 },
        pops: {
          workers: 10,
          retirees: 6,
          industrial_workers: 4,
          business: -8,
          merchants: -10,
          unemployed: -3,
        },
        groups: { unions: 15, workers: 14, retirees: 8, social_movements: 6, commerce: -14, business: -10, agribusiness: -4 },
        issues: { welfare: 4 },
        caucuses: { sindical: 8, empresarial: -6, ruralista: -3 },
        tags: ['social_democratic'],
        politicalCost: 30,
        implementationMonths: 3,
      }),
    ],
  }),
  category({
    id: 'unions',
    branch: 'economia',
    name: 'Sindicatos',
    icon: 'megaphone',
    instrument: 'pl',
    levels: ['federal'],
    description: 'Liberdade sindical, financiamento das entidades e direito de greve.',
    defaultOptionId: 'unions_free',
    options: [
      opt({
        id: 'unions_banned',
        name: 'Sindicatos proibidos',
        description:
          'Fim das entidades sindicais e da negociação coletiva; greves passam a ser ilegais.',
        ideology: { economy: 90, institutions: 15 },
        modifiers: { wageMult: 0.93, laborFlexibility: 1.3 },
        economy: { confidence: 3 },
        pops: {
          business: 8,
          merchants: 4,
          industrial_workers: -12,
          workers: -8,
          civil_servants: -8,
          health_workers: -4,
        },
        groups: {
          business: 12,
          commerce: 6,
          unions: -40,
          workers: -20,
          social_movements: -20,
          civil_servants: -15,
        },
        caucuses: { empresarial: 3, seguranca: 2, sindical: -10, ambientalista: -3, evangelica: -2 },
        legitimacyShock: -10,
        tags: ['authoritarian'],
        politicalCost: 60,
        implementationMonths: 4,
      }),
      opt({
        id: 'unions_restricted',
        name: 'Sindicatos restritos',
        description:
          'Fim da contribuição obrigatória, limites ao direito de greve e serviços essenciais protegidos.',
        ideology: { economy: 75, institutions: 45 },
        modifiers: { wageMult: 0.97, laborFlexibility: 1.15 },
        economy: { confidence: 3 },
        pops: { business: 5, merchants: 3, industrial_workers: -5, civil_servants: -5, workers: -3 },
        groups: { business: 8, commerce: 6, agribusiness: 4, unions: -20, civil_servants: -8, workers: -6 },
        caucuses: { empresarial: 5, sindical: -8 },
        tags: ['liberal', 'conservative'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'unions_free',
        name: 'Liberdade sindical',
        description: 'Sindicatos livres, negociação coletiva e direito de greve.',
        ideology: { economy: 45, institutions: 60 },
        tags: ['democratic'],
        politicalCost: 15,
        implementationMonths: 4,
      }),
      opt({
        id: 'unions_corporatist',
        name: 'Sindicalismo de Estado',
        description:
          'Sindicato único por categoria, financiado pelo Estado, com greves mediadas pela Justiça do Trabalho.',
        ideology: { economy: 30, institutions: 25 },
        modifiers: { wageMult: 1.03, laborFlexibility: 0.9 },
        economy: { confidence: -3 },
        pops: { industrial_workers: 5, civil_servants: 3, workers: 2, business: -5, merchants: -3 },
        groups: { unions: 12, civil_servants: 4, business: -8, commerce: -4, social_movements: -4 },
        caucuses: { sindical: 4, empresarial: -4 },
        legitimacyShock: -2,
        tags: ['nationalist'],
        politicalCost: 35,
        implementationMonths: 6,
      }),
    ],
  }),
  category({
    id: 'land',
    branch: 'economia',
    name: 'Terra',
    icon: 'tractor',
    instrument: 'pl',
    levels: ['federal'],
    description: 'Propriedade da terra no campo e reforma agrária.',
    defaultOptionId: 'land_current',
    options: [
      opt({
        id: 'land_latifundio',
        name: 'Grande propriedade',
        description:
          'Segurança jurídica máxima para grandes propriedades e fim das desapropriações.',
        ideology: { economy: 85, environment: 88 },
        modifiers: { productivityBySector: { agro: 0.03 }, resourceExpansion: 1.1 },
        economy: { confidence: 3 },
        pops: { farmers: 5, business: 4, workers: -2, unemployed: -5 },
        groups: { agribusiness: 18, business: 4, social_movements: -30, unions: -6 },
        issues: { agriculture: 8 },
        caucuses: { ruralista: 10, sindical: -4, ambientalista: -8 },
        tags: ['conservative'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'land_current',
        name: 'Regras atuais',
        description: 'Desapropriação apenas de terras improdutivas, com indenização.',
        ideology: { economy: 55, environment: 60 },
        politicalCost: 15,
        implementationMonths: 4,
      }),
      opt({
        id: 'land_reform',
        name: 'Reforma agrária ampla',
        description: 'Desapropriação de grandes propriedades e assentamento de famílias sem terra.',
        ideology: { economy: 25, environment: 40 },
        modifiers: { landReform: 0.5, productivityBySector: { agro: -0.02 } },
        budget: { social: 0.04, administration: 0.02 },
        economy: { confidence: -5 },
        pops: { unemployed: 8, workers: 4, farmers: -4, business: -6 },
        groups: { social_movements: 18, unions: 6, agribusiness: -30, business: -8 },
        issues: { welfare: 4, housing: 2 },
        caucuses: { sindical: 5, ambientalista: 3, ruralista: -10, empresarial: -4, evangelica: -2 },
        tags: ['progressive'],
        politicalCost: 45,
        implementationMonths: 12,
      }),
      opt({
        id: 'land_collective',
        name: 'Coletivização',
        description:
          'As grandes propriedades viram fazendas coletivas e cooperativas sob plano estatal (exige socialismo de mercado ou planificação).',
        ideology: { economy: 5, environment: 55 },
        requires: ['econ_cooperative', 'econ_planned'],
        modifiers: { landReform: 1, productivityBySector: { agro: -0.08 } },
        budget: { social: 0.04 },
        economy: { confidence: -10 },
        pops: { unemployed: 10, workers: 5, farmers: -12, business: -10, merchants: -3 },
        groups: { social_movements: 16, unions: 4, agribusiness: -40, business: -15, commerce: -6 },
        issues: { welfare: 4, agriculture: -6 },
        caucuses: { sindical: 3, ruralista: -10, empresarial: -8, evangelica: -4 },
        legitimacyShock: -5,
        tags: ['communist'],
        politicalCost: 75,
        implementationMonths: 18,
      }),
    ],
  }),
  category({
    id: 'pensions',
    branch: 'economia',
    name: 'Previdência',
    icon: 'piggy-bank',
    instrument: 'pec',
    levels: ['federal', 'estadual'],
    description: 'Regras de aposentadoria.',
    defaultOptionId: 'pen_current',
    options: [
      opt({
        id: 'pen_current',
        name: 'Regras atuais',
        description: 'Sistema de repartição vigente.',
        ideology: { economy: 45, fiscal: 45 },
        politicalCost: 20,
        implementationMonths: 4,
      }),
      opt({
        id: 'pen_reform',
        name: 'Reforma (idade mínima maior)',
        description: 'Endurece as regras de acesso para equilibrar as contas.',
        ideology: { economy: 70, fiscal: 70 },
        budget: { pensions: -0.1 },
        economy: { confidence: 8, growth: 0.15 },
        pops: { retirees: -8, civil_servants: -7, workers: -4, business: 5 },
        groups: { retirees: -14, civil_servants: -10, unions: -10, business: 10 },
        caucuses: { empresarial: 6, sindical: -8 },
        tags: ['liberal'],
        politicalCost: 40,
        implementationMonths: 12,
      }),
      opt({
        id: 'pen_capitalization',
        name: 'Capitalização',
        description: 'Contas individuais de aposentadoria administradas por fundos.',
        ideology: { economy: 92, fiscal: 80 },
        budget: { pensions: -0.18 },
        modifiers: { privateInvestmentMult: 1.06 },
        economy: { confidence: 6 },
        pops: { retirees: -10, workers: -6, civil_servants: -8, business: 6, tech_workers: 3 },
        groups: { retirees: -18, unions: -14, civil_servants: -10, business: 12 },
        caucuses: { empresarial: 5, sindical: -10 },
        tags: ['liberal'],
        politicalCost: 50,
        implementationMonths: 18,
      }),
      opt({
        id: 'pen_expanded',
        name: 'Benefícios ampliados',
        description: 'Reajustes acima da inflação e regras de acesso mais brandas.',
        ideology: { economy: 15, fiscal: 20 },
        budget: { pensions: 0.12 },
        economy: { confidence: -6, inflation: 0.2 },
        pops: { retirees: 10, workers: 3, business: -5, middle_class: -2 },
        groups: { retirees: 16, unions: 6, business: -8 },
        issues: { pensions: 10 },
        caucuses: { sindical: 8, empresarial: -5 },
        tags: ['social_democratic'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
    ],
  }),
  category({
    id: 'environment',
    branch: 'economia',
    name: 'Meio ambiente',
    icon: 'trees',
    instrument: 'pl',
    levels: ['federal', 'estadual'],
    description: 'Licenciamento e proteção ambiental.',
    defaultOptionId: 'env_current',
    options: [
      opt({
        id: 'env_current',
        name: 'Regras atuais',
        description: 'Licenciamento e fiscalização vigentes.',
        ideology: { environment: 45, economy: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'env_strict',
        name: 'Proteção rigorosa',
        description: 'Desmatamento zero, licenciamento exigente e fiscalização dura.',
        ideology: { environment: 10, economy: 40 },
        modifiers: {
          pollutionPenalty: 0.15,
          resourceExpansion: 0.85,
          productivityBySector: { agro: -0.02 },
        },
        budget: { administration: 0.03 },
        pops: { students: 6, health_workers: 3, middle_class: 3, farmers: -10, business: -3 },
        groups: { social_movements: 10, youth: 8, agribusiness: -16, industry: -4 },
        issues: { environment: 14 },
        caucuses: { ambientalista: 10, empresarial: -3, ruralista: -10 },
        tags: ['green'],
        politicalCost: 30,
        implementationMonths: 8,
      }),
      opt({
        id: 'env_flexible',
        name: 'Licenciamento flexível',
        description: 'Licenças rápidas para obras, mineração e expansão agrícola.',
        ideology: { environment: 90, economy: 65 },
        modifiers: { resourceExpansion: 1.2, pollutionPenalty: -0.03, foreignInvestmentMult: 0.95 },
        pops: { farmers: 9, business: 5, students: -7, health_workers: -3 },
        groups: { agribusiness: 16, industry: 6, social_movements: -12, youth: -8 },
        issues: { agriculture: 8, environment: -8 },
        caucuses: { ruralista: 10, empresarial: 3, ambientalista: -10 },
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'env_green_economy',
        name: 'Economia verde',
        description: 'Incentivos à energia limpa, à bioeconomia e à indústria de baixo carbono.',
        ideology: { environment: 25, economy: 45 },
        modifiers: {
          pollutionPenalty: 0.08,
          productivityBySector: { energy: 0.04 },
          creditSubsidy: { energy: 1 },
        },
        budget: { infrastructure: 0.06, science: 0.1 },
        pops: { students: 5, tech_workers: 4, farmers: -3, industrial_workers: -2 },
        groups: { tech: 8, youth: 6, agribusiness: -5, industry: -3 },
        issues: { environment: 8, technology: 4 },
        caucuses: { ambientalista: 7, empresarial: 1, ruralista: -4 },
        tags: ['green'],
        politicalCost: 25,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'infrastructure',
    branch: 'economia',
    name: 'Infraestrutura',
    icon: 'construction',
    instrument: 'pl',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Como obras e serviços de infraestrutura são feitos e financiados.',
    defaultOptionId: 'infra_public',
    options: [
      opt({
        id: 'infra_public',
        name: 'Obras públicas',
        description: 'O Estado contrata e executa as obras.',
        ideology: { economy: 40, fiscal: 45 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'infra_concessions',
        name: 'Concessões e privatizações',
        description:
          'Empresas privadas operam rodovias, portos e energia e investem em troca de tarifas.',
        ideology: { economy: 88, fiscal: 65 },
        budget: { infrastructure: -0.12 },
        modifiers: { privateInvestmentMult: 1.06, foreignInvestmentMult: 1.08, productivity: 0.01 },
        economy: { confidence: 7 },
        pops: { business: 7, middle_class: 3, civil_servants: -6, workers: -2 },
        groups: { business: 12, industry: 6, unions: -10, civil_servants: -8 },
        issues: { infrastructure: 8 },
        caucuses: { empresarial: 6, sindical: -5 },
        tags: ['liberal'],
        politicalCost: 30,
        implementationMonths: 12,
      }),
      opt({
        id: 'infra_ppp',
        name: 'Parcerias público-privadas',
        description: 'Riscos e investimentos compartilhados entre o Estado e as empresas.',
        ideology: { economy: 65, fiscal: 55 },
        budget: { infrastructure: 0.04 },
        modifiers: { privateInvestmentMult: 1.03, productivity: 0.006 },
        economy: { confidence: 3 },
        pops: { business: 4, workers: 2, civil_servants: -2 },
        groups: { business: 6, industry: 4, unions: -4, civil_servants: -3, social_movements: -3 },
        issues: { infrastructure: 7, transport: 4 },
        caucuses: { empresarial: 4, sindical: -2 },
        politicalCost: 20,
        implementationMonths: 10,
      }),
      opt({
        id: 'infra_big_plan',
        name: 'Plano nacional de obras',
        description: 'Grande programa estatal de investimento em estradas, energia e saneamento.',
        ideology: { economy: 20, fiscal: 35 },
        budget: { infrastructure: 0.3 },
        modifiers: { stateConstructionDiscount: 0.1, productivity: 0.01 },
        economy: { inflation: 0.3, confidence: -2 },
        pops: { workers: 6, industrial_workers: 5, unemployed: 6, business: -2, middle_class: -3 },
        groups: { industry: 8, workers: 8, unions: 6, business: -5 },
        issues: { infrastructure: 12, transport: 6, jobs: 4 },
        caucuses: { sindical: 4, ruralista: 2, empresarial: -1 },
        tags: ['developmentalist'],
        politicalCost: 30,
        implementationMonths: 12,
      }),
    ],
  }),

  // ===========================================================================
  // SOCIEDADE
  // ===========================================================================
  category({
    id: 'education',
    branch: 'sociedade',
    name: 'Educação',
    icon: 'graduation-cap',
    instrument: 'pl',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Modelo de ensino público.',
    defaultOptionId: 'edu_public',
    options: [
      opt({
        id: 'edu_public',
        name: 'Ensino público tradicional',
        description: 'Rede pública universal com o financiamento atual.',
        ideology: { economy: 45, social: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'edu_fulltime',
        name: 'Escola em tempo integral',
        description: 'Jornada estendida e mais investimento na rede pública.',
        ideology: { economy: 30, social: 40 },
        budget: { education: 0.18 },
        economy: { growth: 0.1 },
        pops: { students: 7, workers: 3, civil_servants: 4, middle_class: 2, business: -3 },
        groups: { youth: 8, civil_servants: 6, unions: 4, business: -4 },
        issues: { education: 10 },
        caucuses: { sindical: 2, empresarial: -2 },
        tags: ['social_democratic'],
        politicalCost: 20,
        implementationMonths: 12,
      }),
      opt({
        id: 'edu_vouchers',
        name: 'Vouchers educacionais',
        description: 'O Estado paga a escola escolhida pela família, pública ou privada.',
        ideology: { economy: 80, social: 60 },
        budget: { education: 0.05 },
        pops: { middle_class: 5, business: 4, merchants: 2, civil_servants: -7, students: -2 },
        groups: { business: 6, civil_servants: -12, unions: -8, social_movements: -6 },
        issues: { education: 4 },
        caucuses: { evangelica: 8, empresarial: 4, sindical: -6 },
        tags: ['liberal', 'conservative'],
        politicalCost: 30,
        implementationMonths: 10,
      }),
      opt({
        id: 'edu_tech',
        name: 'Ensino técnico em massa',
        description: 'Foco em formação profissional para a indústria e os serviços.',
        ideology: { economy: 58, social: 50 },
        budget: { education: 0.08 },
        modifiers: {
          productivityBySector: { manufacturing: 0.015, high_tech: 0.01 },
          informality: -0.01,
        },
        pops: { students: 4, industrial_workers: 3, unemployed: 3, business: 3, civil_servants: -3 },
        groups: { industry: 8, youth: 5, tech: 4, civil_servants: -4 },
        issues: { education: 6, jobs: 3 },
        caucuses: { empresarial: 4 },
        politicalCost: 20,
        implementationMonths: 10,
      }),
    ],
  }),
  category({
    id: 'healthcare',
    branch: 'sociedade',
    name: 'Saúde',
    icon: 'heart-pulse',
    instrument: 'pl',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Modelo do sistema de saúde.',
    defaultOptionId: 'health_universal',
    options: [
      opt({
        id: 'health_universal',
        name: 'Sistema universal',
        description: 'Saúde pública gratuita para todos (modelo atual).',
        ideology: { economy: 35, fiscal: 45 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'health_expanded',
        name: 'Sistema universal ampliado',
        description: 'Mais hospitais, médicos e programas na rede pública.',
        ideology: { economy: 20, fiscal: 30 },
        budget: { health: 0.2 },
        pops: { retirees: 7, health_workers: 6, unemployed: 5, workers: 4, business: -3 },
        groups: { retirees: 10, social_movements: 6, unions: 4, business: -4 },
        issues: { healthcare: 12 },
        caucuses: { sindical: 3, empresarial: -2 },
        tags: ['social_democratic'],
        politicalCost: 25,
        implementationMonths: 12,
      }),
      opt({
        id: 'health_mixed',
        name: 'Gestão com parceiros privados',
        description: 'Organizações sociais e parcerias para reduzir as filas.',
        ideology: { economy: 65, fiscal: 55 },
        budget: { health: 0.03 },
        economy: { confidence: 2 },
        pops: { middle_class: 4, business: 3, health_workers: -3, civil_servants: -3 },
        groups: { business: 5, civil_servants: -6 },
        issues: { healthcare: 6 },
        caucuses: { empresarial: 3, sindical: -2 },
        politicalCost: 20,
        implementationMonths: 8,
      }),
      opt({
        id: 'health_private',
        name: 'Seguro-saúde incentivado',
        description: 'Subsídio a planos privados e rede pública mínima.',
        ideology: { economy: 85, fiscal: 72 },
        budget: { health: -0.15 },
        economy: { confidence: 4 },
        pops: { business: 6, middle_class: 3, retirees: -8, unemployed: -8, health_workers: -5 },
        groups: { business: 8, retirees: -12, social_movements: -12 },
        issues: { healthcare: -4 },
        caucuses: { empresarial: 5, sindical: -5 },
        tags: ['liberal'],
        politicalCost: 35,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'security',
    branch: 'sociedade',
    name: 'Segurança pública',
    icon: 'shield',
    instrument: 'pl',
    levels: ['federal', 'estadual', 'municipal'],
    description: 'Abordagem do Estado contra o crime.',
    defaultOptionId: 'sec_balanced',
    options: [
      opt({
        id: 'sec_balanced',
        name: 'Modelo atual',
        description: 'Policiamento e justiça criminal como hoje.',
        ideology: { security: 55, social: 55, institutions: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'sec_punitive',
        name: 'Tolerância zero',
        description: 'Mais polícia, penas maiores e mais prisões.',
        ideology: { security: 90, social: 72, institutions: 40 },
        budget: { security: 0.2 },
        pops: { merchants: 7, retirees: 5, middle_class: 3, students: -5, unemployed: -3 },
        groups: { commerce: 8, retirees: 5, social_movements: -12, youth: -6 },
        issues: { security: 12 },
        caucuses: { seguranca: 10, evangelica: 6, ruralista: 3 },
        tags: ['conservative'],
        politicalCost: 25,
        implementationMonths: 8,
      }),
      opt({
        id: 'sec_preventive',
        name: 'Prevenção social',
        description: 'Escolas, esporte, iluminação e mediação de conflitos.',
        ideology: { security: 15, social: 30, institutions: 60 },
        budget: { security: 0.05, social: 0.06 },
        pops: { students: 6, unemployed: 3, workers: 2, merchants: -4, retirees: -2 },
        groups: { social_movements: 10, youth: 6, commerce: -5 },
        issues: { security: 5 },
        caucuses: { ambientalista: 2, evangelica: -3, seguranca: -10 },
        tags: ['progressive'],
        politicalCost: 25,
        implementationMonths: 12,
      }),
      opt({
        id: 'sec_intelligence',
        name: 'Inteligência e tecnologia',
        description: 'Investigação, câmeras e integração de dados policiais.',
        ideology: { security: 58, social: 50, institutions: 38 },
        budget: { security: 0.1 },
        pops: { middle_class: 4, tech_workers: 4, merchants: 3, students: -2 },
        groups: { tech: 6, commerce: 4, social_movements: -4 },
        issues: { security: 9 },
        caucuses: { seguranca: 3 },
        politicalCost: 20,
        implementationMonths: 10,
      }),
    ],
  }),
  category({
    id: 'welfare',
    branch: 'sociedade',
    name: 'Assistência social',
    icon: 'hand-heart',
    instrument: 'pl',
    allowsMP: true,
    levels: ['federal'],
    description: 'Transferências de renda: para quem, quanto e com quais condições.',
    defaultOptionId: 'wel_targeted',
    options: [
      opt({
        id: 'wel_none',
        name: 'Sem transferência de renda',
        description:
          'Fim dos programas de renda; a assistência fica com municípios e entidades filantrópicas.',
        ideology: { economy: 95, fiscal: 95, social: 80 },
        modifiers: { transfers: {} },
        budget: { social: -0.3 },
        economy: { confidence: 4 },
        pops: { business: 6, merchants: 4, middle_class: 2, unemployed: -15, workers: -6, students: -3 },
        groups: {
          business: 8,
          commerce: 6,
          social_movements: -30,
          workers: -12,
          unions: -8,
          youth: -4,
        },
        issues: { taxes: 4, welfare: -10 },
        caucuses: { empresarial: 3, sindical: -6 },
        tags: ['liberal'],
        politicalCost: 40,
        implementationMonths: 6,
      }),
      opt({
        id: 'wel_targeted',
        name: 'Transferência focalizada',
        description:
          'Benefício para famílias pobres e desempregados, com condicionalidades (modelo atual).',
        ideology: { economy: 58, fiscal: 58, social: 50 },
        modifiers: { transfers: { unemployed: 300, workers: 60 } },
        politicalCost: 15,
        implementationMonths: 4,
      }),
      opt({
        id: 'wel_expanded',
        name: 'Rede de proteção ampliada',
        description:
          'Benefícios maiores e mais famílias atendidas, incluindo idosos pobres e estudantes.',
        ideology: { economy: 28, fiscal: 30, social: 35 },
        modifiers: { transfers: { unemployed: 500, workers: 120, retirees: 100, students: 80 } },
        budget: { social: 0.3 },
        economy: { inflation: 0.2, confidence: -3 },
        pops: { unemployed: 10, workers: 4, students: 4, retirees: 3, business: -6, middle_class: -4 },
        groups: { social_movements: 12, youth: 6, workers: 6, retirees: 4, unions: 5, business: -10 },
        issues: { welfare: 10, housing: 2 },
        caucuses: { sindical: 4, empresarial: -4 },
        tags: ['social_democratic'],
        politicalCost: 30,
        implementationMonths: 6,
      }),
      opt({
        id: 'wel_universal_income',
        name: 'Renda básica universal',
        description: 'Todo cidadão recebe uma renda mensal fixa, sem condições. Custo fiscal enorme.',
        ideology: { economy: 12, fiscal: 15, social: 25 },
        modifiers: {
          transfers: {
            workers: UNIVERSAL_INCOME,
            industrial_workers: UNIVERSAL_INCOME,
            farmers: UNIVERSAL_INCOME,
            business: UNIVERSAL_INCOME,
            merchants: UNIVERSAL_INCOME,
            middle_class: UNIVERSAL_INCOME,
            civil_servants: UNIVERSAL_INCOME,
            health_workers: UNIVERSAL_INCOME,
            tech_workers: UNIVERSAL_INCOME,
            students: UNIVERSAL_INCOME,
            retirees: UNIVERSAL_INCOME,
            unemployed: UNIVERSAL_INCOME,
          },
        },
        budget: { social: 3 },
        economy: { inflation: 0.6, confidence: -8 },
        pops: {
          unemployed: 15,
          students: 10,
          workers: 8,
          retirees: 5,
          farmers: 4,
          business: -10,
          middle_class: -6,
        },
        groups: {
          social_movements: 16,
          youth: 12,
          workers: 10,
          retirees: 6,
          commerce: 4,
          business: -20,
          industry: -8,
        },
        issues: { welfare: 15 },
        caucuses: { sindical: 3, empresarial: -6, ruralista: -3 },
        tags: ['progressive'],
        politicalCost: 60,
        implementationMonths: 12,
      }),
    ],
  }),
  category({
    id: 'science',
    branch: 'sociedade',
    name: 'Ciência e tecnologia',
    icon: 'flask-conical',
    instrument: 'pl',
    levels: ['federal'],
    description: 'Quanto o Estado investe em pesquisa e inovação.',
    defaultOptionId: 'sci_current',
    options: [
      opt({
        id: 'sci_minimal',
        name: 'Ciência mínima',
        description: 'Corte de bolsas e fundos de pesquisa; a inovação fica a cargo das empresas.',
        ideology: { economy: 78, fiscal: 80 },
        modifiers: { techRate: 0.6 },
        budget: { science: -0.5 },
        pops: {
          business: 3,
          merchants: 2,
          students: -8,
          tech_workers: -8,
          health_workers: -3,
          civil_servants: -3,
        },
        groups: { business: 4, commerce: 3, youth: -12, tech: -16, civil_servants: -6 },
        issues: { technology: -6, taxes: 2 },
        caucuses: { empresarial: 2, ambientalista: -5 },
        politicalCost: 25,
        implementationMonths: 4,
      }),
      opt({
        id: 'sci_current',
        name: 'Fomento atual',
        description: 'Universidades, agências de fomento e institutos públicos com o orçamento atual.',
        ideology: { economy: 50, fiscal: 50 },
        politicalCost: 10,
        implementationMonths: 4,
      }),
      opt({
        id: 'sci_innovation_state',
        name: 'Estado empreendedor',
        description:
          'Fundos públicos de inovação, institutos tecnológicos e encomendas tecnológicas do Estado.',
        ideology: { economy: 28, fiscal: 32 },
        modifiers: { techRate: 1.6 },
        budget: { science: 0.8 },
        pops: { tech_workers: 8, students: 6, health_workers: 2, business: -3, merchants: -2 },
        groups: { tech: 14, youth: 8, industry: 4, business: -4, commerce: -4 },
        issues: { technology: 10, education: 3 },
        caucuses: { ambientalista: 6, empresarial: 1 },
        tags: ['developmentalist'],
        politicalCost: 30,
        implementationMonths: 12,
      }),
    ],
  }),
];

export function getLawCategory(id: string): LawCategoryDefinition | undefined {
  return LAW_CATEGORIES.find((c) => c.id === id);
}

export function getLawOption(
  categoryId: string,
  optionId: string,
): LawOptionDefinition | undefined {
  return getLawCategory(categoryId)?.options.find((o) => o.id === optionId);
}

export function defaultLaws(): Record<string, string> {
  return Object.fromEntries(LAW_CATEGORIES.map((c) => [c.id, c.defaultOptionId]));
}
